// regret_capture_test.go — auto-generated by capture_go.sh
// DO NOT EDIT — this file is regenerated on each capture run.
package regrettest

import (
        stringspkg "github.com/regrets/test-go-example/strings"
        mathpkg "github.com/regrets/test-go-example/math"
        "reflect"
        "testing"
)

func TestRegretCapture(t *testing.T) {
  t.Run("reverse", func(t *testing.T) {
    var results []regretIO

    // Input 0
    var in0 interface{} = "hello"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 0 for reverse threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(stringspkg.Reverse), false, in0)
      if err != nil {
        t.Logf("⚠️  Input 0 for reverse error: %v", err)
        return
      }
      hash := fingerprint(in0, out)
      results = append(results, regretIO{Input: in0, Output: out, Hash: hash})
    }()

    // Input 1
    var in1 interface{} = "regrets"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 1 for reverse threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(stringspkg.Reverse), false, in1)
      if err != nil {
        t.Logf("⚠️  Input 1 for reverse error: %v", err)
        return
      }
      hash := fingerprint(in1, out)
      results = append(results, regretIO{Input: in1, Output: out, Hash: hash})
    }()

    // Input 2
    var in2 interface{} = "level"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 2 for reverse threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(stringspkg.Reverse), false, in2)
      if err != nil {
        t.Logf("⚠️  Input 2 for reverse error: %v", err)
        return
      }
      hash := fingerprint(in2, out)
      results = append(results, regretIO{Input: in2, Output: out, Hash: hash})
    }()

    if len(results) == 0 {
      t.Errorf("❌ reverse: all inputs threw/errored — no capture possible")
      return
    }
    if err := writeRegret("reverse", "Reverse", results); err != nil {
      t.Fatalf("write .regret for reverse: %v", err)
    }
    t.Logf("✅ reverse captured (hash: %s)", results[0].Hash)
  })

  t.Run("count-vowels", func(t *testing.T) {
    var results []regretIO

    // Input 0
    var in0 interface{} = "hello"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 0 for count-vowels threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(stringspkg.CountVowels), false, in0)
      if err != nil {
        t.Logf("⚠️  Input 0 for count-vowels error: %v", err)
        return
      }
      hash := fingerprint(in0, out)
      results = append(results, regretIO{Input: in0, Output: out, Hash: hash})
    }()

    // Input 1
    var in1 interface{} = "aeiou"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 1 for count-vowels threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(stringspkg.CountVowels), false, in1)
      if err != nil {
        t.Logf("⚠️  Input 1 for count-vowels error: %v", err)
        return
      }
      hash := fingerprint(in1, out)
      results = append(results, regretIO{Input: in1, Output: out, Hash: hash})
    }()

    // Input 2
    var in2 interface{} = "xyz"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 2 for count-vowels threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(stringspkg.CountVowels), false, in2)
      if err != nil {
        t.Logf("⚠️  Input 2 for count-vowels error: %v", err)
        return
      }
      hash := fingerprint(in2, out)
      results = append(results, regretIO{Input: in2, Output: out, Hash: hash})
    }()

    if len(results) == 0 {
      t.Errorf("❌ count-vowels: all inputs threw/errored — no capture possible")
      return
    }
    if err := writeRegret("count-vowels", "CountVowels", results); err != nil {
      t.Fatalf("write .regret for count-vowels: %v", err)
    }
    t.Logf("✅ count-vowels captured (hash: %s)", results[0].Hash)
  })

  t.Run("add", func(t *testing.T) {
    var results []regretIO

    // Input 0
    var in0 interface{} = []interface{}{1, 2}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 0 for add threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(mathpkg.Add), true, in0)
      if err != nil {
        t.Logf("⚠️  Input 0 for add error: %v", err)
        return
      }
      hash := fingerprint(in0, out)
      results = append(results, regretIO{Input: in0, Output: out, Hash: hash})
    }()

    // Input 1
    var in1 interface{} = []interface{}{10, 20}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 1 for add threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(mathpkg.Add), true, in1)
      if err != nil {
        t.Logf("⚠️  Input 1 for add error: %v", err)
        return
      }
      hash := fingerprint(in1, out)
      results = append(results, regretIO{Input: in1, Output: out, Hash: hash})
    }()

    // Input 2
    var in2 interface{} = []interface{}{-5, 5}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 2 for add threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(mathpkg.Add), true, in2)
      if err != nil {
        t.Logf("⚠️  Input 2 for add error: %v", err)
        return
      }
      hash := fingerprint(in2, out)
      results = append(results, regretIO{Input: in2, Output: out, Hash: hash})
    }()

    if len(results) == 0 {
      t.Errorf("❌ add: all inputs threw/errored — no capture possible")
      return
    }
    if err := writeRegret("add", "Add", results); err != nil {
      t.Fatalf("write .regret for add: %v", err)
    }
    t.Logf("✅ add captured (hash: %s)", results[0].Hash)
  })

}
