// regret_helpers_test.go — auto-generated by capture_go.sh
// DO NOT EDIT — shared fingerprint + reflect helpers for capture/validate tests.
package regrettest

import (
        "crypto/sha256"
        "encoding/json"
        "fmt"
        "math"
        "math/big"
        "os"
        "reflect"
        "sort"
        "strings"
        "time"
)

// stableStringify produces a deterministic JSON string with sorted keys.
// Must produce identical output to JS stableStringify() and Python stable_dumps().
//
// Edge cases that must match the JS implementation (issue #322):
//   - NaN → "__nan__" sentinel (JSON.stringify would emit "null")
//   - +Inf → "__infinity__"
//   - -Inf → "__neg_infinity__"
func stableStringify(obj interface{}) string {
        return doStableStringify(obj)
}

func doStableStringify(obj interface{}) string {
        if obj == nil {
                return "null"
        }
        switch v := obj.(type) {
        case bool:
                if v {
                        return "true"
                }
                return "false"
        case int:
                return fmt.Sprintf("%d", v)
        case int64:
                return fmt.Sprintf("%d", v)
        case float64:
                if math.IsNaN(v) {
                        return "\"__nan__\""
                }
                if math.IsInf(v, 1) {
                        return "\"__infinity__\""
                }
                if math.IsInf(v, -1) {
                        return "\"__neg_infinity__\""
                }
                return fmt.Sprintf("%g", v)
        case string:
                b, _ := json.Marshal(v)
                return string(b)
        case []interface{}:
                parts := make([]string, len(v))
                for i, item := range v {
                        parts[i] = doStableStringify(item)
                }
                return "[" + joinStrings(parts, ",") + "]"
        case map[string]interface{}:
                keys := make([]string, 0, len(v))
                for k := range v {
                        keys = append(keys, k)
                }
                sort.Strings(keys)
                parts := make([]string, len(keys))
                for i, k := range keys {
                        b, _ := json.Marshal(k)
                        parts[i] = string(b) + ":" + doStableStringify(v[k])
                }
                return "{" + joinStrings(parts, ",") + "}"
        default:
                b, _ := json.Marshal(v)
                return string(b)
        }
}

func joinStrings(ss []string, sep string) string {
        result := ""
        for i, s := range ss {
                if i > 0 {
                        result += sep
                }
                result += s
        }
        return result
}

// toBase36 converts a big.Int to base36 string (lowercase).
// Must produce identical output to JS BigInt.toString(36) and Python to_base36().
func toBase36(n *big.Int) string {
        if n.Sign() == 0 {
                return "0"
        }
        chars := "0123456789abcdefghijklmnopqrstuvwxyz"
        base := big.NewInt(36)
        zero := big.NewInt(0)
        result := ""
        remainder := new(big.Int)
        temp := new(big.Int).Set(n)
        if temp.Sign() < 0 {
                temp.Abs(temp)
        }
        for temp.Cmp(zero) > 0 {
                temp.DivMod(temp, base, remainder)
                result = string(chars[int(remainder.Int64())]) + result
        }
        return result
}

// fingerprint computes the 7-char base36 fingerprint.
// IDENTICAL algorithm to fingerprint.js / fingerprint.py:
//   sha256(stableStringify(input) + "|" + stableStringify(output)) → base36 → first 7 chars
func fingerprint(input interface{}, output interface{}) string {
        combined := stableStringify(input) + "|" + stableStringify(output)
        hash := sha256.Sum256([]byte(combined))
        hexStr := fmt.Sprintf("%x", hash)
        bigNum := new(big.Int)
        bigNum.SetString(hexStr, 16)
        b36 := toBase36(bigNum)
        if len(b36) >= 7 {
                return b36[:7]
        }
        return b36
}

// regretIO holds a single input/output/hash triple.
type regretIO struct {
        Input  interface{}
        Output interface{}
        Hash   string
}

// writeRegret builds and writes a .regret file for the given cluster.
// Format matches capture.js: cluster/version/fingerprint/captured/entry/
// stack/fingerprintLevel header, then --- separator, then
// INPUT/OUTPUT/HASH for the first result, then INPUTS for results[1+].
func writeRegret(id, entry string, results []regretIO) error {
        if len(results) == 0 {
                return fmt.Errorf("no results for cluster %s", id)
        }
        fp := results[0].Hash
        timestamp := time.Now().UTC().Format(time.RFC3339)
        var b strings.Builder
        b.WriteString("cluster: " + id + "\n")
        b.WriteString("version: 1\n")
        b.WriteString("fingerprint: " + fp + "\n")
        b.WriteString("captured: " + timestamp + "\n")
        b.WriteString("entry: " + entry + "\n")
        b.WriteString("stack: go\n")
        b.WriteString("fingerprintLevel: entry\n")
        b.WriteString("---\n")
        inBytes, _ := json.Marshal(results[0].Input)
        outBytes, _ := json.Marshal(results[0].Output)
        b.WriteString("INPUT  " + string(inBytes) + "\n")
        b.WriteString("OUTPUT " + string(outBytes) + "\n")
        b.WriteString("HASH   " + results[0].Hash + "\n")
        if len(results) > 1 {
                rest := make([]map[string]interface{}, 0, len(results)-1)
                for k := 1; k < len(results); k++ {
                        rest = append(rest, map[string]interface{}{
                                "input":  results[k].Input,
                                "output": results[k].Output,
                                "hash":   results[k].Hash,
                        })
                }
                restBytes, _ := json.Marshal(rest)
                b.WriteString("INPUTS " + string(restBytes) + "\n")
        }
        regretPath := id + ".regret"
        return os.WriteFile(regretPath, []byte(b.String()), 0644)
}

// adaptArg converts a JSON-parsed interface{} value to the target reflect.Type.
// Handles common conversions: float64→int, float64→int64, int→float64, etc.
// This bridges the gap between JSON's float64-only number type and Go's typed
// function parameters.
func adaptArg(v interface{}, target reflect.Type) (reflect.Value, error) {
        if v == nil {
                return reflect.Zero(target), nil
        }
        rv := reflect.ValueOf(v)
        if rv.Type() == target {
                return rv, nil
        }
        // float64 → int/int64 conversion (JSON decodes all numbers as float64)
        if rv.Kind() == reflect.Float64 && (target.Kind() == reflect.Int || target.Kind() == reflect.Int64 || target.Kind() == reflect.Int32 || target.Kind() == reflect.Int16 || target.Kind() == reflect.Int8) {
                return rv.Convert(target), nil
        }
        // int → float64
        if rv.Kind() == reflect.Int && target.Kind() == reflect.Float64 {
                return rv.Convert(target), nil
        }
        if rv.Type().ConvertibleTo(target) {
                return rv.Convert(target), nil
        }
        return reflect.Value{}, fmt.Errorf("cannot convert %v to %v", rv.Type(), target)
}

// invokeEntry invokes fn via reflection. If multiArgs is true, input must be an
// array; each element is converted to the corresponding parameter type via
// adaptArg. If input is nil, the function is called with zero args.
// Returns the result(s) as a single interface{} (or []interface{}
// for multi-return functions). If the last return is a non-nil error,
// it is returned as the Go error from this function.
func invokeEntry(fn reflect.Value, multiArgs bool, input interface{}) (interface{}, error) {
        fnType := fn.Type()
        var args []interface{}

        if input == nil {
                // Zero-arg call
                args = []interface{}{}
        } else if multiArgs {
                arr, ok := input.([]interface{})
                if !ok {
                        return nil, fmt.Errorf("multiArgs input is not an array (got %T)", input)
                }
                args = arr
        } else {
                args = []interface{}{input}
        }

        if fnType.NumIn() != len(args) {
                return nil, fmt.Errorf("entry expects %d args, got %d", fnType.NumIn(), len(args))
        }

        reflectArgs := make([]reflect.Value, len(args))
        for i, a := range args {
                av, err := adaptArg(a, fnType.In(i))
                if err != nil {
                        return nil, fmt.Errorf("arg %d: %w", i, err)
                }
                reflectArgs[i] = av
        }

        callResults := fn.Call(reflectArgs)
        if len(callResults) == 0 {
                return nil, nil
        }

        // Check if last return is a non-nil error
        lastResult := callResults[len(callResults)-1]
        if errVal, ok := lastResult.Interface().(error); ok && errVal != nil {
                return nil, errVal
        }

        if len(callResults) == 1 {
                return callResults[0].Interface(), nil
        }

        // Multiple return values — include all (including nil error as nil)
        arr := make([]interface{}, len(callResults))
        for k, r := range callResults {
                arr[k] = r.Interface()
        }
        return arr, nil
}

// parseRegret extracts INPUT, OUTPUT, HASH, and INPUTS fields from a .regret
// file's content. Returns the first input/output/hash plus the INPUTS array
// (for multi-input clusters, inputs[1+]).
func parseRegret(content string) (input interface{}, output interface{}, hash string, inputsList []map[string]interface{}, err error) {
        lines := strings.Split(content, "\n")
        var inputData, outputData, hashData, inputsData string
        for _, line := range lines {
                if strings.HasPrefix(line, "INPUTS ") && inputsData == "" {
                        inputsData = strings.TrimSpace(strings.TrimPrefix(line, "INPUTS"))
                } else if strings.HasPrefix(line, "INPUT ") && inputData == "" {
                        inputData = strings.TrimSpace(strings.TrimPrefix(line, "INPUT"))
                } else if strings.HasPrefix(line, "OUTPUT ") && outputData == "" {
                        outputData = strings.TrimSpace(strings.TrimPrefix(line, "OUTPUT"))
                } else if strings.HasPrefix(line, "HASH ") && hashData == "" {
                        hashData = strings.TrimSpace(strings.TrimPrefix(line, "HASH"))
                }
        }
        if inputData != "" {
                if e := json.Unmarshal([]byte(inputData), &input); e != nil {
                        err = fmt.Errorf("parse INPUT: %w", e)
                        return
                }
        }
        if outputData != "" {
                if e := json.Unmarshal([]byte(outputData), &output); e != nil {
                        err = fmt.Errorf("parse OUTPUT: %w", e)
                        return
                }
        }
        hash = hashData
        if inputsData != "" {
                if e := json.Unmarshal([]byte(inputsData), &inputsList); e != nil {
                        err = fmt.Errorf("parse INPUTS: %w", e)
                        return
                }
        }
        return
}
