// regret_validate_test.go — auto-generated by capture_go.sh
// DO NOT EDIT — this file is regenerated on each validate run.
package regrettest

import (
        stringspkg "github.com/regrets/test-go-example/strings"
        mathpkg "github.com/regrets/test-go-example/math"
        "os"
        "reflect"
        "testing"
)

func TestRegretValidate(t *testing.T) {
  t.Run("reverse", func(t *testing.T) {
    regretPath := "reverse.regret"
    data, err := os.ReadFile(regretPath)
    if err != nil {
      t.Fatalf("read .regret for reverse: %v", err)
    }
    gInput, _, gHash, gInputsList, err := parseRegret(string(data))
    if err != nil {
      t.Fatalf("parse .regret for reverse: %v", err)
    }

    // Validate the primary input
    out, err := invokeEntry(reflect.ValueOf(stringspkg.Reverse), false, gInput)
    if err != nil {
      t.Fatalf("invoke Reverse: %v", err)
    }
    newHash := fingerprint(gInput, out)
    if newHash != gHash {
      t.Errorf("❌ reverse FAIL — expected %s got %s", gHash, newHash)
    } else {
      t.Logf("✅ reverse %s PASS", newHash)
    }

    // Validate INPUTS[1+] if present
    for i, item := range gInputsList {
      inVal := item["input"]
      expectedHash := item["hash"].(string)
      outN, err := invokeEntry(reflect.ValueOf(stringspkg.Reverse), false, inVal)
      if err != nil {
        t.Errorf("❌ reverse INPUTS[%d] invoke error: %v", i, err)
        continue
      }
      gotHash := fingerprint(inVal, outN)
      if gotHash != expectedHash {
        t.Errorf("❌ reverse INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)
      } else {
        t.Logf("✅ reverse INPUTS[%d] %s PASS", i, gotHash)
      }
    }
  })

  t.Run("count-vowels", func(t *testing.T) {
    regretPath := "count-vowels.regret"
    data, err := os.ReadFile(regretPath)
    if err != nil {
      t.Fatalf("read .regret for count-vowels: %v", err)
    }
    gInput, _, gHash, gInputsList, err := parseRegret(string(data))
    if err != nil {
      t.Fatalf("parse .regret for count-vowels: %v", err)
    }

    // Validate the primary input
    out, err := invokeEntry(reflect.ValueOf(stringspkg.CountVowels), false, gInput)
    if err != nil {
      t.Fatalf("invoke CountVowels: %v", err)
    }
    newHash := fingerprint(gInput, out)
    if newHash != gHash {
      t.Errorf("❌ count-vowels FAIL — expected %s got %s", gHash, newHash)
    } else {
      t.Logf("✅ count-vowels %s PASS", newHash)
    }

    // Validate INPUTS[1+] if present
    for i, item := range gInputsList {
      inVal := item["input"]
      expectedHash := item["hash"].(string)
      outN, err := invokeEntry(reflect.ValueOf(stringspkg.CountVowels), false, inVal)
      if err != nil {
        t.Errorf("❌ count-vowels INPUTS[%d] invoke error: %v", i, err)
        continue
      }
      gotHash := fingerprint(inVal, outN)
      if gotHash != expectedHash {
        t.Errorf("❌ count-vowels INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)
      } else {
        t.Logf("✅ count-vowels INPUTS[%d] %s PASS", i, gotHash)
      }
    }
  })

  t.Run("add", func(t *testing.T) {
    regretPath := "add.regret"
    data, err := os.ReadFile(regretPath)
    if err != nil {
      t.Fatalf("read .regret for add: %v", err)
    }
    gInput, _, gHash, gInputsList, err := parseRegret(string(data))
    if err != nil {
      t.Fatalf("parse .regret for add: %v", err)
    }

    // Validate the primary input
    out, err := invokeEntry(reflect.ValueOf(mathpkg.Add), true, gInput)
    if err != nil {
      t.Fatalf("invoke Add: %v", err)
    }
    newHash := fingerprint(gInput, out)
    if newHash != gHash {
      t.Errorf("❌ add FAIL — expected %s got %s", gHash, newHash)
    } else {
      t.Logf("✅ add %s PASS", newHash)
    }

    // Validate INPUTS[1+] if present
    for i, item := range gInputsList {
      inVal := item["input"]
      expectedHash := item["hash"].(string)
      outN, err := invokeEntry(reflect.ValueOf(mathpkg.Add), true, inVal)
      if err != nil {
        t.Errorf("❌ add INPUTS[%d] invoke error: %v", i, err)
        continue
      }
      gotHash := fingerprint(inVal, outN)
      if gotHash != expectedHash {
        t.Errorf("❌ add INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)
      } else {
        t.Logf("✅ add INPUTS[%d] %s PASS", i, gotHash)
      }
    }
  })

}
