// _dart_capture_gen.js — Node-side generator for the per-cluster Dart runner.
// Invoked by capture_dart.sh.
//
// Args: <cluster_json_file> <output_runner_path> <fingerprint_helper_path>
//
// Reads the cluster JSON (a single cluster object), generates a Dart runner
// that imports the user's target file + the fingerprint helper, invokes the
// entry function with each declared input, captures the output, computes the
// fingerprint, and prints a JSON array of {input, output, hash} results to
// stdout for the shell wrapper to consume.

const fs = require('fs');
const path = require('path');

const [, , clusterFile, runnerPath, fingerprintHelperPath] = process.argv;

if (!clusterFile || !runnerPath || !fingerprintHelperPath) {
  console.error('Usage: _dart_capture_gen.js <cluster_json_file> <output_runner_path> <fingerprint_helper_path>');
  process.exit(2);
}

const cluster = JSON.parse(fs.readFileSync(clusterFile, 'utf8'));
const projectDir = process.cwd();
const entry = cluster.entry;
const file = cluster.file || cluster.entryPath;
const inputs = cluster.inputs || [null];
const multiArgs = !!cluster.multiArgs;

if (!file) {
  console.error(`Cluster ${cluster.id} missing "file" field (Dart requires a relative path to the .dart source).`);
  process.exit(2);
}

const absTarget = path.resolve(projectDir, file);

// Build the runner source. We use string concatenation so the entry name
// is injected as a literal Dart identifier (no reflection needed at runtime).
const lines = [];
lines.push('// Auto-generated by capture_dart.sh — do not edit.');
lines.push("import 'dart:convert';");
lines.push("import 'dart:io';");
lines.push(`import '${absTarget}' as target;`);
lines.push(`import '${fingerprintHelperPath}' as fp;`);
lines.push('');
lines.push('void main(List<String> args) {');
lines.push('  final inputs = ' + JSON.stringify(inputs) + ';');
lines.push('  final multiArgs = ' + multiArgs + ';');
lines.push('  final cluster = ' + JSON.stringify(cluster) + ';');
lines.push('  final results = <Map<String, dynamic>>[];');
lines.push('  for (final input in inputs) {');
lines.push('    Object? output;');
lines.push('    Object? inputValue = input;');
lines.push('    try {');
if (multiArgs) {
  // multiArgs: input is always a List (positional args). Use Function.apply.
  // Skip the dead `else` branch entirely — Dart's static type-checker would
  // reject `target.<entry>(input)` for multi-arg functions even though the
  // branch is unreachable at runtime.
  lines.push('      if (input is List) {');
  lines.push(`        final fn = target.${entry} as Function;`);
  lines.push('        output = Function.apply(fn, input);');
  lines.push('      } else {');
  lines.push("        // Should never happen for multiArgs clusters.");
  lines.push("        throw StateError('multiArgs cluster got non-list input');");
  lines.push('      }');
} else {
  lines.push(`      output = target.${entry}(input);`);
}
lines.push('    } catch (e, st) {');
lines.push("      stderr.writeln('[capture_dart] cluster ${cluster['id']} input threw: ${e.toString()}');");
lines.push('      continue;');
lines.push('    }');
lines.push('    // Trivial-output guard: null / NaN / Infinity → skip this input.');
lines.push('    if (output == null) {');
lines.push("      stderr.writeln('[capture_dart] cluster ${cluster['id']} output null → skipped');");
lines.push('      continue;');
lines.push('    }');
lines.push('    if (output is double && (output.isNaN || output.isInfinite)) {');
lines.push("      stderr.writeln('[capture_dart] cluster ${cluster['id']} output NaN/Inf → skipped');");
lines.push('      continue;');
lines.push('    }');
lines.push('    final hash = fp.fingerprint(inputValue, output);');
lines.push('    results.add({');
lines.push('      "input": inputValue,');
lines.push('      "output": output,');
lines.push('      "hash": hash,');
lines.push('    });');
lines.push('  }');
lines.push('  // Emit results as JSON to stdout for the shell wrapper to write .regret files.');
lines.push('  stdout.write(jsonEncode(results));');
lines.push('}');

fs.writeFileSync(runnerPath, lines.join('\n') + '\n');
console.error(`[capture_dart_gen] wrote runner: ${runnerPath}`);
