// _dart_validate_gen.js — Node-side generator for the per-cluster Dart validate runner.
// Invoked by validate_dart.sh.
//
// Args: <cluster_meta_json_file> <output_runner_path> <fingerprint_helper_path>
//
// cluster_meta_json has shape:
//   { id, entry, file, multiArgs, input, golden_output, golden_hash }
//
// Generates a Dart runner that:
//   1. Imports the user's target file + the fingerprint helper.
//   2. Invokes the entry function with `input`.
//   3. Computes the live fingerprint.
//   4. Prints JSON {output, error, hash} to stdout for the shell wrapper to
//      compare against the golden hash.

const fs = require('fs');
const path = require('path');

const [, , metaFile, runnerPath, fingerprintHelperPath] = process.argv;

if (!metaFile || !runnerPath || !fingerprintHelperPath) {
  console.error('Usage: _dart_validate_gen.js <meta_json_file> <output_runner_path> <fingerprint_helper_path>');
  process.exit(2);
}

const cm = JSON.parse(fs.readFileSync(metaFile, 'utf8'));
const projectDir = process.cwd();
const absTarget = path.resolve(projectDir, cm.file);
const entry = cm.entry;
const multiArgs = !!cm.multiArgs;

const lines = [];
lines.push('// Auto-generated by validate_dart.sh — do not edit.');
lines.push("import 'dart:convert';");
lines.push("import 'dart:io';");
lines.push(`import '${absTarget}' as target;`);
lines.push(`import '${fingerprintHelperPath}' as fp;`);
lines.push('');
lines.push('void main() {');
lines.push('  final cm = ' + JSON.stringify(cm) + ';');
lines.push('  Object? output;');
lines.push('  String? error;');
lines.push('  try {');
// Always use Function.apply — sidesteps Dart 3 strict type-checking on the
// `cm['input']` Object? value (which JSON.parse produces at runtime). For
// multiArgs clusters, input is already a List of positional args; for
// single-arg clusters, wrap input in a one-element list.
lines.push(`    final fn = target.${entry} as Function;`);
lines.push("    final List args = (cm['multiArgs'] == true && cm['input'] is List)");
lines.push("        ? (cm['input'] as List)");
lines.push("        : [cm['input']];");
lines.push('    output = Function.apply(fn, args);');
lines.push('  } catch (e) {');
lines.push('    error = e.toString();');
lines.push('  }');
lines.push("  final hash = fp.fingerprint(cm['input'], output);");
lines.push('  stdout.write(jsonEncode({');
lines.push('    "output": output,');
lines.push('    "error": error,');
lines.push('    "hash": hash,');
lines.push('  }));');
lines.push('}');

fs.writeFileSync(runnerPath, lines.join('\n') + '\n');
console.error(`[validate_dart_gen] wrote runner: ${runnerPath}`);
