#!/usr/bin/env node
// _julia_harness_gen.cjs — generate a per-cluster Julia harness file.
// Called by capture_julia.sh and validate_julia.sh.
//
// Args: <cluster_json> <harness_path> <scripts_dir>
// Outputs: writes the harness .jl file to <harness_path>
//
// The harness:
//   1. Activates the user's project env (if a Project.toml is alongside their source)
//   2. Includes the user's source file (so all top-level functions become visible)
//   3. Parses the embedded input JSON
//   4. Dispatches to the entry function based on the input's JSON type
//      (string, int, float, bool, array of those)
//   5. Computes the fingerprint and prints REGRET_INPUT/REGRET_OUTPUT/REGRET_HASH lines

const fs = require('fs');
const path = require('path');

const clusterJson = process.argv[2];
const harnessPath = process.argv[3];
const scriptsDir = process.argv[4]; // path to scripts/ dir (for fingerprint_julia.jl)

if (!clusterJson || !harnessPath || !scriptsDir) {
  console.error('Usage: _julia_harness_gen.cjs <cluster_json> <harness_path> <scripts_dir>');
  process.exit(1);
}

const cluster = JSON.parse(clusterJson);

const srcRelPath = cluster.file;
if (!srcRelPath) throw new Error('cluster.file is required for Julia stack');

const absSrcPath = path.resolve(process.cwd(), srcRelPath);
const absFingerprintPath = path.resolve(scriptsDir, 'fingerprint_julia.jl');

const inputs = cluster.inputs || [null];
if (inputs.length === 0) inputs.push(null);
const firstInput = inputs[0];

// Embed input as JSON in a Julia raw-string.
// Julia raw-strings use `r"..."` or triple-quoted strings, but both have
// issues with embedded quotes. The cleanest approach is:
//   1. JSON.stringify the input (produces a valid JSON string with proper escaping)
//   2. Embed it in a Julia `escape_string`-safe form using `replace` to escape
//      double-quotes for use in a regular Julia string literal.
//
// We use a regular double-quoted Julia string with `\"` escaping. JSON output
// never contains literal backslashes that aren't already escaped, so this is
// safe — we just need to escape the double-quotes that JSON adds.
const inputJSON = JSON.stringify(firstInput);
// Escape backslashes first, then double-quotes — same order as JSON.stringify
// output requires for a Julia double-quoted string.
const escapedInput = inputJSON
    .replace(/\\/g, '\\\\')  // escape backslashes
    .replace(/"/g, '\\"');   // escape double-quotes

const entry = cluster.entry;
if (!entry) throw new Error('cluster.entry is required');
if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(entry)) {
  throw new Error('cluster.entry must be a valid Julia identifier (got: ' + entry + ')');
}

// Build the harness source.
// We use `include` to load the user's source — all top-level functions become
// visible in Main scope. Then we dispatch by JSON type at runtime.
//
// The dispatch tries each conversion in turn:
//   1. String → entry(input_node.str)
//   2. Int64  → entry(input_node.val)
//   3. Float64→ entry(input_node.val)
//   4. Bool   → entry(input_node.val)
//   5. Vector{String} → entry(map(n -> n.str, input_node.array))
//   6. Vector{Int64}  → entry(map(n -> n.val, input_node.array))
//   7. Vector{Float64}→ entry(map(n -> n.val, input_node.array))
//   8. Vector{Any}    → entry(input_node.array) — fallthrough
//   9. fallback → entry(input_node) — pass the JSON node itself
//
// If the entry function's signature doesn't match any conversion, Julia will
// throw a MethodError which the bash wrapper will catch and report.
const harness = `# Auto-generated by capture_julia.sh — DO NOT EDIT
# Cluster: ${cluster.id}
# Generated: ${new Date().toISOString()}

include("${absFingerprintPath}")
include("${absSrcPath}")

using .RegretsFingerprint: stableStringify, fingerprint, toBase36
using JSON

const input_node = JSON.parse("${escapedInput}")

# Dispatch by JSON type.
function dispatch_entry(entry_sym::Symbol, node::Any)
    # Try string
    if node isa AbstractString
        fn = getfield(Main, entry_sym)
        return try
            fn(String(node))
        catch
            fn(node)
        end
    elseif node isa Number
        fn = getfield(Main, entry_sym)
        # Try Int first, then Float
        if node isa Integer
            return try fn(Int64(node)) catch; try fn(Float64(node)) catch; fn(node) end end
        else
            return try fn(Float64(node)) catch; fn(node) end
        end
    elseif node isa Bool
        fn = getfield(Main, entry_sym)
        return fn(node)
    elseif node isa AbstractVector
        fn = getfield(Main, entry_sym)
        if !isempty(node)
            first_el = node[1]
            if first_el isa AbstractString
                return try fn(String.(node)) catch; fn(node) end
            elseif first_el isa Number && !(first_el isa Bool)
                if first_el isa Integer
                    return try fn(Int64.(node)) catch; try fn(Float64.(node)) catch; fn(node) end end
                else
                    return try fn(Float64.(node)) catch; fn(node) end
                end
            end
        end
        return fn(node)
    else
        fn = getfield(Main, entry_sym)
        return fn(node)
    end
end

const output_val = dispatch_entry(Symbol("${entry}"), input_node)
const input_str = stableStringify(input_node)
const output_str = stableStringify(output_val)
const fp = fingerprint(input_node, output_val)

println("REGRET_INPUT ", input_str)
println("REGRET_OUTPUT ", output_str)
println("REGRET_HASH ", fp)
`;

fs.writeFileSync(harnessPath, harness);
