#!/usr/bin/env node
// _nim_harness_gen.js — generate a per-cluster Nim harness file.
// Called by capture_nim.sh and validate_nim.sh.
//
// Args: <cluster_json> <harness_path>
// Outputs: writes the harness .nim file to <harness_path>

const fs = require('fs');
const path = require('path');

const clusterJson = process.argv[2];
const harnessPath = process.argv[3];

if (!clusterJson || !harnessPath) {
  console.error('Usage: _nim_harness_gen.js <cluster_json> <harness_path>');
  process.exit(1);
}

const cluster = JSON.parse(clusterJson);

const srcRelPath = cluster.file;
if (!srcRelPath) throw new Error('cluster.file is required for Nim stack');

// Nim's `include "..."` argument is a double-quoted string literal, where
// a backslash starts an escape sequence (e.g. \x41). path.resolve() on
// native Windows produces backslash-separated paths, so any path segment
// starting with a letter that looks like a hex digit after the backslash
// (e.g. "...\slugify.nim") gets misparsed by Nim's lexer as a malformed
// escape ("expected a hex digit, but found: s"). Forward slashes work
// fine cross-platform in Nim, so normalize before embedding.
const absSrcPath = path.resolve(process.cwd(), srcRelPath).replaceAll('\\', '/');

const inputs = cluster.inputs || [null];
if (inputs.length === 0) inputs.push(null);
const firstInput = inputs[0];

// Embed input as JSON in a Nim triple-quoted string.
// Escape any internal triple-quotes (very unlikely in JSON, but safe).
const inputJSON = JSON.stringify(firstInput);
const escapedInput = inputJSON.replace(/"""/g, '\\"\\"\\"');

const entry = cluster.entry;
if (!entry) throw new Error('cluster.entry is required');
if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(entry)) {
  throw new Error('cluster.entry must be a valid Nim identifier (got: ' + entry + ')');
}

// Build the harness source
const harness = `# Auto-generated by capture_nim.sh — DO NOT EDIT
# Cluster: ${cluster.id}
# Generated: ${new Date().toISOString()}

import std/[json, strutils, sequtils, algorithm]
import fingerprint_nim

# Include user source — all symbols (private + public) become visible
include "${absSrcPath}"

# Compile-time dispatch: try various input-type conversions.
# The first compiles() branch that matches the entry proc's signature wins.
template invokeEntry(entrySym: untyped; inputNode: JsonNode): JsonNode =
  when compiles(entrySym(inputNode.getStr())):
    %entrySym(inputNode.getStr())
  elif compiles(entrySym(inputNode.getInt())):
    %entrySym(inputNode.getInt())
  elif compiles(entrySym(inputNode.getFloat())):
    %entrySym(inputNode.getFloat())
  elif compiles(entrySym(inputNode.getBool())):
    %entrySym(inputNode.getBool())
  elif compiles(entrySym(inputNode.getElems().mapIt(it.getStr()))):
    %entrySym(inputNode.getElems().mapIt(it.getStr()))
  elif compiles(entrySym(inputNode.getElems().mapIt(it.getInt()))):
    %entrySym(inputNode.getElems().mapIt(it.getInt()))
  elif compiles(entrySym(inputNode.getElems().mapIt(it.getFloat()))):
    %entrySym(inputNode.getElems().mapIt(it.getFloat()))
  elif compiles(entrySym(inputNode.getElems().mapIt(it.getBool()))):
    %entrySym(inputNode.getElems().mapIt(it.getBool()))
  elif compiles(entrySym(inputNode)):
    %entrySym(inputNode)
  else:
    raise newException(ValueError, "Entry proc does not accept any supported input type")

let inputNode = parseJson("""${escapedInput}""")
let outputNode = invokeEntry(${entry}, inputNode)
let fp = fingerprint(inputNode, outputNode)

# Output for the wrapper to parse — one key per line, JSON-encoded values
echo "REGRET_INPUT " & stableDumps(inputNode)
echo "REGRET_OUTPUT " & stableDumps(outputNode)
echo "REGRET_HASH " & fp
`;

fs.writeFileSync(harnessPath, harness);
