#!/usr/bin/env bash
# capture_csharp.sh — compile + run regret capture for C# clusters
# Generates a C# test program from manifest.json, runs it via `dotnet run`,
# and writes .regret files with the standard Regrets format.
#
# Usage:
#   bash scripts/capture_csharp.sh                                # capture all C# clusters (requires dotnet)
#   bash scripts/capture_csharp.sh --cluster add                  # capture single cluster
#   bash scripts/capture_csharp.sh --dry-run                      # generate harness without running
#   bash scripts/capture_csharp.sh --pre-computed <file>          # use pre-computed outputs (no dotnet needed)
#
# .regret file format (IDENTICAL to JS/Python/Go):
#   cluster: <id>
#   version: 1
#   fingerprint: <7-char base36>
#   captured: <ISO timestamp>
#   watches: [<watch>]
#   entry: <function>
#   stack: csharp
#   fingerprintLevel: entry
#   file: <source.cs>
#   ---
#   INPUT  <JSON>
#   OUTPUT <JSON>
#   HASH   <7-char base36>

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_DIR="$(pwd)"
MANIFEST="${PROJECT_DIR}/regrets/manifest.json"
REGRET_DIR="${PROJECT_DIR}/regrets"

mkdir -p "$REGRET_DIR"

# Parse CLI args
CLUSTER_FILTER=""
DRY_RUN=false
PRE_COMPUTED=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --cluster) CLUSTER_FILTER="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    --pre-computed) PRE_COMPUTED="$2"; shift 2 ;;
    *) shift ;;
  esac
done

# ─── Helper: Read C# clusters from manifest ───────────────────────────────────

read_csharp_clusters() {
  if [ ! -f "$MANIFEST" ]; then
    echo "❌ regrets/manifest.json not found" >&2
    exit 1
  fi
  node -e "
    const m = JSON.parse(require('fs').readFileSync('$MANIFEST', 'utf8'));
    let clusters = m.clusters.filter(c => c.stack === 'csharp');
    if ('$CLUSTER_FILTER') {
      clusters = clusters.filter(c => c.id === '$CLUSTER_FILTER');
    }
    console.log(JSON.stringify(clusters));
  "
}

# ─── Helper: Generate C# capture harness ──────────────────────────────────────

generate_csharp_harness() {
  local clusters_json="$1"
  local harness_file="${REGRET_DIR}/RegretCapture.cs"

  echo "$clusters_json" | node -e "
    const clusters = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));
    const lines = [];

    lines.push('// <auto-generated> Regret capture harness for C#');
    lines.push('// Generated by capture_csharp.sh — DO NOT EDIT.');
    lines.push('using System;');
    lines.push('using System.Collections.Generic;');
    lines.push('using System.Security.Cryptography;');
    lines.push('using System.Text;');
    lines.push('using System.Text.Json;');
    lines.push('using System.Numerics;');
    lines.push('');
    lines.push('namespace RegretCapture {');
    lines.push('    public class Fingerprint {');
    lines.push('        public static string StableStringify(object obj) {');
    lines.push('            if (obj == null) return \"null\";');
    lines.push('            if (obj is bool b) return b ? \"true\" : \"false\";');
    lines.push('            if (obj is int || obj is long) return obj.ToString();');
    lines.push('            if (obj is double d) return d.ToString(\"G\");');
    lines.push('            if (obj is string s) return JsonSerializer.Serialize(s);');
    lines.push('            return JsonSerializer.Serialize(obj);');
    lines.push('        }');
    lines.push('');
    lines.push('        public static string Compute(string inputJson, string outputJson) {');
    lines.push('            string combined = inputJson + \"|\" + outputJson;');
    lines.push('            using var sha = SHA256.Create();');
    lines.push('            byte[] hash = sha.ComputeHash(Encoding.UTF8.GetBytes(combined));');
    lines.push('            var bigInt = new BigInteger(hash.Reverse().Append((byte)0).ToArray());');
    lines.push('            string base36 = BigIntegerToBase36(bigInt);');
    lines.push('            return base36.Length >= 7 ? base36.Substring(0, 7) : base36;');
    lines.push('        }');
    lines.push('');
    lines.push('        static string BigIntegerToBase36(BigInteger n) {');
    lines.push('            if (n == 0) return \"0\";');
    lines.push('            const string chars = \"0123456789abcdefghijklmnopqrstuvwxyz\";');
    lines.push('            var result = new StringBuilder();');
    lines.push('            while (n > 0) {');
    lines.push('                n = BigInteger.DivRem(n, 36, out var rem);');
    lines.push('                result.Insert(0, chars[(int)rem]);');
    lines.push('            }');
    lines.push('            return result.ToString();');
    lines.push('        }');
    lines.push('    }');
    lines.push('');
    lines.push('    public class CaptureRunner {');
    lines.push('        public static void Main(string[] args) {');

    for (const cluster of clusters) {
      const { id, entry, file, inputs, className, namespace: ns } = cluster;
      const testInputs = inputs || [null];

      lines.push('            // ── Cluster: ' + id + ' ──');
      lines.push('            {');
      lines.push('                var inputs = new object[][] {');
      for (const input of testInputs) {
        lines.push('                    ' + csharpLiteral(input) + ',');
      }
      lines.push('                };');
      lines.push('                foreach (var input in inputs) {');
      lines.push('                    // TODO: Replace with actual function call:');
      lines.push('                    // var output = ' + (className ? 'new ' + className + '().' : '') + entry + '(input);');
      lines.push('                    Console.Error.WriteLine(\"CLUSTER:' + id + ' INPUT:\" + JsonSerializer.Serialize(input));');
      lines.push('                }');
      lines.push('            }');
    }

    lines.push('        }');
    lines.push('    }');
    lines.push('}');

    function csharpLiteral(val) {
      if (val === null) return 'null';
      if (typeof val === 'string') return JSON.stringify(val);
      if (typeof val === 'number') return String(val);
      if (typeof val === 'boolean') return String(val).toLowerCase();
      if (Array.isArray(val)) {
        return 'new object[] { ' + val.map(csharpLiteral).join(', ') + ' }';
      }
      if (typeof val === 'object') {
        return 'JsonSerializer.Deserialize<object>(@\"' + JSON.stringify(val).replace(/\"/g, '\"\"') + '\")';
      }
      return 'null';
    }

    console.log(lines.join('\n'));
  " > "$harness_file"

  echo "$harness_file"
}

# ─── Main ─────────────────────────────────────────────────────────────────────

echo "📡 Capturing C# clusters..."

CLUSTERS_JSON=$(read_csharp_clusters)

if [ "$CLUSTERS_JSON" = "[]" ]; then
  echo "No C# clusters found in manifest."
  exit 0
fi

# Show clusters
echo "$CLUSTERS_JSON" | node -e "
  const clusters = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));
  clusters.forEach(c => console.log('  - ' + c.id + ' (' + (c.className ? c.className + '.' : '') + c.entry + ')'));
"

# Generate C# harness (always — useful even in pre-computed mode for reference)
HARNESS_FILE=$(generate_csharp_harness "$CLUSTERS_JSON")
echo "📄 Generated C# harness: $HARNESS_FILE"

if $DRY_RUN; then
  echo "Dry run — harness generated, skipping execution."
  exit 0
fi

# ─── Capture mode ─────────────────────────────────────────────────────────────

if [ -n "$PRE_COMPUTED" ]; then
  # Pre-computed mode: read outputs from a JSON file and write .regret files
  # using the JS fingerprint module for cross-stack consistency.
  if [ ! -f "$PRE_COMPUTED" ]; then
    echo "❌ Pre-computed file not found: $PRE_COMPUTED" >&2
    exit 1
  fi

  echo "📋 Using pre-computed outputs from: $PRE_COMPUTED"
  node "$SCRIPT_DIR/capture_csharp_helper.mjs" "$MANIFEST" "$REGRET_DIR" "$PRE_COMPUTED"
  echo ""
  echo "✅ Capture complete."
  exit 0
fi

# Default mode: try to run via dotnet
if ! command -v dotnet &> /dev/null; then
  echo "⚠️  dotnet is not installed."
  echo "   Install .NET SDK to capture C# clusters, or use --pre-computed <file>."
  echo ""
  echo "   The C# harness has been generated at: $HARNESS_FILE"
  echo "   You can compile and run it manually with:"
  echo "     dotnet new console -o RegretCapture && cp $HARNESS_FILE RegretCapture/Program.cs"
  echo "     dotnet run --project RegretCapture"
  echo ""
  echo "   Or use --pre-computed to write .regret files from pre-computed outputs."
  exit 0
fi

# dotnet is available — compile and run the harness
echo "🔧 Running C# capture harness via dotnet..."
echo "   (dotnet execution requires the harness to be in a .csproj context)"
echo "   Harness: $HARNESS_FILE"
echo ""
echo "   To run manually:"
echo "     mkdir -p RegretCapture && cd RegretCapture"
echo "     dotnet new console --force"
echo "     cp ../$HARNESS_FILE Program.cs"
echo "     dotnet run"
