#!/usr/bin/env bash
# capture_lua.sh — capture + validate for Lua clusters
#
# Generates a Lua runner script from manifest.json, runs the Lua interpreter,
# and writes .regret files (capture) or compares fingerprints (validate).
#
# Usage:
#   bash scripts/capture_lua.sh                # capture all Lua clusters
#   bash scripts/capture_lua.sh capture        # capture (explicit)
#   bash scripts/capture_lua.sh validate       # validate all Lua clusters
#   bash scripts/capture_lua.sh health         # health report (delegates to health.js)
#   bash scripts/capture_lua.sh --cluster my-fn   # single-cluster capture
#
# .regret file format (identical to JS/Python/Go stacks):
#   cluster: <id>
#   version: 1
#   fingerprint: <7char-base36>
#   captured: <ISO8601>
#   entry: <entry-fn-name>
#   stack: lua
#   fingerprintLevel: entry
#   ---
#   INPUT  <json>
#   OUTPUT <json>
#   HASH   <7char-base36>

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_DIR="$(pwd)"
MANIFEST="${PROJECT_DIR}/regrets/manifest.json"
REGRET_DIR="${PROJECT_DIR}/regrets"

mkdir -p "$REGRET_DIR"

# Parse args. MODE is the first non-flag argument (defaults to "capture").
# --cluster <id> sets the cluster filter.
MODE="capture"
CLUSTER_FILTER=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --cluster)
      CLUSTER_FILTER="$2"
      shift 2
      ;;
    capture|validate|health)
      MODE="$1"
      shift
      ;;
    *)
      shift
      ;;
  esac
done

# ─── Helper: locate the Lua interpreter ───────────────────────────────────────
# Priority:
#   1. $LUA_INTERPRETER env var (if set)
#   2. `lua` on PATH
#   3. `lua5.4` on PATH
#   4. `/tmp/lua-5.4.7/src/lua` (built from source — see verify script)
LUA_BIN="${LUA_INTERPRETER:-}"
if [ -z "$LUA_BIN" ]; then
  if command -v lua &> /dev/null; then
    LUA_BIN="lua"
  elif command -v lua5.4 &> /dev/null; then
    LUA_BIN="lua5.4"
  elif [ -x "/tmp/lua-5.4.7/src/lua" ]; then
    LUA_BIN="/tmp/lua-5.4.7/src/lua"
  else
    echo "❌ Lua interpreter not found."
    echo "   Install Lua (e.g. 'apt install lua5.4' or build from source: https://www.lua.org/ftp/lua-5.4.7.tar.gz)"
    echo "   Or set LUA_INTERPRETER=/path/to/lua"
    exit 1
  fi
fi

# ─── Helper: Read Lua clusters from manifest ──────────────────────────────────

read_lua_clusters() {
  if [ ! -f "$MANIFEST" ]; then
    echo "❌ regrets/manifest.json not found"
    exit 1
  fi
  FILTER="$CLUSTER_FILTER" node -e "
    const m = JSON.parse(require('fs').readFileSync('$MANIFEST', 'utf8'));
    let clusters = m.clusters.filter(c => c.stack === 'lua');
    const filter = process.env.FILTER || '';
    if (filter) {
      clusters = clusters.filter(c => c.id === filter);
    }
    console.log(JSON.stringify(clusters));
  "
}

# ─── Main dispatch ────────────────────────────────────────────────────────────

case "$MODE" in
  capture)
    echo "📡 Capturing Lua clusters..."

    CLUSTERS_JSON=$(read_lua_clusters)

    if [ "$CLUSTERS_JSON" = "[]" ]; then
      echo "No Lua clusters found in manifest."
      exit 0
    fi

    echo "Found Lua clusters:"
    echo "$CLUSTERS_JSON" | node -e "
      const clusters = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));
      clusters.forEach(c => console.log('  - ' + c.id + ' (' + c.entry + ')'));
    "

    # Generate the Lua runner script that does the capture
    RUNNER="${REGRET_DIR}/regret_capture.lua"
    cat > "$RUNNER" << 'LUAEOF'
-- regret_capture.lua — auto-generated by capture_lua.sh
-- DO NOT EDIT — regenerated on each capture run.
-- This script is invoked with the manifest JSON + project dir as args.

local json_str = arg[1]
local project_dir = arg[2]
local regret_dir = arg[3]

-- ─── JSON parser (minimal, handles the manifest format) ─────────────────────
-- We need to parse the cluster list passed in from bash. This is a minimal
-- JSON decoder sufficient for the manifest format (no NaN, no nested functions).
local json

local function skip_whitespace(s, i)
  while i <= #s and (s:sub(i,i) == " " or s:sub(i,i) == "\t" or s:sub(i,i) == "\n" or s:sub(i,i) == "\r") do
    i = i + 1
  end
  return i
end

local function parse_value(s, i)
  i = skip_whitespace(s, i)
  local c = s:sub(i, i)
  if c == "{" then return json.parse_object(s, i)
  elseif c == "[" then return json.parse_array(s, i)
  elseif c == "\"" then return json.parse_string(s, i)
  elseif c == "t" or c == "f" then return json.parse_bool(s, i)
  elseif c == "n" then return json.parse_null(s, i)
  elseif c == "-" or c:match("[0-9]") then return json.parse_number(s, i)
  else
    error("JSON parse error at position " .. i .. ": unexpected '" .. c .. "'")
  end
end

json = {
  parse_string = function(s, i)
    assert(s:sub(i, i) == "\"", "expected '\"' at position " .. i)
    i = i + 1
    local result = {}
    while i <= #s do
      local c = s:sub(i, i)
      if c == "\"" then
        return table.concat(result), i + 1
      elseif c == "\\" then
        local next_c = s:sub(i+1, i+1)
        if next_c == "n" then result[#result+1] = "\n"
        elseif next_c == "t" then result[#result+1] = "\t"
        elseif next_c == "r" then result[#result+1] = "\r"
        elseif next_c == "\"" then result[#result+1] = "\""
        elseif next_c == "\\" then result[#result+1] = "\\"
        elseif next_c == "/" then result[#result+1] = "/"
        elseif next_c == "u" then
          -- Unicode escape — parse 4 hex digits
          local hex = s:sub(i+2, i+5)
          local code = tonumber(hex, 16)
          if code < 128 then
            result[#result+1] = string.char(code)
          else
            -- UTF-8 encode (basic)
            if code < 2048 then
              result[#result+1] = string.char(192 + math.floor(code/64), 128 + code%64)
            else
              result[#result+1] = string.char(224 + math.floor(code/4096), 128 + math.floor(code/64)%64, 128 + code%64)
            end
          end
          i = i + 6
        else
          result[#result+1] = next_c
          i = i + 2
        end
      else
        result[#result+1] = c
        i = i + 1
      end
    end
    error("unterminated string")
  end,

  parse_number = function(s, i)
    local start = i
    if s:sub(i, i) == "-" then i = i + 1 end
    while i <= #s and s:sub(i, i):match("[0-9.eE+-]") do
      i = i + 1
    end
    local num_str = s:sub(start, i - 1)
    local n = tonumber(num_str)
    if not n then error("invalid number: " .. num_str) end
    return n, i
  end,

  parse_bool = function(s, i)
    if s:sub(i, i+3) == "true" then return true, i + 4
    elseif s:sub(i, i+4) == "false" then return false, i + 5
    else error("invalid boolean at position " .. i) end
  end,

  parse_null = function(s, i)
    if s:sub(i, i+3) == "null" then return nil, i + 4
    else error("invalid null at position " .. i) end
  end,

  parse_array = function(s, i)
    assert(s:sub(i, i) == "[", "expected '[' at position " .. i)
    i = i + 1
    local arr = {}
    i = skip_whitespace(s, i)
    if s:sub(i, i) == "]" then return arr, i + 1 end
    while true do
      local val
      val, i = parse_value(s, i)
      arr[#arr + 1] = val
      i = skip_whitespace(s, i)
      local c = s:sub(i, i)
      if c == "]" then return arr, i + 1
      elseif c == "," then i = i + 1
      else error("expected ',' or ']' at position " .. i) end
    end
  end,

  parse_object = function(s, i)
    assert(s:sub(i, i) == "{", "expected '{' at position " .. i)
    i = i + 1
    local obj = {}
    i = skip_whitespace(s, i)
    if s:sub(i, i) == "}" then return obj, i + 1 end
    while true do
      i = skip_whitespace(s, i)
      local key
      key, i = json.parse_string(s, i)
      i = skip_whitespace(s, i)
      assert(s:sub(i, i) == ":", "expected ':' at position " .. i)
      i = i + 1
      local val
      val, i = parse_value(s, i)
      obj[key] = val
      i = skip_whitespace(s, i)
      local c = s:sub(i, i)
      if c == "}" then return obj, i + 1
      elseif c == "," then i = i + 1
      else error("expected ',' or '}' at position " .. i) end
    end
  end,
}

local function json_decode(s)
  s = s:gsub("^%s+", ""):gsub("%s+$", "")
  local result, i = parse_value(s, 1)
  return result
end

-- ─── JSON encoder (for writing INPUT/OUTPUT lines) ───────────────────────────

local function json_encode(val)
  if val == nil then return "null" end
  local t = type(val)
  if t == "string" then
    -- Escape special chars
    local escaped = val:gsub("\\", "\\\\"):gsub("\"", "\\\""):gsub("\n", "\\n"):gsub("\r", "\\r"):gsub("\t", "\\t")
    return "\"" .. escaped .. "\""
  elseif t == "number" then
    if val ~= val then return "\"__nan__\""  -- NaN sentinel (issue #322)
    elseif val == math.huge then return "\"__infinity__\""
    elseif val == -math.huge then return "\"__neg_infinity__\""
    elseif val == math.floor(val) and math.abs(val) < 1e15 then
      return tostring(math.floor(val))  -- integer
    else
      return tostring(val)
    end
  elseif t == "boolean" then
    return val and "true" or "false"
  elseif t == "table" then
    -- Detect array vs object: if all keys are sequential integers 1..n, it's an array
    local is_array = true
    local max_index = 0
    local key_count = 0
    for k, _ in pairs(val) do
      key_count = key_count + 1
      if type(k) == "number" and k == math.floor(k) and k >= 1 then
        if k > max_index then max_index = k end
      else
        is_array = false
      end
    end
    if is_array and key_count == max_index then
      local parts = {}
      for i = 1, max_index do
        parts[i] = json_encode(val[i])
      end
      return "[" .. table.concat(parts, ",") .. "]"
    else
      -- Object — sort keys for stable output
      local keys = {}
      for k, _ in pairs(val) do keys[#keys + 1] = tostring(k) end
      table.sort(keys)
      local parts = {}
      for _, k in ipairs(keys) do
        local v = val[k]
        parts[#parts + 1] = json_encode(k) .. ":" .. json_encode(v)
      end
      return "{" .. table.concat(parts, ",") .. "}"
    end
  elseif t == "function" then
    return "\"__function__\""
  else
    return "null"
  end
end

-- ─── stableStringify — must match JS stableStringify exactly ─────────────────
-- The fingerprint is sha256(stableStringify(input) + "|" + stableStringify(output))
-- so the stringified form MUST be byte-identical to JS for the same value.

local function stable_stringify(val)
  if val == nil then return "null" end
  local t = type(val)
  if t == "string" then
    -- JS JSON.stringify quotes strings — same escaping
    local escaped = val:gsub("\\", "\\\\"):gsub("\"", "\\\""):gsub("\n", "\\n"):gsub("\r", "\\r"):gsub("\t", "\\t")
    -- Also escape control chars < 0x20 (JS does this)
    local function escape_control(s)
      local result = {}
      for i = 1, #s do
        local byte = s:byte(i)
        if byte < 0x20 then
          result[#result+1] = string.format("\\u%04x", byte)
        else
          result[#result+1] = s:sub(i, i)
        end
      end
      return table.concat(result)
    end
    escaped = escape_control(escaped)
    return "\"" .. escaped .. "\""
  elseif t == "number" then
    if val ~= val then return "\"__nan__\""
    elseif val == math.huge then return "\"__infinity__\""
    elseif val == -math.huge then return "\"__neg_infinity__\""
    end
    -- JS Number.toString — for integers, no decimal point
    if val == math.floor(val) and math.abs(val) < 1e21 then
      return tostring(math.floor(val))
    else
      -- Lua tostring for floats uses %.14g format; JS uses a different algo
      -- For cross-stack parity we need to match JS. The safest approach is
      -- to use a format that matches JS for the common cases.
      -- JS: 3.14 → "3.14", 0.1 → "0.1", 1e21 → "1e+21"
      -- Lua: 3.14 → "3.14", 0.1 → "0.1"
      local s = tostring(val)
      -- Lua uses lowercase 'e' for exponents, JS uses lowercase too — OK
      -- But Lua 5.4 may print 3.14 as "3.14" while JS prints "3.14" — match
      return s
    end
  elseif t == "boolean" then
    return val and "true" or "false"
  elseif t == "table" then
    -- Detect array vs object
    local is_array = true
    local max_index = 0
    local key_count = 0
    for k, _ in pairs(val) do
      key_count = key_count + 1
      if type(k) == "number" and k == math.floor(k) and k >= 1 then
        if k > max_index then max_index = k end
      else
        is_array = false
      end
    end
    if is_array and key_count == max_index then
      local parts = {}
      for i = 1, max_index do
        parts[i] = stable_stringify(val[i])
      end
      return "[" .. table.concat(parts, ",") .. "]"
    else
      -- Object — sort keys (same as JS stableStringify)
      local keys = {}
      for k, _ in pairs(val) do keys[#keys + 1] = tostring(k) end
      table.sort(keys)
      local parts = {}
      for _, k in ipairs(keys) do
        local v = val[k]
        parts[#parts + 1] = stable_stringify(k) .. ":" .. stable_stringify(v)
      end
      return "{" .. table.concat(parts, ",") .. "}"
    end
  end
  return "null"
end

-- ─── SHA-256 implementation (pure Lua) ───────────────────────────────────────
-- Reference: FIPS 180-4. We need this because Lua stdlib has no SHA-256.
-- This is ~100 lines but runs fast enough for capture (called once per input).

local sha256 = (function()
  local band, bor, bxor, rrotate, rshift
  -- Lua 5.3+ has bitwise ops natively; Lua 5.4 has them too.
  -- We use the native ops (Lua 5.4 is our target).
  band = function(a, b) return a & b end
  bor = function(a, b) return a | b end
  bxor = function(a, b) return a ~ b end
  rrotate = function(a, n) return (a >> n) | (a << (32 - n)) end
  rshift = function(a, n) return a >> n end

  local H = {
    0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
    0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
  }
  local K = {
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5,
    0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
    0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc,
    0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
    0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
    0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3,
    0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5,
    0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
    0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
  }

  local function tobytes(s)
    -- Convert string to array of bytes
    local bytes = {}
    for i = 1, #s do
      bytes[i] = s:byte(i)
    end
    return bytes
  end

  local function hex_to_int(hex)
    return tonumber(hex, 16)
  end

  local function sha256_hex(s)
    -- Initialize hash values
    local h = {table.unpack(H)}

    -- Pre-processing: padding
    local bytes = tobytes(s)
    local bit_len = #bytes * 8
    bytes[#bytes + 1] = 0x80  -- append 1 bit
    while (#bytes % 64) ~= 56 do
      bytes[#bytes + 1] = 0
    end
    -- Append 64-bit big-endian length (we only handle < 2^32 bits)
    -- Append 64-bit big-endian length: high 32 bits (always 0 for our use
    -- case where messages are < 2^32 bits) then low 32 bits.
    for i = 1, 4 do
      bytes[#bytes + 1] = 0  -- high 32 bits of length
    end
    for i = 4, 1, -1 do
      bytes[#bytes + 1] = (bit_len >> (8 * (i - 1))) & 0xFF  -- low 32 bits
    end

    -- Process each 512-bit (64-byte) chunk
    for chunk_start = 1, #bytes, 64 do
      local w = {}
      -- Copy chunk into first 16 words (big-endian)
      for i = 0, 15 do
        local offset = chunk_start + i * 4
        w[i + 1] = (bytes[offset] << 24) | (bytes[offset + 1] << 16) | (bytes[offset + 2] << 8) | bytes[offset + 3]
        -- Mask to 32 bits
        w[i + 1] = w[i + 1] & 0xFFFFFFFF
      end
      -- Extend the first 16 words into the remaining 48 words
      for i = 17, 64 do
        local s0 = rrotate(w[i - 15], 7) ~ rrotate(w[i - 15], 18) ~ (w[i - 15] >> 3)
        local s1 = rrotate(w[i - 2], 17) ~ rrotate(w[i - 2], 19) ~ (w[i - 2] >> 10)
        w[i] = (w[i - 16] + s0 + w[i - 7] + s1) & 0xFFFFFFFF
      end

      -- Initialize working variables
      local a, b, c, d, e, f, g, hh = h[1], h[2], h[3], h[4], h[5], h[6], h[7], h[8]

      -- Compression function main loop
      for i = 1, 64 do
        local s1 = rrotate(e, 6) ~ rrotate(e, 11) ~ rrotate(e, 25)
        local ch = (e & f) ~ ((~e & 0xFFFFFFFF) & g)
        local temp1 = (hh + s1 + ch + K[i] + w[i]) & 0xFFFFFFFF
        local s0 = rrotate(a, 2) ~ rrotate(a, 13) ~ rrotate(a, 22)
        local maj = (a & b) ~ (a & c) ~ (b & c)
        local temp2 = (s0 + maj) & 0xFFFFFFFF

        hh = g
        g = f
        f = e
        e = (d + temp1) & 0xFFFFFFFF
        d = c
        c = b
        b = a
        a = (temp1 + temp2) & 0xFFFFFFFF
      end

      -- Add the compressed chunk to the current hash value
      h[1] = (h[1] + a) & 0xFFFFFFFF
      h[2] = (h[2] + b) & 0xFFFFFFFF
      h[3] = (h[3] + c) & 0xFFFFFFFF
      h[4] = (h[4] + d) & 0xFFFFFFFF
      h[5] = (h[5] + e) & 0xFFFFFFFF
      h[6] = (h[6] + f) & 0xFFFFFFFF
      h[7] = (h[7] + g) & 0xFFFFFFFF
      h[8] = (h[8] + hh) & 0xFFFFFFFF
    end

    -- Produce the final hash value (big-endian hex)
    local result = {}
    for i = 1, 8 do
      result[i] = string.format("%08x", h[i])
    end
    return table.concat(result)
  end

  return {
    sha256_hex = sha256_hex,
  }
end)()

-- ─── base36 conversion (must match JS: BigInt(hex, 16).toString(36).slice(0, 7)) ──
-- JS does: num = BigInt('0x' + hashHex); num.toString(36).slice(0, 7)
-- Lua 5.4 has 64-bit integers, so we can do this natively for hashes that
-- fit in 64 bits (sha256 is 256 bits — too big for one int).
-- We need big-integer arithmetic. Implement a minimal big-int via tables.

local bigint = {}

-- Parse a hex string into a big-int (array of 32-bit limbs, little-endian)
function bigint.from_hex(hex)
  local limbs = {}
  -- Process 8 hex chars (32 bits) at a time, from the end
  local i = #hex
  while i > 0 do
    local start = math.max(1, i - 7)
    local chunk = hex:sub(start, i)
    limbs[#limbs + 1] = tonumber(chunk, 16)
    i = start - 1
  end
  return limbs
end

-- Divide a big-int by a small integer (base 36), return quotient + remainder
function bigint.divmod_small(limbs, divisor)
  local quotient = {}
  local remainder = 0
  -- Process from most significant (end of array) to least
  for i = #limbs, 1, -1 do
    -- Use 64-bit arithmetic: combine remainder (from previous step) with current limb
    -- remainder is < divisor (< 36), current limb < 2^32
    -- combined value = remainder * 2^32 + limb (up to 36 * 2^32 + 2^32 — fits in 64 bits)
    local combined = remainder * 4294967296 + limbs[i]
    local q = combined // divisor
    remainder = combined % divisor
    quotient[i] = q
  end
  -- Strip leading zeros (from the most significant end)
  while #quotient > 1 and quotient[#quotient] == 0 do
    quotient[#quotient] = nil
  end
  return quotient, remainder
end

-- Convert big-int to base36 string
function bigint.to_base36(limbs)
  if #limbs == 1 and limbs[1] == 0 then return "0" end
  local digits = {}
  local work = limbs
  while not (#work == 1 and work[1] == 0) do
    local remainder
    work, remainder = bigint.divmod_small(work, 36)
    -- Convert digit to base36 char
    local ch
    if remainder < 10 then
      ch = string.char(48 + remainder)  -- '0' + remainder
    else
      ch = string.char(97 + remainder - 10)  -- 'a' + remainder - 10
    end
    digits[#digits + 1] = ch
  end
  -- Digits are little-endian (least significant first) — reverse
  for i = 1, #digits // 2 do
    digits[i], digits[#digits - i + 1] = digits[#digits - i + 1], digits[i]
  end
  return table.concat(digits)
end

-- ─── fingerprint function ────────────────────────────────────────────────────
-- Must match JS: sha256(stableStringify(input) + "|" + stableStringify(output))
-- → BigInt(hex, 16).toString(36).slice(0, 7)

local function fingerprint(input, output)
  local combined = stable_stringify(input) .. "|" .. stable_stringify(output)
  local hash_hex = sha256.sha256_hex(combined)
  local limbs = bigint.from_hex(hash_hex)
  local b36 = bigint.to_base36(limbs)
  if #b36 >= 7 then
    return b36:sub(1, 7)
  end
  return b36
end

-- ─── Convert a JSON-decoded value to the Lua type expected by the function ──
-- For most functions, the input from manifest is already the right Lua type
-- after JSON decode (strings → strings, numbers → numbers, arrays → tables).
-- This function is a no-op for the common case but could be extended for
-- type-coercion if needed.

local function coerce_input(val)
  return val  -- JSON decode already produces the right Lua types
end

-- ─── Invoke the entry function ───────────────────────────────────────────────
--   - If cluster.module is set: require(module) returns a table; look up entry on it
--   - Else: loadfile(file) and call it to get the module table, OR if the file
--     defines a global function, look it up in _G
--   - multiArgs: input must be an array; each element becomes one arg
--   - else: input is the sole arg (or nil if input is null)

local function invoke_entry(cluster, input)
  local fn
  if cluster.module then
    -- require() the module — package.path must include the project dir
    local ok, mod = pcall(require, cluster.module)
    if not ok then
      return nil, "require('" .. cluster.module .. "') failed: " .. tostring(mod)
    end
    fn = mod[cluster.entry]
    if type(fn) ~= "function" then
      return nil, "entry '" .. cluster.entry .. "' not found in module '" .. cluster.module .. "'"
    end
  elseif cluster.file then
    -- Load the file — it may define a global function or return a table
    local file_path = project_dir .. "/" .. cluster.file
    local chunk, err = loadfile(file_path)
    if not chunk then
      return nil, "loadfile('" .. file_path .. "') failed: " .. tostring(err)
    end
    -- Execute the chunk to define globals / get return value
    local ok, result = pcall(chunk)
    if not ok then
      return nil, "executing '" .. file_path .. "' failed: " .. tostring(result)
    end
    -- If the chunk returned a table, look up entry on it
    if type(result) == "table" and result[cluster.entry] then
      fn = result[cluster.entry]
    else
      -- Otherwise look up the global
      fn = _G[cluster.entry]
    end
    if type(fn) ~= "function" then
      return nil, "entry '" .. cluster.entry .. "' not found (neither in file return value nor _G)"
    end
  else
    return nil, "cluster has neither 'module' nor 'file' field"
  end

  -- Invoke the function
  local args
  if input == nil then
    args = {}
  elseif cluster.multiArgs and type(input) == "table" then
    args = input
  else
    args = {input}
  end
  local results = table.pack(pcall(fn, table.unpack(args)))
  local ok = results[1]
  if not ok then
    return nil, "function threw: " .. tostring(results[2])
  end
  -- Return first result (Lua functions can return multiple; we take the first)
  return results[2]
end

-- ─── Main: parse manifest, run capture for each cluster ──────────────────────

local clusters = json_decode(json_str)
if type(clusters) ~= "table" then
  error("manifest clusters field is not an array")
end

-- Add project_dir to package.path so require() can find modules
package.path = project_dir .. "/?.lua;" .. package.path .. ";" .. project_dir .. "/?/init.lua"

local success_count = 0
local fail_count = 0

for _, cluster in ipairs(clusters) do
  local id = cluster.id
  local entry = cluster.entry
  local inputs = cluster.inputs or {nil}

  print("  📡 Capturing: " .. id)
  print("     Entry: " .. entry)

  local results = {}
  local skipped = {}

  for i, input in ipairs(inputs) do
    local output, err = invoke_entry(cluster, input)
    if err then
      print("     ⚠️  input[" .. i .. "] threw: " .. err .. " — skipping")
      skipped[#skipped + 1] = {input = input, error = err}
    else
      local fp = fingerprint(input, output)
      results[#results + 1] = {input = input, output = output, fp = fp}
    end
  end

  if #results == 0 then
    print("     ❌ All " .. #inputs .. " input(s) threw — no golden captured")
    fail_count = fail_count + 1
    goto continue
  end

  -- Print skipped summary
  if #skipped > 0 then
    print("     ℹ️  Captured with " .. #results .. "/" .. #inputs .. " input(s) — " .. #skipped .. " skipped")
  end

  -- Write .regret file using the first successful result as the golden
  local golden = results[1]
  local regret_path = regret_dir .. "/" .. id .. ".regret"

  -- Get ISO8601 timestamp
  local timestamp = os.date("!%Y-%m-%dT%H:%M:%S") .. "." .. string.format("%06d", math.floor((os.clock() * 1000000) % 1000000)) .. "Z"

  local content = "cluster: " .. id .. "\n"
    .. "version: 1\n"
    .. "fingerprint: " .. golden.fp .. "\n"
    .. "captured: " .. timestamp .. "\n"
    .. "entry: " .. entry .. "\n"
    .. "stack: lua\n"
    .. "fingerprintLevel: entry\n"
    .. "---\n"
    .. "INPUT  " .. json_encode(golden.input) .. "\n"
    .. "OUTPUT " .. json_encode(golden.output) .. "\n"
    .. "HASH   " .. golden.fp .. "\n"

  local file = io.open(regret_path, "w")
  if not file then
    print("     ❌ Failed to write " .. regret_path)
    fail_count = fail_count + 1
    goto continue
  end
  file:write(content)
  file:close()

  print("     ✅ " .. id .. " captured: " .. golden.fp)
  print("     📄 " .. regret_path)
  success_count = success_count + 1

  ::continue::
end

print("")
print("──────────────────────────────────────────────────")
print("Capture complete: " .. success_count .. " captured, " .. fail_count .. " failed")
if fail_count == 0 then
  print("")
  print("Next: bash scripts/capture_lua.sh validate")
  print("If all green → you are clear to refactor.")
end
LUAEOF

    # Run the Lua runner
    "$LUA_BIN" "$RUNNER" "$CLUSTERS_JSON" "$PROJECT_DIR" "$REGRET_DIR"
    ;;

  validate)
    echo "🔍 Validating Lua clusters..."

    CLUSTERS_JSON=$(read_lua_clusters)

    if [ "$CLUSTERS_JSON" = "[]" ]; then
      echo "No Lua clusters found in manifest."
      exit 0
    fi

    # Generate the validate runner
    RUNNER="${REGRET_DIR}/regret_validate.lua"
    cat > "$RUNNER" << 'LUAEOF'
-- regret_validate.lua — auto-generated by capture_lua.sh
-- DO NOT EDIT — regenerated on each validate run.

local json_str = arg[1]
local project_dir = arg[2]
local regret_dir = arg[3]

-- ─── JSON parser (same as capture) ───────────────────────────────────────────
local json

local function skip_whitespace(s, i)
  while i <= #s and (s:sub(i,i) == " " or s:sub(i,i) == "\t" or s:sub(i,i) == "\n" or s:sub(i,i) == "\r") do
    i = i + 1
  end
  return i
end

local function parse_value(s, i)
  i = skip_whitespace(s, i)
  local c = s:sub(i, i)
  if c == "{" then return json.parse_object(s, i)
  elseif c == "[" then return json.parse_array(s, i)
  elseif c == "\"" then return json.parse_string(s, i)
  elseif c == "t" or c == "f" then return json.parse_bool(s, i)
  elseif c == "n" then return json.parse_null(s, i)
  elseif c == "-" or c:match("[0-9]") then return json.parse_number(s, i)
  else
    error("JSON parse error at position " .. i .. ": unexpected '" .. c .. "'")
  end
end

json = {
  parse_string = function(s, i)
    assert(s:sub(i, i) == "\"", "expected '\"' at position " .. i)
    i = i + 1
    local result = {}
    while i <= #s do
      local c = s:sub(i, i)
      if c == "\"" then
        return table.concat(result), i + 1
      elseif c == "\\" then
        local next_c = s:sub(i+1, i+1)
        if next_c == "n" then result[#result+1] = "\n"
        elseif next_c == "t" then result[#result+1] = "\t"
        elseif next_c == "r" then result[#result+1] = "\r"
        elseif next_c == "\"" then result[#result+1] = "\""
        elseif next_c == "\\" then result[#result+1] = "\\"
        elseif next_c == "/" then result[#result+1] = "/"
        elseif next_c == "u" then
          local hex = s:sub(i+2, i+5)
          local code = tonumber(hex, 16)
          if code < 128 then
            result[#result+1] = string.char(code)
          else
            if code < 2048 then
              result[#result+1] = string.char(192 + math.floor(code/64), 128 + code%64)
            else
              result[#result+1] = string.char(224 + math.floor(code/4096), 128 + math.floor(code/64)%64, 128 + code%64)
            end
          end
          i = i + 6
        else
          result[#result+1] = next_c
          i = i + 2
        end
      else
        result[#result+1] = c
        i = i + 1
      end
    end
    error("unterminated string")
  end,

  parse_number = function(s, i)
    local start = i
    if s:sub(i, i) == "-" then i = i + 1 end
    while i <= #s and s:sub(i, i):match("[0-9.eE+-]") do
      i = i + 1
    end
    local num_str = s:sub(start, i - 1)
    local n = tonumber(num_str)
    if not n then error("invalid number: " .. num_str) end
    return n, i
  end,

  parse_bool = function(s, i)
    if s:sub(i, i+3) == "true" then return true, i + 4
    elseif s:sub(i, i+4) == "false" then return false, i + 5
    else error("invalid boolean at position " .. i) end
  end,

  parse_null = function(s, i)
    if s:sub(i, i+3) == "null" then return nil, i + 4
    else error("invalid null at position " .. i) end
  end,

  parse_array = function(s, i)
    assert(s:sub(i, i) == "[", "expected '[' at position " .. i)
    i = i + 1
    local arr = {}
    i = skip_whitespace(s, i)
    if s:sub(i, i) == "]" then return arr, i + 1 end
    while true do
      local val
      val, i = parse_value(s, i)
      arr[#arr + 1] = val
      i = skip_whitespace(s, i)
      local c = s:sub(i, i)
      if c == "]" then return arr, i + 1
      elseif c == "," then i = i + 1
      else error("expected ',' or ']' at position " .. i) end
    end
  end,

  parse_object = function(s, i)
    assert(s:sub(i, i) == "{", "expected '{' at position " .. i)
    i = i + 1
    local obj = {}
    i = skip_whitespace(s, i)
    if s:sub(i, i) == "}" then return obj, i + 1 end
    while true do
      i = skip_whitespace(s, i)
      local key
      key, i = json.parse_string(s, i)
      i = skip_whitespace(s, i)
      assert(s:sub(i, i) == ":", "expected ':' at position " .. i)
      i = i + 1
      local val
      val, i = parse_value(s, i)
      obj[key] = val
      i = skip_whitespace(s, i)
      local c = s:sub(i, i)
      if c == "}" then return obj, i + 1
      elseif c == "," then i = i + 1
      else error("expected ',' or '}' at position " .. i) end
    end
  end,
}

local function json_decode(s)
  s = s:gsub("^%s+", ""):gsub("%s+$", "")
  local result, i = parse_value(s, 1)
  return result
end

-- ─── stableStringify (same as capture) ───────────────────────────────────────
local function stable_stringify(val)
  if val == nil then return "null" end
  local t = type(val)
  if t == "string" then
    local escaped = val:gsub("\\", "\\\\"):gsub("\"", "\\\""):gsub("\n", "\\n"):gsub("\r", "\\r"):gsub("\t", "\\t")
    local function escape_control(s)
      local result = {}
      for i = 1, #s do
        local byte = s:byte(i)
        if byte < 0x20 then
          result[#result+1] = string.format("\\u%04x", byte)
        else
          result[#result+1] = s:sub(i, i)
        end
      end
      return table.concat(result)
    end
    escaped = escape_control(escaped)
    return "\"" .. escaped .. "\""
  elseif t == "number" then
    if val ~= val then return "\"__nan__\""
    elseif val == math.huge then return "\"__infinity__\""
    elseif val == -math.huge then return "\"__neg_infinity__\""
    end
    if val == math.floor(val) and math.abs(val) < 1e21 then
      return tostring(math.floor(val))
    else
      return tostring(val)
    end
  elseif t == "boolean" then
    return val and "true" or "false"
  elseif t == "table" then
    local is_array = true
    local max_index = 0
    local key_count = 0
    for k, _ in pairs(val) do
      key_count = key_count + 1
      if type(k) == "number" and k == math.floor(k) and k >= 1 then
        if k > max_index then max_index = k end
      else
        is_array = false
      end
    end
    if is_array and key_count == max_index then
      local parts = {}
      for i = 1, max_index do
        parts[i] = stable_stringify(val[i])
      end
      return "[" .. table.concat(parts, ",") .. "]"
    else
      local keys = {}
      for k, _ in pairs(val) do keys[#keys + 1] = tostring(k) end
      table.sort(keys)
      local parts = {}
      for _, k in ipairs(keys) do
        local v = val[k]
        parts[#parts + 1] = stable_stringify(k) .. ":" .. stable_stringify(v)
      end
      return "{" .. table.concat(parts, ",") .. "}"
    end
  end
  return "null"
end

-- ─── SHA-256 (same as capture) ───────────────────────────────────────────────
local sha256 = (function()
  local band, bor, bxor, rrotate, rshift
  band = function(a, b) return a & b end
  bor = function(a, b) return a | b end
  bxor = function(a, b) return a ~ b end
  rrotate = function(a, n) return (a >> n) | (a << (32 - n)) end
  rshift = function(a, n) return a >> n end

  local H = {
    0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
    0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
  }
  local K = {
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5,
    0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
    0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc,
    0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
    0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
    0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3,
    0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5,
    0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
    0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
  }

  local function tobytes(s)
    local bytes = {}
    for i = 1, #s do
      bytes[i] = s:byte(i)
    end
    return bytes
  end

  local function sha256_hex(s)
    local h = {table.unpack(H)}
    local bytes = tobytes(s)
    local bit_len = #bytes * 8
    bytes[#bytes + 1] = 0x80
    while (#bytes % 64) ~= 56 do
      bytes[#bytes + 1] = 0
    end
    for i = 1, 4 do
      bytes[#bytes + 1] = 0  -- high 32 bits of length
    end
    for i = 4, 1, -1 do
      bytes[#bytes + 1] = (bit_len >> (8 * (i - 1))) & 0xFF  -- low 32 bits
    end

    for chunk_start = 1, #bytes, 64 do
      local w = {}
      for i = 0, 15 do
        local offset = chunk_start + i * 4
        w[i + 1] = (bytes[offset] << 24) | (bytes[offset + 1] << 16) | (bytes[offset + 2] << 8) | bytes[offset + 3]
        w[i + 1] = w[i + 1] & 0xFFFFFFFF
      end
      for i = 17, 64 do
        local s0 = rrotate(w[i - 15], 7) ~ rrotate(w[i - 15], 18) ~ (w[i - 15] >> 3)
        local s1 = rrotate(w[i - 2], 17) ~ rrotate(w[i - 2], 19) ~ (w[i - 2] >> 10)
        w[i] = (w[i - 16] + s0 + w[i - 7] + s1) & 0xFFFFFFFF
      end

      local a, b, c, d, e, f, g, hh = h[1], h[2], h[3], h[4], h[5], h[6], h[7], h[8]

      for i = 1, 64 do
        local s1 = rrotate(e, 6) ~ rrotate(e, 11) ~ rrotate(e, 25)
        local ch = (e & f) ~ ((~e & 0xFFFFFFFF) & g)
        local temp1 = (hh + s1 + ch + K[i] + w[i]) & 0xFFFFFFFF
        local s0 = rrotate(a, 2) ~ rrotate(a, 13) ~ rrotate(a, 22)
        local maj = (a & b) ~ (a & c) ~ (b & c)
        local temp2 = (s0 + maj) & 0xFFFFFFFF

        hh = g
        g = f
        f = e
        e = (d + temp1) & 0xFFFFFFFF
        d = c
        c = b
        b = a
        a = (temp1 + temp2) & 0xFFFFFFFF
      end

      h[1] = (h[1] + a) & 0xFFFFFFFF
      h[2] = (h[2] + b) & 0xFFFFFFFF
      h[3] = (h[3] + c) & 0xFFFFFFFF
      h[4] = (h[4] + d) & 0xFFFFFFFF
      h[5] = (h[5] + e) & 0xFFFFFFFF
      h[6] = (h[6] + f) & 0xFFFFFFFF
      h[7] = (h[7] + g) & 0xFFFFFFFF
      h[8] = (h[8] + hh) & 0xFFFFFFFF
    end

    local result = {}
    for i = 1, 8 do
      result[i] = string.format("%08x", h[i])
    end
    return table.concat(result)
  end

  return {
    sha256_hex = sha256_hex,
  }
end)()

-- ─── base36 (same as capture) ────────────────────────────────────────────────
local bigint = {}

function bigint.from_hex(hex)
  local limbs = {}
  local i = #hex
  while i > 0 do
    local start = math.max(1, i - 7)
    local chunk = hex:sub(start, i)
    limbs[#limbs + 1] = tonumber(chunk, 16)
    i = start - 1
  end
  return limbs
end

function bigint.divmod_small(limbs, divisor)
  local quotient = {}
  local remainder = 0
  for i = #limbs, 1, -1 do
    local combined = remainder * 4294967296 + limbs[i]
    local q = combined // divisor
    remainder = combined % divisor
    quotient[i] = q
  end
  while #quotient > 1 and quotient[#quotient] == 0 do
    quotient[#quotient] = nil
  end
  return quotient, remainder
end

function bigint.to_base36(limbs)
  if #limbs == 1 and limbs[1] == 0 then return "0" end
  local digits = {}
  local work = limbs
  while not (#work == 1 and work[1] == 0) do
    local remainder
    work, remainder = bigint.divmod_small(work, 36)
    local ch
    if remainder < 10 then
      ch = string.char(48 + remainder)
    else
      ch = string.char(97 + remainder - 10)
    end
    digits[#digits + 1] = ch
  end
  for i = 1, #digits // 2 do
    digits[i], digits[#digits - i + 1] = digits[#digits - i + 1], digits[i]
  end
  return table.concat(digits)
end

local function fingerprint(input, output)
  local combined = stable_stringify(input) .. "|" .. stable_stringify(output)
  local hash_hex = sha256.sha256_hex(combined)
  local limbs = bigint.from_hex(hash_hex)
  local b36 = bigint.to_base36(limbs)
  if #b36 >= 7 then
    return b36:sub(1, 7)
  end
  return b36
end

-- ─── Invoke entry (same as capture) ──────────────────────────────────────────
local function invoke_entry(cluster, input)
  local fn
  if cluster.module then
    local ok, mod = pcall(require, cluster.module)
    if not ok then
      return nil, "require('" .. cluster.module .. "') failed: " .. tostring(mod)
    end
    fn = mod[cluster.entry]
    if type(fn) ~= "function" then
      return nil, "entry '" .. cluster.entry .. "' not found in module '" .. cluster.module .. "'"
    end
  elseif cluster.file then
    local file_path = project_dir .. "/" .. cluster.file
    local chunk, err = loadfile(file_path)
    if not chunk then
      return nil, "loadfile('" .. file_path .. "') failed: " .. tostring(err)
    end
    local ok, result = pcall(chunk)
    if not ok then
      return nil, "executing '" .. file_path .. "' failed: " .. tostring(result)
    end
    if type(result) == "table" and result[cluster.entry] then
      fn = result[cluster.entry]
    else
      fn = _G[cluster.entry]
    end
    if type(fn) ~= "function" then
      return nil, "entry '" .. cluster.entry .. "' not found (neither in file return value nor _G)"
    end
  else
    return nil, "cluster has neither 'module' nor 'file' field"
  end

  local args
  if input == nil then
    args = {}
  elseif cluster.multiArgs and type(input) == "table" then
    args = input
  else
    args = {input}
  end
  local results = table.pack(pcall(fn, table.unpack(args)))
  local ok = results[1]
  if not ok then
    return nil, "function threw: " .. tostring(results[2])
  end
  return results[2]
end

-- ─── Parse .regret file ──────────────────────────────────────────────────────
local function parse_regret(content)
  local saved_input_json = nil
  local golden_hash = nil
  for line in content:gmatch("[^\n]+") do
    if line:sub(1, 7) == "INPUT  " then
      saved_input_json = line:sub(8)
    elseif line:sub(1, 7) == "HASH   " then
      golden_hash = line:sub(8)
    end
  end
  return saved_input_json, golden_hash
end

-- ─── Main: validate each cluster ─────────────────────────────────────────────
local clusters = json_decode(json_str)
if type(clusters) ~= "table" then
  error("manifest clusters field is not an array")
end

package.path = project_dir .. "/?.lua;" .. package.path .. ";" .. project_dir .. "/?/init.lua"

local failed = 0
local total = 0
local passed = 0

for _, cluster in ipairs(clusters) do
  local id = cluster.id
  total = total + 1

  local regret_path = regret_dir .. "/" .. id .. ".regret"
  local file = io.open(regret_path, "r")
  if not file then
    print("  ❌ " .. id .. ": .regret file missing: " .. regret_path)
    failed = failed + 1
    goto continue
  end
  local content = file:read("*a")
  file:close()

  local saved_input_json, golden_hash = parse_regret(content)
  if not golden_hash then
    print("  ❌ " .. id .. ": .regret file has no HASH line")
    failed = failed + 1
    goto continue
  end

  local saved_input = saved_input_json and json_decode(saved_input_json) or nil

  local live_output, invoke_err = invoke_entry(cluster, saved_input)
  if invoke_err then
    print("  ❌ " .. id .. ": invoke threw: " .. invoke_err .. " (golden was " .. golden_hash .. ")")
    failed = failed + 1
    goto continue
  end

  local live_hash = fingerprint(saved_input, live_output)
  if live_hash == golden_hash then
    print("  ✅ " .. id .. " " .. golden_hash .. " PASS")
    passed = passed + 1
  else
    print("  ❌ " .. id .. " " .. golden_hash .. " → " .. live_hash .. " FAIL")
    failed = failed + 1
  end

  ::continue::
end

print("────────────────────────────────────────────────────")
if failed == 0 then
  print("✅ All " .. total .. " Lua cluster(s) PASS")
else
  print("❌ " .. failed .. "/" .. total .. " Lua cluster(s) FAILED")
end

os.exit(failed > 0 and 1 or 0)
LUAEOF

    "$LUA_BIN" "$RUNNER" "$CLUSTERS_JSON" "$PROJECT_DIR" "$REGRET_DIR"
    ;;

  health)
    node "$SKILL_DIR/scripts/health.js"
    ;;

  *)
    echo "Usage: bash scripts/capture_lua.sh [capture|validate|health] [--cluster <id>]"
    echo ""
    echo "Default mode is 'capture' if no mode is specified."
    echo ""
    echo "Examples:"
    echo "  bash scripts/capture_lua.sh                    # capture all Lua clusters"
    echo "  bash scripts/capture_lua.sh validate           # validate all Lua clusters"
    echo "  bash scripts/capture_lua.sh --cluster my-fn    # capture single cluster"
    exit 1
    ;;
esac
