#!/usr/bin/env bash
# capture_go.sh — compile + run regret capture/validate for Go clusters
#
# Generates Go test files from manifest.json, runs `go test`, and writes
# .regret files (capture) or compares fingerprints (validate).
#
# Usage:
#   bash scripts/capture_go.sh                # capture all Go clusters
#   bash scripts/capture_go.sh capture        # capture (explicit)
#   bash scripts/capture_go.sh validate       # validate all Go clusters
#   bash scripts/capture_go.sh health         # health report (delegates to health.js)
#   bash scripts/capture_go.sh --cluster add  # single-cluster capture
#   bash scripts/capture_go.sh validate --cluster add
#
# .regret file format (identical to JS/Python stacks):
#   cluster: <id>
#   version: 1
#   fingerprint: <7char-base36>
#   captured: <ISO8601>
#   entry: <entry-fn-name>
#   stack: go
#   fingerprintLevel: entry
#   ---
#   INPUT  <json>
#   OUTPUT <json>
#   HASH   <7char-base36>
#   INPUTS <json-array-of-additional-results>  (if multi-input cluster)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_DIR="$(pwd)"
MANIFEST="${PROJECT_DIR}/regrets/manifest.json"
REGRET_DIR="${PROJECT_DIR}/regrets"

mkdir -p "$REGRET_DIR"

# Parse args. MODE is the first non-flag argument (defaults to "capture").
# --cluster <id> sets the cluster filter.
MODE="capture"
CLUSTER_FILTER=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --cluster)
      CLUSTER_FILTER="$2"
      shift 2
      ;;
    capture|validate|health)
      MODE="$1"
      shift
      ;;
    *)
      shift
      ;;
  esac
done

# ─── Helper: Emit the shared fingerprint + reflect helpers file ────────────────
# This file is written once per capture/validate run and shared by both the
# capture and validate test files. Keeping it separate avoids import-block
# conflicts.

generate_helpers_file() {
  local helpers_file="${REGRET_DIR}/regret_helpers_test.go"
  cat > "$helpers_file" << 'HELPERSEOF'
// regret_helpers_test.go — auto-generated by capture_go.sh
// DO NOT EDIT — shared fingerprint + reflect helpers for capture/validate tests.
package regrettest

import (
        "crypto/sha256"
        "encoding/json"
        "fmt"
        "math"
        "math/big"
        "os"
        "reflect"
        "sort"
        "strings"
        "time"
)

// stableStringify produces a deterministic JSON string with sorted keys.
// Must produce identical output to JS stableStringify() and Python stable_dumps().
//
// Edge cases that must match the JS implementation (issue #322):
//   - NaN → "__nan__" sentinel (JSON.stringify would emit "null")
//   - +Inf → "__infinity__"
//   - -Inf → "__neg_infinity__"
func stableStringify(obj interface{}) string {
        return doStableStringify(obj)
}

func doStableStringify(obj interface{}) string {
        if obj == nil {
                return "null"
        }
        switch v := obj.(type) {
        case bool:
                if v {
                        return "true"
                }
                return "false"
        case int:
                return fmt.Sprintf("%d", v)
        case int64:
                return fmt.Sprintf("%d", v)
        case float64:
                if math.IsNaN(v) {
                        return "\"__nan__\""
                }
                if math.IsInf(v, 1) {
                        return "\"__infinity__\""
                }
                if math.IsInf(v, -1) {
                        return "\"__neg_infinity__\""
                }
                return fmt.Sprintf("%g", v)
        case string:
                b, _ := json.Marshal(v)
                return string(b)
        case []interface{}:
                parts := make([]string, len(v))
                for i, item := range v {
                        parts[i] = doStableStringify(item)
                }
                return "[" + joinStrings(parts, ",") + "]"
        case map[string]interface{}:
                keys := make([]string, 0, len(v))
                for k := range v {
                        keys = append(keys, k)
                }
                sort.Strings(keys)
                parts := make([]string, len(keys))
                for i, k := range keys {
                        b, _ := json.Marshal(k)
                        parts[i] = string(b) + ":" + doStableStringify(v[k])
                }
                return "{" + joinStrings(parts, ",") + "}"
        default:
                b, _ := json.Marshal(v)
                return string(b)
        }
}

func joinStrings(ss []string, sep string) string {
        result := ""
        for i, s := range ss {
                if i > 0 {
                        result += sep
                }
                result += s
        }
        return result
}

// toBase36 converts a big.Int to base36 string (lowercase).
// Must produce identical output to JS BigInt.toString(36) and Python to_base36().
func toBase36(n *big.Int) string {
        if n.Sign() == 0 {
                return "0"
        }
        chars := "0123456789abcdefghijklmnopqrstuvwxyz"
        base := big.NewInt(36)
        zero := big.NewInt(0)
        result := ""
        remainder := new(big.Int)
        temp := new(big.Int).Set(n)
        if temp.Sign() < 0 {
                temp.Abs(temp)
        }
        for temp.Cmp(zero) > 0 {
                temp.DivMod(temp, base, remainder)
                result = string(chars[int(remainder.Int64())]) + result
        }
        return result
}

// fingerprint computes the 7-char base36 fingerprint.
// IDENTICAL algorithm to fingerprint.js / fingerprint.py:
//   sha256(stableStringify(input) + "|" + stableStringify(output)) → base36 → first 7 chars
func fingerprint(input interface{}, output interface{}) string {
        combined := stableStringify(input) + "|" + stableStringify(output)
        hash := sha256.Sum256([]byte(combined))
        hexStr := fmt.Sprintf("%x", hash)
        bigNum := new(big.Int)
        bigNum.SetString(hexStr, 16)
        b36 := toBase36(bigNum)
        if len(b36) >= 7 {
                return b36[:7]
        }
        return b36
}

// regretIO holds a single input/output/hash triple.
type regretIO struct {
        Input  interface{}
        Output interface{}
        Hash   string
}

// writeRegret builds and writes a .regret file for the given cluster.
// Format matches capture.js: cluster/version/fingerprint/captured/entry/
// stack/fingerprintLevel header, then --- separator, then
// INPUT/OUTPUT/HASH for the first result, then INPUTS for results[1+].
func writeRegret(id, entry string, results []regretIO) error {
        if len(results) == 0 {
                return fmt.Errorf("no results for cluster %s", id)
        }
        fp := results[0].Hash
        timestamp := time.Now().UTC().Format(time.RFC3339)
        var b strings.Builder
        b.WriteString("cluster: " + id + "\n")
        b.WriteString("version: 1\n")
        b.WriteString("fingerprint: " + fp + "\n")
        b.WriteString("captured: " + timestamp + "\n")
        b.WriteString("entry: " + entry + "\n")
        b.WriteString("stack: go\n")
        b.WriteString("fingerprintLevel: entry\n")
        b.WriteString("---\n")
        inBytes, _ := json.Marshal(results[0].Input)
        outBytes, _ := json.Marshal(results[0].Output)
        b.WriteString("INPUT  " + string(inBytes) + "\n")
        b.WriteString("OUTPUT " + string(outBytes) + "\n")
        b.WriteString("HASH   " + results[0].Hash + "\n")
        if len(results) > 1 {
                rest := make([]map[string]interface{}, 0, len(results)-1)
                for k := 1; k < len(results); k++ {
                        rest = append(rest, map[string]interface{}{
                                "input":  results[k].Input,
                                "output": results[k].Output,
                                "hash":   results[k].Hash,
                        })
                }
                restBytes, _ := json.Marshal(rest)
                b.WriteString("INPUTS " + string(restBytes) + "\n")
        }
        regretPath := id + ".regret"
        return os.WriteFile(regretPath, []byte(b.String()), 0644)
}

// adaptArg converts a JSON-parsed interface{} value to the target reflect.Type.
// Handles common conversions: float64→int, float64→int64, int→float64, etc.
// This bridges the gap between JSON's float64-only number type and Go's typed
// function parameters.
func adaptArg(v interface{}, target reflect.Type) (reflect.Value, error) {
        if v == nil {
                return reflect.Zero(target), nil
        }
        rv := reflect.ValueOf(v)
        if rv.Type() == target {
                return rv, nil
        }
        // float64 → int/int64 conversion (JSON decodes all numbers as float64)
        if rv.Kind() == reflect.Float64 && (target.Kind() == reflect.Int || target.Kind() == reflect.Int64 || target.Kind() == reflect.Int32 || target.Kind() == reflect.Int16 || target.Kind() == reflect.Int8) {
                return rv.Convert(target), nil
        }
        // int → float64
        if rv.Kind() == reflect.Int && target.Kind() == reflect.Float64 {
                return rv.Convert(target), nil
        }
        if rv.Type().ConvertibleTo(target) {
                return rv.Convert(target), nil
        }
        return reflect.Value{}, fmt.Errorf("cannot convert %v to %v", rv.Type(), target)
}

// invokeEntry invokes fn via reflection. If multiArgs is true, input must be an
// array; each element is converted to the corresponding parameter type via
// adaptArg. If input is nil, the function is called with zero args.
// Returns the result(s) as a single interface{} (or []interface{}
// for multi-return functions). If the last return is a non-nil error,
// it is returned as the Go error from this function.
func invokeEntry(fn reflect.Value, multiArgs bool, input interface{}) (interface{}, error) {
        fnType := fn.Type()
        var args []interface{}

        if input == nil {
                // Zero-arg call
                args = []interface{}{}
        } else if multiArgs {
                arr, ok := input.([]interface{})
                if !ok {
                        return nil, fmt.Errorf("multiArgs input is not an array (got %T)", input)
                }
                args = arr
        } else {
                args = []interface{}{input}
        }

        if fnType.NumIn() != len(args) {
                return nil, fmt.Errorf("entry expects %d args, got %d", fnType.NumIn(), len(args))
        }

        reflectArgs := make([]reflect.Value, len(args))
        for i, a := range args {
                av, err := adaptArg(a, fnType.In(i))
                if err != nil {
                        return nil, fmt.Errorf("arg %d: %w", i, err)
                }
                reflectArgs[i] = av
        }

        callResults := fn.Call(reflectArgs)
        if len(callResults) == 0 {
                return nil, nil
        }

        // Check if last return is a non-nil error
        lastResult := callResults[len(callResults)-1]
        if errVal, ok := lastResult.Interface().(error); ok && errVal != nil {
                return nil, errVal
        }

        if len(callResults) == 1 {
                return callResults[0].Interface(), nil
        }

        // Multiple return values — include all (including nil error as nil)
        arr := make([]interface{}, len(callResults))
        for k, r := range callResults {
                arr[k] = r.Interface()
        }
        return arr, nil
}

// parseRegret extracts INPUT, OUTPUT, HASH, and INPUTS fields from a .regret
// file's content. Returns the first input/output/hash plus the INPUTS array
// (for multi-input clusters, inputs[1+]).
func parseRegret(content string) (input interface{}, output interface{}, hash string, inputsList []map[string]interface{}, err error) {
        lines := strings.Split(content, "\n")
        var inputData, outputData, hashData, inputsData string
        for _, line := range lines {
                if strings.HasPrefix(line, "INPUTS ") && inputsData == "" {
                        inputsData = strings.TrimSpace(strings.TrimPrefix(line, "INPUTS"))
                } else if strings.HasPrefix(line, "INPUT ") && inputData == "" {
                        inputData = strings.TrimSpace(strings.TrimPrefix(line, "INPUT"))
                } else if strings.HasPrefix(line, "OUTPUT ") && outputData == "" {
                        outputData = strings.TrimSpace(strings.TrimPrefix(line, "OUTPUT"))
                } else if strings.HasPrefix(line, "HASH ") && hashData == "" {
                        hashData = strings.TrimSpace(strings.TrimPrefix(line, "HASH"))
                }
        }
        if inputData != "" {
                if e := json.Unmarshal([]byte(inputData), &input); e != nil {
                        err = fmt.Errorf("parse INPUT: %w", e)
                        return
                }
        }
        if outputData != "" {
                if e := json.Unmarshal([]byte(outputData), &output); e != nil {
                        err = fmt.Errorf("parse OUTPUT: %w", e)
                        return
                }
        }
        hash = hashData
        if inputsData != "" {
                if e := json.Unmarshal([]byte(inputsData), &inputsList); e != nil {
                        err = fmt.Errorf("parse INPUTS: %w", e)
                        return
                }
        }
        return
}
HELPERSEOF

  echo "$helpers_file"
}

# ─── Helper: Read Go clusters from manifest ───────────────────────────────────

read_go_clusters() {
  if [ ! -f "$MANIFEST" ]; then
    echo "❌ regrets/manifest.json not found"
    exit 1
  fi
  node -e "
    const m = JSON.parse(require('fs').readFileSync('$MANIFEST', 'utf8'));
    const clusters = m.clusters.filter(c => c.stack === 'go');
    if ('$CLUSTER_FILTER') {
      const id = '$CLUSTER_FILTER'.trim();
      const filtered = clusters.filter(c => c.id === id);
      console.log(JSON.stringify(filtered));
    } else {
      console.log(JSON.stringify(clusters));
    }
  "
}

# ─── Helper: Generate Go capture test file ────────────────────────────────────

generate_capture_test() {
  local clusters_json="$1"
  local test_file="${REGRET_DIR}/regret_capture_test.go"

  CLUSTERS_JSON="$clusters_json" node << 'NODESCRIPT' > "$test_file"
const clusters = JSON.parse(process.env.CLUSTERS_JSON);

// goLit: convert a JS value to a Go literal expression
function goLit(val) {
  if (val === null || val === undefined) return 'nil';
  if (typeof val === 'string') return JSON.stringify(val);
  if (typeof val === 'number') return String(val);
  if (typeof val === 'boolean') return String(val);
  if (Array.isArray(val)) {
    return '[]interface{}{' + val.map(goLit).join(', ') + '}';
  }
  if (typeof val === 'object') {
    const entries = Object.entries(val).map(([k, v]) => JSON.stringify(k) + ': ' + goLit(v));
    return 'map[string]interface{}{' + entries.join(', ') + '}';
  }
  return 'nil';
}

// Compute safe package alias (avoid conflicts with Go stdlib names)
const stdlib = new Set(['fmt', 'os', 'strings', 'math', 'sort', 'time', 'reflect', 'json', 'crypto', 'testing', 'big', 'sync', 'io', 'bytes', 'errors', 'context', 'strconv', 'regexp', 'path', 'filepath', 'runtime', 'unicode', 'utf8', 'bufio', 'net', 'http', 'url']);
const aliasMap = {};
for (const c of clusters) {
  if (!c.goPackage) continue;
  const base = c.goPackage.split('/').pop();
  if (stdlib.has(base)) {
    aliasMap[c.goPackage] = base + 'pkg';
  } else {
    aliasMap[c.goPackage] = base;
  }
}

const lines = [];

// Package declaration + imports
lines.push('// regret_capture_test.go — auto-generated by capture_go.sh');
lines.push('// DO NOT EDIT — this file is regenerated on each capture run.');
lines.push('package regrettest');
lines.push('');
lines.push('import (');

// Collect unique packages
const imports = new Set();
for (const c of clusters) {
  if (c.goPackage) {
    const alias = aliasMap[c.goPackage];
    imports.add(`        ${alias} "${c.goPackage}"`);
  }
}
for (const imp of imports) {
  lines.push(imp);
}
lines.push('        "reflect"');
lines.push('        "testing"');
lines.push(')');
lines.push('');

// Test function
lines.push('func TestRegretCapture(t *testing.T) {');

for (const cluster of clusters) {
  const { id, entry, goPackage, multiArgs, inputs } = cluster;
  const alias = goPackage ? aliasMap[goPackage] : '';
  const testInputs = inputs || [null];

  lines.push(`  t.Run("${id}", func(t *testing.T) {`);
  lines.push(`    var results []regretIO`);
  lines.push('');

  for (let i = 0; i < testInputs.length; i++) {
    const input = testInputs[i];
    lines.push(`    // Input ${i}`);
    lines.push(`    var in${i} interface{} = ${goLit(input)}`);

    // Call entry function via reflection with try/recover for partial capture
    lines.push(`    func() {`);
    lines.push(`      defer func() {`);
    lines.push(`        if r := recover(); r != nil {`);
    lines.push(`          t.Logf("⚠️  Input ${i} for ${id} threw: %v", r)`);
    lines.push(`        }`);
    lines.push(`      }()`);
    lines.push(`      out, err := invokeEntry(reflect.ValueOf(${alias}.${entry}), ${multiArgs ? 'true' : 'false'}, in${i})`);
    lines.push(`      if err != nil {`);
    lines.push(`        t.Logf("⚠️  Input ${i} for ${id} error: %v", err)`);
    lines.push(`        return`);
    lines.push(`      }`);
    lines.push(`      hash := fingerprint(in${i}, out)`);
    lines.push(`      results = append(results, regretIO{Input: in${i}, Output: out, Hash: hash})`);
    lines.push(`    }()`);
    lines.push('');
  }

  lines.push(`    if len(results) == 0 {`);
  lines.push(`      t.Errorf("❌ ${id}: all inputs threw/errored — no capture possible")`);
  lines.push(`      return`);
  lines.push(`    }`);
  lines.push(`    if err := writeRegret("${id}", "${entry}", results); err != nil {`);
  lines.push(`      t.Fatalf("write .regret for ${id}: %v", err)`);
  lines.push(`    }`);
  lines.push(`    t.Logf("✅ ${id} captured (hash: %s)", results[0].Hash)`);
  lines.push(`  })`);
  lines.push('');
}

lines.push('}');

console.log(lines.join('\n'));
NODESCRIPT

  echo "$test_file"
}

# ─── Helper: Generate Go validate test file ───────────────────────────────────

generate_validate_test() {
  local clusters_json="$1"
  local test_file="${REGRET_DIR}/regret_validate_test.go"

  CLUSTERS_JSON="$clusters_json" node << 'NODESCRIPT' > "$test_file"
const clusters = JSON.parse(process.env.CLUSTERS_JSON);

const stdlib = new Set(['fmt', 'os', 'strings', 'math', 'sort', 'time', 'reflect', 'json', 'crypto', 'testing', 'big', 'sync', 'io', 'bytes', 'errors', 'context', 'strconv', 'regexp', 'path', 'filepath', 'runtime', 'unicode', 'utf8', 'bufio', 'net', 'http', 'url']);
const aliasMap = {};
for (const c of clusters) {
  if (!c.goPackage) continue;
  const base = c.goPackage.split('/').pop();
  if (stdlib.has(base)) {
    aliasMap[c.goPackage] = base + 'pkg';
  } else {
    aliasMap[c.goPackage] = base;
  }
}

const lines = [];

lines.push('// regret_validate_test.go — auto-generated by capture_go.sh');
lines.push('// DO NOT EDIT — this file is regenerated on each validate run.');
lines.push('package regrettest');
lines.push('');
lines.push('import (');
const imports = new Set();
for (const c of clusters) {
  if (c.goPackage) {
    const alias = aliasMap[c.goPackage];
    imports.add(`        ${alias} "${c.goPackage}"`);
  }
}
for (const imp of imports) {
  lines.push(imp);
}
lines.push('        "os"');
lines.push('        "reflect"');
lines.push('        "testing"');
lines.push(')');
lines.push('');

lines.push('func TestRegretValidate(t *testing.T) {');

for (const cluster of clusters) {
  const { id, entry, goPackage, multiArgs } = cluster;
  const alias = goPackage ? aliasMap[goPackage] : '';

  lines.push(`  t.Run("${id}", func(t *testing.T) {`);
  lines.push(`    regretPath := "${id}.regret"`);
  lines.push(`    data, err := os.ReadFile(regretPath)`);
  lines.push(`    if err != nil {`);
  lines.push(`      t.Fatalf("read .regret for ${id}: %v", err)`);
  lines.push(`    }`);
  lines.push(`    gInput, _, gHash, gInputsList, err := parseRegret(string(data))`);
  lines.push(`    if err != nil {`);
  lines.push(`      t.Fatalf("parse .regret for ${id}: %v", err)`);
  lines.push(`    }`);
  lines.push('');
  lines.push(`    // Validate the primary input`);
  lines.push(`    out, err := invokeEntry(reflect.ValueOf(${alias}.${entry}), ${multiArgs ? 'true' : 'false'}, gInput)`);
  lines.push(`    if err != nil {`);
  lines.push(`      t.Fatalf("invoke ${entry}: %v", err)`);
  lines.push(`    }`);
  lines.push(`    newHash := fingerprint(gInput, out)`);
  lines.push(`    if newHash != gHash {`);
  lines.push(`      t.Errorf("❌ ${id} FAIL — expected %s got %s", gHash, newHash)`);
  lines.push(`    } else {`);
  lines.push(`      t.Logf("✅ ${id} %s PASS", newHash)`);
  lines.push(`    }`);
  lines.push('');
  lines.push(`    // Validate INPUTS[1+] if present`);
  lines.push(`    for i, item := range gInputsList {`);
  lines.push(`      inVal := item["input"]`);
  lines.push(`      expectedHash := item["hash"].(string)`);
  lines.push(`      outN, err := invokeEntry(reflect.ValueOf(${alias}.${entry}), ${multiArgs ? 'true' : 'false'}, inVal)`);
  lines.push(`      if err != nil {`);
  lines.push(`        t.Errorf("❌ ${id} INPUTS[%d] invoke error: %v", i, err)`);
  lines.push(`        continue`);
  lines.push(`      }`);
  lines.push(`      gotHash := fingerprint(inVal, outN)`);
  lines.push(`      if gotHash != expectedHash {`);
  lines.push(`        t.Errorf("❌ ${id} INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)`);
  lines.push(`      } else {`);
  lines.push(`        t.Logf("✅ ${id} INPUTS[%d] %s PASS", i, gotHash)`);
  lines.push(`      }`);
  lines.push(`    }`);
  lines.push(`  })`);
  lines.push('');
}

lines.push('}');

console.log(lines.join('\n'));
NODESCRIPT

  echo "$test_file"
}

# ─── Main dispatch ────────────────────────────────────────────────────────────

case "$MODE" in
  capture)
    echo "📡 Capturing Go clusters..."

    # Check if go is available
    if ! command -v go &> /dev/null; then
      echo "⚠️  Go is not installed. Install Go to use the Go stack."
      echo "   See references/go.md for the Go capture protocol."
      exit 0
    fi

    # Read clusters from manifest
    CLUSTERS_JSON=$(read_go_clusters)

    if [ "$CLUSTERS_JSON" = "[]" ]; then
      echo "No Go clusters found in manifest."
      exit 0
    fi

    echo "Found Go clusters:"
    echo "$CLUSTERS_JSON" | node -e "
      const clusters = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));
      clusters.forEach(c => console.log('  - ' + c.id + ' (' + c.entry + ')'));
    "

    # Generate helpers + capture test files
    HELPERS_FILE=$(generate_helpers_file)
    echo "📄 Generated: $HELPERS_FILE"
    TEST_FILE=$(generate_capture_test "$CLUSTERS_JSON")
    echo "📄 Generated: $TEST_FILE"

    # Build first to ensure modules are available
    echo "🔧 Building Go modules..."
    go build ./... 2>/dev/null || true

    # Run capture test
    echo "🧪 Running regret capture..."
    go test -v -run TestRegretCapture ./regrets/ 2>&1 || {
      echo "⚠️  Go test execution failed."
      echo "   Check that your Go module is set up correctly."
      exit 1
    }
    ;;

  validate)
    echo "🔍 Validating Go clusters..."

    if ! command -v go &> /dev/null; then
      echo "⚠️  Go is not installed. Cannot validate Go clusters."
      exit 0
    fi

    CLUSTERS_JSON=$(read_go_clusters)

    if [ "$CLUSTERS_JSON" = "[]" ]; then
      echo "No Go clusters found in manifest."
      exit 0
    fi

    # Generate helpers + validate test files
    HELPERS_FILE=$(generate_helpers_file)
    echo "📄 Generated: $HELPERS_FILE"
    TEST_FILE=$(generate_validate_test "$CLUSTERS_JSON")
    echo "📄 Generated: $TEST_FILE"

    # Run validate test
    echo "🧪 Running regret validation..."
    go test -v -run TestRegretValidate ./regrets/ 2>&1 || {
      echo "❌ Validation FAILED — at least one cluster has a fingerprint mismatch."
      exit 1
    }
    ;;

  health)
    node "$SKILL_DIR/scripts/health.js"
    ;;

  *)
    echo "Usage: bash scripts/capture_go.sh [capture|validate|health] [--cluster <id>]"
    exit 1
    ;;
esac
