#!/usr/bin/env bash
# capture_go.sh — compile + run regret capture/validate for Go clusters
#
# Generates Go test files from manifest.json, runs `go test`, and writes
# .regret files (capture) or compares fingerprints (validate).
#
# Usage:
#   bash scripts/capture_go.sh                # capture all Go clusters
#   bash scripts/capture_go.sh capture        # capture (explicit)
#   bash scripts/capture_go.sh validate       # validate all Go clusters
#   bash scripts/capture_go.sh health         # health report (delegates to health.js)
#   bash scripts/capture_go.sh --cluster to-valid-bf   # single-cluster capture
#
# .regret file format (identical to JS/Python stacks):
#   cluster: <id>
#   version: 1
#   fingerprint: <7char-base36>
#   captured: <ISO8601>
#   entry: <entry-fn-name>
#   stack: go
#   fingerprintLevel: entry
#   ---
#   INPUT  <json>
#   OUTPUT <json>
#   HASH   <7char-base36>

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_DIR="$(pwd)"
MANIFEST="${PROJECT_DIR}/regrets/manifest.json"
REGRET_DIR="${PROJECT_DIR}/regrets"

mkdir -p "$REGRET_DIR"

# Parse args. MODE is the first non-flag argument (defaults to "capture").
# --cluster <id> sets the cluster filter (works with or without explicit MODE).
MODE="capture"
CLUSTER_FILTER=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --cluster)
      CLUSTER_FILTER="$2"
      shift 2
      ;;
    capture|validate|health)
      MODE="$1"
      shift
      ;;
    *)
      # Unknown arg — skip (could be a stale arg from older usage)
      shift
      ;;
  esac
done

# ─── Helper: emit the shared fingerprint + reflect helpers file ────────────────
# This file is written once per capture/validate run and shared by both the
# capture and validate test files. Keeping it separate avoids import-block
# conflicts (the fingerprint code has its own imports that would otherwise
# collide with the test file's imports).

generate_helpers_file() {
  local helpers_file="${REGRET_DIR}/regret_helpers_test.go"
  cat > "$helpers_file" << 'HELPERSEOF'
// regret_helpers_test.go — auto-generated by capture_go.sh
// DO NOT EDIT — shared fingerprint + reflect helpers for capture/validate tests.
package regrettest

import (
        "crypto/sha256"
        "encoding/json"
        "fmt"
        "math"
        "math/big"
        "reflect"
        "sort"
)

// stableStringify produces a deterministic JSON string with sorted keys.
// Must produce identical output to JS stableStringify() and Python stable_dumps().
//
// Edge cases that must match the JS implementation (issue #322):
//   - NaN → "__nan__" sentinel (JSON.stringify would emit "null")
//   - +Inf → "__infinity__"
//   - -Inf → "__neg_infinity__"
func stableStringify(obj interface{}) string {
        return doStableStringify(obj)
}

func doStableStringify(obj interface{}) string {
        if obj == nil {
                return "null"
        }
        switch v := obj.(type) {
        case bool:
                if v {
                        return "true"
                }
                return "false"
        case int:
                return fmt.Sprintf("%d", v)
        case int64:
                return fmt.Sprintf("%d", v)
        case float64:
                if v != v { // NaN
                        return "\"__nan__\""
                }
                if math.IsInf(v, 1) { // +Inf
                        return "\"__infinity__\""
                }
                if math.IsInf(v, -1) { // -Inf
                        return "\"__neg_infinity__\""
                }
                return fmt.Sprintf("%g", v)
        case string:
                b, _ := json.Marshal(v)
                return string(b)
        case []interface{}:
                parts := make([]string, len(v))
                for i, item := range v {
                        parts[i] = doStableStringify(item)
                }
                return "[" + joinStrings(parts, ",") + "]"
        case map[string]interface{}:
                keys := make([]string, 0, len(v))
                for k := range v {
                        keys = append(keys, k)
                }
                sort.Strings(keys)
                parts := make([]string, len(keys))
                for i, k := range keys {
                        b, _ := json.Marshal(k)
                        parts[i] = string(b) + ":" + doStableStringify(v[k])
                }
                return "{" + joinStrings(parts, ",") + "}"
        default:
                b, _ := json.Marshal(v)
                return string(b)
        }
}

func joinStrings(ss []string, sep string) string {
        result := ""
        for i, s := range ss {
                if i > 0 {
                        result += sep
                }
                result += s
        }
        return result
}

// fingerprint computes the 7-char base36 hash.
// Must match JS fingerprint(): sha256(stableStringify(input) + "|" + stableStringify(output)) → base36 → first 7 chars
func fingerprint(input interface{}, output interface{}) string {
        combined := stableStringify(input) + "|" + stableStringify(output)
        hash := sha256.Sum256([]byte(combined))
        hexStr := fmt.Sprintf("%x", hash)
        bigNum := new(big.Int)
        bigNum.SetString(hexStr, 16)
        b36 := toBase36(bigNum)
        if len(b36) >= 7 {
                return b36[:7]
        }
        return b36
}

func toBase36(n *big.Int) string {
        if n.Sign() == 0 {
                return "0"
        }
        abs := new(big.Int).Set(n)
        if abs.Sign() < 0 {
                abs.Abs(abs)
        }
        base := big.NewInt(36)
        digits := ""
        for abs.Sign() > 0 {
                mod := new(big.Int)
                abs.DivMod(abs, base, mod)
                digits = string(base36Digit(mod.Int64())) + digits
        }
        return digits
}

func base36Digit(d int64) byte {
        if d < 10 {
                return byte('0' + d)
        }
        return byte('a' + d - 10)
}

// invokeEntry calls a Go function via reflection.
//   - input == nil → zero-arg call
//   - multiArgs=true → input must be []interface{}, each element becomes one arg
//   - multiArgs=false → input is the sole arg
// Returns the first result. If the last result is a non-nil error, returns it.
func invokeEntry(fn reflect.Value, input interface{}, multiArgs bool) (interface{}, error) {
        var args []reflect.Value
        if input == nil {
                // zero-arg call
        } else if multiArgs {
                arr, ok := input.([]interface{})
                if !ok {
                        return nil, fmt.Errorf("multiArgs=true but input is not array: %T", input)
                }
                fnType := fn.Type()
                if len(arr) != fnType.NumIn() {
                        return nil, fmt.Errorf("multiArgs: input has %d elements but function takes %d args", len(arr), fnType.NumIn())
                }
                for i, a := range arr {
                        conv, err := convertArg(a, fnType.In(i))
                        if err != nil {
                                return nil, err
                        }
                        args = append(args, conv)
                }
        } else {
                fnType := fn.Type()
                if fnType.NumIn() > 0 {
                        conv, err := convertArg(input, fnType.In(0))
                        if err != nil {
                                return nil, err
                        }
                        args = append(args, conv)
                }
        }
        results := fn.Call(args)
        if len(results) == 0 {
                return nil, nil
        }
        last := results[len(results)-1]
        if err, ok := last.Interface().(error); ok && err != nil {
                return nil, err
        }
        return results[0].Interface(), nil
}

// convertArg converts a JSON-decoded interface{} value to the expected Go type.
// JSON numbers come back as float64; we convert to int/int64/float64 as needed.
func convertArg(val interface{}, expected reflect.Type) (reflect.Value, error) {
        if val == nil {
                return reflect.Zero(expected), nil
        }
        valType := reflect.TypeOf(val)
        if valType == expected {
                return reflect.ValueOf(val), nil
        }
        switch expected.Kind() {
        case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
                if f, ok := val.(float64); ok {
                        return reflect.ValueOf(f).Convert(expected), nil
                }
        case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
                if f, ok := val.(float64); ok {
                        return reflect.ValueOf(f).Convert(expected), nil
                }
        case reflect.Float32, reflect.Float64:
                if f, ok := val.(float64); ok {
                        return reflect.ValueOf(f).Convert(expected), nil
                }
        case reflect.String:
                if s, ok := val.(string); ok {
                        return reflect.ValueOf(s), nil
                }
        case reflect.Bool:
                if b, ok := val.(bool); ok {
                        return reflect.ValueOf(b), nil
                }
        case reflect.Slice:
                if arr, ok := val.([]interface{}); ok {
                        slice := reflect.MakeSlice(expected, 0, len(arr))
                        for _, item := range arr {
                                conv, err := convertArg(item, expected.Elem())
                                if err != nil {
                                        return reflect.Value{}, err
                                }
                                slice = reflect.Append(slice, conv)
                        }
                        return slice, nil
                }
        }
        if valType.ConvertibleTo(expected) {
                return reflect.ValueOf(val).Convert(expected), nil
        }
        return reflect.Value{}, fmt.Errorf("cannot convert %T to %v", val, expected)
}

// parseRegretFile extracts the INPUT and HASH lines from a .regret file.
// Returns (inputJSON, goldenHash, error).
func parseRegretFile(content string) (string, string, error) {
        var savedInputJSON, goldenHash string
        for _, line := range splitLines(content) {
                trimmed := line
                if hasPrefix(trimmed, "INPUT  ") {
                        savedInputJSON = trimmed[7:]
                } else if hasPrefix(trimmed, "HASH   ") {
                        goldenHash = trimmed[7:]
                }
        }
        if goldenHash == "" {
                return "", "", fmt.Errorf(".regret file has no HASH line")
        }
        return savedInputJSON, goldenHash, nil
}

func splitLines(s string) []string {
        var lines []string
        current := ""
        for _, ch := range s {
                if ch == '\n' {
                        lines = append(lines, current)
                        current = ""
                } else {
                        current += string(ch)
                }
        }
        if current != "" {
                lines = append(lines, current)
        }
        return lines
}

func hasPrefix(s, prefix string) bool {
        if len(s) < len(prefix) {
                return false
        }
        return s[:len(prefix)] == prefix
}
HELPERSEOF
  echo "$helpers_file"
}

# ─── Helper: Read Go clusters from manifest ───────────────────────────────────

read_go_clusters() {
  if [ ! -f "$MANIFEST" ]; then
    echo "❌ regrets/manifest.json not found"
    exit 1
  fi
  FILTER="$CLUSTER_FILTER" node -e "
    const m = JSON.parse(require('fs').readFileSync('$MANIFEST', 'utf8'));
    let clusters = m.clusters.filter(c => c.stack === 'go');
    const filter = process.env.FILTER || '';
    if (filter) {
      clusters = clusters.filter(c => c.id === filter);
    }
    console.log(JSON.stringify(clusters));
  "
}

# ─── Helper: compute unique package imports + alias map ──────────────────────
# Outputs Go import lines (one per line) and writes the alias map to a temp
# file for the test generator to read.
emit_imports_and_alias_map() {
  local clusters_json="$1"
  echo "$clusters_json" | node -e "
    const clusters = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));
    const aliasMap = {};
    const uniquePkgs = [];
    for (const cluster of clusters) {
      const pkg = cluster.goPackage || 'main';
      if (!aliasMap[pkg]) {
        let alias = pkg.split('/').pop().replace(/[^a-zA-Z0-9_]/g, '_');
        if (!alias || /^[0-9]/.test(alias)) alias = 'pkg_' + alias;
        // Go reserves 'main' as a package name — use a different alias
        if (alias === 'main') alias = 'mainpkg';
        aliasMap[pkg] = alias;
        uniquePkgs.push({ pkg, alias });
      }
    }
    // Emit import lines
    for (const { pkg, alias } of uniquePkgs) {
      console.log('  ' + alias + ' \"' + pkg + '\"');
    }
    // Write alias map to stderr for the caller to capture (single JSON line)
    process.stderr.write(JSON.stringify(aliasMap));
  "
}

# ─── Helper: Generate capture test file ───────────────────────────────────────

generate_capture_test() {
  local clusters_json="$1"
  local test_file="${REGRET_DIR}/regret_capture_test.go"

  # Build the alias map first
  local alias_map_json
  alias_map_json=$(echo "$clusters_json" | node -e "
    const clusters = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));
    const aliasMap = {};
    for (const cluster of clusters) {
      const pkg = cluster.goPackage || 'main';
      if (!aliasMap[pkg]) {
        let alias = pkg.split('/').pop().replace(/[^a-zA-Z0-9_]/g, '_');
        if (!alias || /^[0-9]/.test(alias)) alias = 'pkg_' + alias;
        if (alias === 'main') alias = 'mainpkg';
        aliasMap[pkg] = alias;
      }
    }
    console.log(JSON.stringify(aliasMap));
  ")

  {
    cat << 'TESTHEADER'
// regret_capture_test.go — auto-generated by capture_go.sh
// DO NOT EDIT — this file is regenerated on each capture run.
package regrettest

import (
        "encoding/json"
        "fmt"
        "os"
        "path/filepath"
        "reflect"
        "testing"
        "time"
TESTHEADER

    # Emit target package imports (inside the same import block)
    echo "$clusters_json" | node -e "
      const clusters = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));
      const seen = new Set();
      const lines = [];
      for (const cluster of clusters) {
        const pkg = cluster.goPackage || 'main';
        if (seen.has(pkg)) continue;
        seen.add(pkg);
        let alias = pkg.split('/').pop().replace(/[^a-zA-Z0-9_]/g, '_');
        if (!alias || /^[0-9]/.test(alias)) alias = 'pkg_' + alias;
        if (alias === 'main') alias = 'mainpkg';
        lines.push('  ' + alias + ' \"' + pkg + '\"');
      }
      console.log(lines.join('\n'));
    "
    echo ")"

    # Emit the test function
    echo ""
    echo "func TestRegretCapture(t *testing.T) {"
    echo "  regretDir := \"${PROJECT_DIR}/regrets\""
    echo "  _ = regretDir"
    echo ""

    echo "$clusters_json" | ALIAS_MAP="$alias_map_json" node -e "
      const clusters = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));
      const aliasMap = JSON.parse(process.env.ALIAS_MAP || '{}');

      for (const cluster of clusters) {
        const { id, entry, goPackage, inputs, multiArgs } = cluster;
        const pkg = goPackage || 'main';
        const alias = aliasMap[pkg];
        const testInputs = (inputs && inputs.length > 0) ? inputs : [null];

        console.log('  // Cluster: ' + id);
        console.log('  t.Run(\"' + id + '\", func(t *testing.T) {');

        // Resolve the entry function via reflection
        console.log('    entryFn := reflect.ValueOf(' + alias + '.' + entry + ')');
        console.log('    if entryFn.Kind() != reflect.Func {');
        console.log('      t.Fatalf(\"entry ' + entry + ' is not a function in package ' + pkg + '\")');
        console.log('    }');
        console.log('');

        console.log('    type inputOutput struct {');
        console.log('      Input  interface{}');
        console.log('      Output interface{}');
        console.log('      Hash   string');
        console.log('    }');
        console.log('    var results []inputOutput');
        console.log('');

        for (let i = 0; i < testInputs.length; i++) {
          const input = testInputs[i];
          const inputJSON = JSON.stringify(input);
          console.log('    // Input ' + i + ': ' + inputJSON);
          // Emit the input as a JSON string literal, then unmarshal at runtime
          // This preserves exact JSON types (number vs string, etc.)
          console.log('    input' + i + 'Bytes := []byte(' + JSON.stringify(inputJSON) + ')');
          console.log('    var input' + i + 'Val interface{}');
          console.log('    if err := json.Unmarshal(input' + i + 'Bytes, &input' + i + 'Val); err != nil {');
          console.log('      t.Fatalf(\"input ' + i + ' unmarshal failed: %v\", err)');
          console.log('    }');
          console.log('    output' + i + ', err' + i + ' := invokeEntry(entryFn, input' + i + 'Val, ' + (multiArgs ? 'true' : 'false') + ')');
          console.log('    if err' + i + ' != nil {');
          console.log('      t.Logf(\"  input ' + i + ' threw: %v — skipping\", err' + i + ')');
          console.log('    } else {');
          console.log('      fp' + i + ' := fingerprint(input' + i + 'Val, output' + i + ')');
          console.log('      results = append(results, inputOutput{Input: input' + i + 'Val, Output: output' + i + ', Hash: fp' + i + '})');
          console.log('    }');
        }

        console.log('');
        console.log('    if len(results) == 0 {');
        console.log('      t.Fatalf(\"cluster ' + id + ': all ' + testInputs.length + ' input(s) threw — no golden captured\")');
        console.log('    }');
        console.log('');

        // Write .regret file using the first successful result as the golden
        console.log('    golden := results[0]');
        console.log('    regretPath := filepath.Join(regretDir, \"' + id + '.regret\")');
        console.log('    inputJSONBytes, _ := json.Marshal(golden.Input)');
        console.log('    outputJSONBytes, _ := json.Marshal(golden.Output)');
        console.log('    timestamp := time.Now().UTC().Format(time.RFC3339Nano)');
        console.log('    content := \"cluster: ' + id + '\\\\n\" +');
        console.log('      \"version: 1\\\\n\" +');
        console.log('      \"fingerprint: \" + golden.Hash + \"\\\\n\" +');
        console.log('      \"captured: \" + timestamp + \"\\\\n\" +');
        console.log('      \"entry: ' + entry + '\\\\n\" +');
        console.log('      \"stack: go\\\\n\" +');
        console.log('      \"fingerprintLevel: entry\\\\n\" +');
        console.log('      \"---\\\\n\" +');
        console.log('      \"INPUT  \" + string(inputJSONBytes) + \"\\\\n\" +');
        console.log('      \"OUTPUT \" + string(outputJSONBytes) + \"\\\\n\" +');
        console.log('      \"HASH   \" + golden.Hash + \"\\\\n\"');
        console.log('    if err := os.WriteFile(regretPath, []byte(content), 0644); err != nil {');
        console.log('      t.Fatalf(\"write .regret failed: %v\", err)');
        console.log('    }');
        console.log('    t.Logf(\"✅ ' + id + ' captured: %s\", golden.Hash)');
        console.log('    t.Logf(\"📄 %s\", regretPath)');
        console.log('  })');
        console.log('');
      }

      console.log('  _ = fmt.Sprintf'); // suppress unused import if no clusters
      console.log('}');
    "
  } > "$test_file"

  echo "$test_file"
}

# ─── Helper: Generate validate test file ──────────────────────────────────────

generate_validate_test() {
  local clusters_json="$1"
  local test_file="${REGRET_DIR}/regret_validate_test.go"

  local alias_map_json
  alias_map_json=$(echo "$clusters_json" | node -e "
    const clusters = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));
    const aliasMap = {};
    for (const cluster of clusters) {
      const pkg = cluster.goPackage || 'main';
      if (!aliasMap[pkg]) {
        let alias = pkg.split('/').pop().replace(/[^a-zA-Z0-9_]/g, '_');
        if (!alias || /^[0-9]/.test(alias)) alias = 'pkg_' + alias;
        if (alias === 'main') alias = 'mainpkg';
        aliasMap[pkg] = alias;
      }
    }
    console.log(JSON.stringify(aliasMap));
  ")

  {
    cat << 'TESTHEADER'
// regret_validate_test.go — auto-generated by capture_go.sh
// DO NOT EDIT — this file is regenerated on each validate run.
package regrettest

import (
        "encoding/json"
        "fmt"
        "os"
        "path/filepath"
        "reflect"
        "testing"
TESTHEADER

    echo "$clusters_json" | node -e "
      const clusters = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));
      const seen = new Set();
      const lines = [];
      for (const cluster of clusters) {
        const pkg = cluster.goPackage || 'main';
        if (seen.has(pkg)) continue;
        seen.add(pkg);
        let alias = pkg.split('/').pop().replace(/[^a-zA-Z0-9_]/g, '_');
        if (!alias || /^[0-9]/.test(alias)) alias = 'pkg_' + alias;
        if (alias === 'main') alias = 'mainpkg';
        lines.push('  ' + alias + ' \"' + pkg + '\"');
      }
      console.log(lines.join('\n'));
    "
    echo ")"
    echo ""

    echo "func TestRegretValidate(t *testing.T) {"
    echo "  regretDir := \"${PROJECT_DIR}/regrets\""
    echo "  failed := 0"
    echo "  total := 0"
    echo ""

    echo "$clusters_json" | ALIAS_MAP="$alias_map_json" node -e "
      const clusters = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));
      const aliasMap = JSON.parse(process.env.ALIAS_MAP || '{}');

      for (const cluster of clusters) {
        const { id, entry, goPackage, multiArgs } = cluster;
        const pkg = goPackage || 'main';
        const alias = aliasMap[pkg];

        console.log('  // Cluster: ' + id);
        console.log('  t.Run(\"' + id + '\", func(t *testing.T) {');
        console.log('    total++');
        console.log('    regretPath := filepath.Join(regretDir, \"' + id + '.regret\")');
        console.log('    content, err := os.ReadFile(regretPath)');
        console.log('    if err != nil {');
        console.log('      t.Errorf(\"❌ ' + id + ': .regret file missing: %v\", err)');
        console.log('      failed++');
        console.log('      return');
        console.log('    }');
        console.log('    savedInputJSON, goldenHash, parseErr := parseRegretFile(string(content))');
        console.log('    if parseErr != nil {');
        console.log('      t.Errorf(\"❌ ' + id + ': %v\", parseErr)');
        console.log('      failed++');
        console.log('      return');
        console.log('    }');
        console.log('    var savedInput interface{}');
        console.log('    if err := json.Unmarshal([]byte(savedInputJSON), &savedInput); err != nil {');
        console.log('      t.Errorf(\"❌ ' + id + ': input unmarshal failed: %v\", err)');
        console.log('      failed++');
        console.log('      return');
        console.log('    }');
        console.log('    entryFn := reflect.ValueOf(' + alias + '.' + entry + ')');
        console.log('    if entryFn.Kind() != reflect.Func {');
        console.log('      t.Errorf(\"❌ ' + id + ': entry ' + entry + ' not a function\")');
        console.log('      failed++');
        console.log('      return');
        console.log('    }');
        console.log('    liveOutput, invokeErr := invokeEntry(entryFn, savedInput, ' + (multiArgs ? 'true' : 'false') + ')');
        console.log('    if invokeErr != nil {');
        console.log('      t.Errorf(\"❌ ' + id + ': invoke threw: %v (golden was %s)\", invokeErr, goldenHash)');
        console.log('      failed++');
        console.log('      return');
        console.log('    }');
        console.log('    liveHash := fingerprint(savedInput, liveOutput)');
        console.log('    if liveHash == goldenHash {');
        console.log('      t.Logf(\"✅ ' + id + ' %s PASS\", goldenHash)');
        console.log('    } else {');
        console.log('      t.Errorf(\"❌ ' + id + ' %s → %s FAIL\", goldenHash, liveHash)');
        console.log('      failed++');
        console.log('    }');
        console.log('  })');
        console.log('');
      }

      console.log('  t.Logf(\"────────────────────────────────────────────────────\")');
      console.log('  if failed == 0 {');
      console.log('    t.Logf(\"✅ All %d Go cluster(s) PASS\", total)');
      console.log('  } else {');
      console.log('    t.Logf(\"❌ %d/%d Go cluster(s) FAILED\", failed, total)');
      console.log('  }');
      console.log('  _ = fmt.Sprintf');
      console.log('}');
    "
  } > "$test_file"

  echo "$test_file"
}

# ─── Main dispatch ────────────────────────────────────────────────────────────

case "$MODE" in
  capture)
    echo "📡 Capturing Go clusters..."

    if ! command -v go &> /dev/null; then
      echo "⚠️  Go is not installed. Install Go to use the Go stack."
      echo "   See references/go.md for the Go capture protocol."
      exit 0
    fi

    CLUSTERS_JSON=$(read_go_clusters)

    if [ "$CLUSTERS_JSON" = "[]" ]; then
      echo "No Go clusters found in manifest."
      exit 0
    fi

    echo "Found Go clusters:"
    echo "$CLUSTERS_JSON" | node -e "
      const clusters = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));
      clusters.forEach(c => console.log('  - ' + c.id + ' (' + c.entry + ')'));
    "

    # Generate helpers + test file
    HELPERS_FILE=$(generate_helpers_file)
    TEST_FILE=$(generate_capture_test "$CLUSTERS_JSON")
    echo "📄 Generated: $TEST_FILE"

    # Remove any stale validate test file (avoid package conflicts)
    rm -f "${REGRET_DIR}/regret_validate_test.go"

    echo "🔧 Building Go modules..."
    go build ./... 2>&1 || true

    echo "🧪 Running regret capture..."
    if go test -v -run TestRegretCapture "$REGRET_DIR" 2>&1; then
      echo ""
      echo "──────────────────────────────────────────────────"
      echo "Capture complete."
      echo ""
      echo "Next: bash scripts/capture_go.sh validate"
      echo "If all green → you are clear to refactor."
    else
      echo ""
      echo "⚠️  Go test execution failed."
      echo "   Check the test output above for compilation or runtime errors."
      echo "   Common issues:"
      echo "     - Package path mismatch (check goPackage field in manifest)"
      echo "     - Entry function not exported (must start with uppercase letter)"
      echo "     - go.mod not in project root"
      echo "     - For 'main' package: ensure there's a main() function"
      exit 1
    fi
    ;;

  validate)
    echo "🔍 Validating Go clusters..."

    if ! command -v go &> /dev/null; then
      echo "⚠️  Go is not installed. Cannot validate Go clusters."
      exit 0
    fi

    CLUSTERS_JSON=$(read_go_clusters)

    if [ "$CLUSTERS_JSON" = "[]" ]; then
      echo "No Go clusters found in manifest."
      exit 0
    fi

    HELPERS_FILE=$(generate_helpers_file)
    TEST_FILE=$(generate_validate_test "$CLUSTERS_JSON")
    echo "📄 Generated: $TEST_FILE"

    # Remove stale capture test file
    rm -f "${REGRET_DIR}/regret_capture_test.go"

    echo "🧪 Running regret validation..."
    if go test -v -run TestRegretValidate "$REGRET_DIR" 2>&1; then
      echo ""
      echo "────────────────────────────────────────────────────"
      echo "✅ All Go clusters validated — refactor is safe."
    else
      echo ""
      echo "────────────────────────────────────────────────────"
      echo "❌ Validation FAILED — fix the CODE, do not edit .regret files."
      echo "   Re-run: bash scripts/capture_go.sh validate"
      exit 1
    fi
    ;;

  health)
    node "$SKILL_DIR/scripts/health.js"
    ;;

  *)
    echo "Usage: bash scripts/capture_go.sh [capture|validate|health] [--cluster <id>]"
    echo ""
    echo "Default mode is 'capture' if no mode is specified."
    echo ""
    echo "Examples:"
    echo "  bash scripts/capture_go.sh                    # capture all Go clusters"
    echo "  bash scripts/capture_go.sh validate           # validate all Go clusters"
    echo "  bash scripts/capture_go.sh --cluster to-valid-bf   # capture single cluster"
    exit 1
    ;;
esac
