#!/usr/bin/env bash
# capture_go.sh — compile + run regret capture for Go clusters
# Generates a Go test file from manifest.json, runs `go test`, and writes .regret files.
#
# Usage:
#   bash scripts/capture_go.sh                # capture all Go clusters
#   bash scripts/capture_go.sh validate       # validate all Go clusters
#   bash scripts/capture_go.sh health         # health report (delegates to health.js)
#   bash scripts/capture_go.sh --cluster to-valid-bf

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_DIR="$(pwd)"
MANIFEST="${PROJECT_DIR}/regrets/manifest.json"
REGRET_DIR="${PROJECT_DIR}/regrets"

# Ensure regrets directory exists
mkdir -p "$REGRET_DIR"

MODE="${1:-capture}"
CLUSTER_FLAG=""

# Parse --cluster flag
for arg in "$@"; do
  if [[ "$arg" == "--cluster" ]]; then
    shift
    CLUSTER_FLAG="--cluster $1"
    break
  fi
done

# ─── Helper: Generate Go fingerprint code ─────────────────────────────────────

# The Go fingerprint code must produce IDENTICAL results to the JS/Python/Rust
# implementations: sha256(stableStringify(input) + "|" + stableStringify(output)) → base36 → first 7 chars

FINGERPRINT_GO=$(cat <<'GOEOF'
package regrettest

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"math/big"
	"sort"
)

// stableStringify produces a deterministic JSON string with sorted keys.
// Must produce identical output to JS stableStringify() and Python stable_dumps().
func stableStringify(obj interface{}) string {
	return doStableStringify(obj)
}

func doStableStringify(obj interface{}) string {
	if obj == nil {
		return "null"
	}
	switch v := obj.(type) {
	case bool:
		if v {
			return "true"
		}
		return "false"
	case int:
		return fmt.Sprintf("%d", v)
	case int64:
		return fmt.Sprintf("%d", v)
	case float64:
		return fmt.Sprintf("%g", v)
	case string:
		b, _ := json.Marshal(v)
		return string(b)
	case []interface{}:
		parts := make([]string, len(v))
		for i, item := range v {
			parts[i] = doStableStringify(item)
		}
		return "[" + joinStrings(parts, ",") + "]"
	case map[string]interface{}:
		keys := make([]string, 0, len(v))
		for k := range v {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		parts := make([]string, len(keys))
		for i, k := range keys {
			b, _ := json.Marshal(k)
			parts[i] = string(b) + ":" + doStableStringify(v[k])
		}
		return "{" + joinStrings(parts, ",") + "}"
	default:
		b, _ := json.Marshal(v)
		return string(b)
	}
}

func joinStrings(ss []string, sep string) string {
	result := ""
	for i, s := range ss {
		if i > 0 {
			result += sep
		}
		result += s
	}
	return result
}

// toBase36 converts a big.Int to base36 string (lowercase).
// Must produce identical output to JS BigInt.toString(36) and Python to_base36().
func toBase36(n *big.Int) string {
	if n.Sign() == 0 {
		return "0"
	}
	chars := "0123456789abcdefghijklmnopqrstuvwxyz"
	base := big.NewInt(36)
	zero := big.NewInt(0)
	result := ""
	remainder := new(big.Int)
	temp := new(big.Int).Set(n)
	if temp.Sign() < 0 {
		temp.Abs(temp)
	}
	for temp.Cmp(zero) > 0 {
		temp.DivMod(temp, base, remainder)
		result = string(chars[int(remainder.Int64())]) + result
	}
	return result
}

// fingerprint computes the 7-char base36 fingerprint.
// IDENTICAL algorithm to fingerprint.js / fingerprint.py / fingerprint.rs:
//   sha256(stableStringify(input) + "|" + stableStringify(output)) → base36 → first 7 chars
func fingerprint(input interface{}, output interface{}) string {
	combined := stableStringify(input) + "|" + stableStringify(output)
	hash := sha256.Sum256([]byte(combined))
	hexStr := fmt.Sprintf("%x", hash)
	bigNum := new(big.Int)
	bigNum.SetString(hexStr, 16)
	b36 := toBase36(bigNum)
	if len(b36) >= 7 {
		return b36[:7]
	}
	return b36
}
GOEOF
)

# ─── Helper: Read Go clusters from manifest ───────────────────────────────────

read_go_clusters() {
  if [ ! -f "$MANIFEST" ]; then
    echo "❌ regrets/manifest.json not found"
    exit 1
  fi
  # Use node to extract Go clusters since bash can't parse JSON easily
  node -e "
    const m = JSON.parse(require('fs').readFileSync('$MANIFEST', 'utf8'));
    const clusters = m.clusters.filter(c => c.stack === 'go');
    if ('$CLUSTER_FLAG') {
      const id = '$CLUSTER_FLAG'.trim();
      const filtered = clusters.filter(c => c.id === id);
      console.log(JSON.stringify(filtered));
    } else {
      console.log(JSON.stringify(clusters));
    }
  "
}

# ─── Helper: Generate Go test file ────────────────────────────────────────────

generate_capture_test() {
  local clusters_json="$1"
  local test_file="${REGRET_DIR}/regret_capture_test.go"

  # Build the test file
  cat > "$test_file" << 'TESTHEADER'
// regret_capture_test.go — auto-generated by capture_go.sh
// DO NOT EDIT — this file is regenerated on each capture run.
package regrettest

import (
	"encoding/json"
	"fmt"
	"os"
	"testing"
	"time"
)

TESTHEADER

  # Add fingerprint code
  echo "$FINGERPRINT_GO" >> "$test_file"

  # Now add a test function for each cluster
  echo "$clusters_json" | node -e "
    const clusters = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));
    const lines = [];
    lines.push('');
    lines.push('func TestRegretCapture(t *testing.T) {');

    for (const cluster of clusters) {
      const { id, entry, file, goPackage, goTestPkg, multiArgs, inputs } = cluster;
      const pkgAlias = goPackage ? goPackage.split('/').pop() : '';
      const testInputs = inputs || [null];

      lines.push('  // Cluster: ' + id);
      lines.push('  t.Run(\"' + id + '\", func(t *testing.T) {');

      // For each input, generate a call
      for (let i = 0; i < testInputs.length; i++) {
        const input = testInputs[i];
        const inputJSON = JSON.stringify(input);
        lines.push('    var input' + i + ' interface{} = ' + convertToGoLiteral(input, multiArgs));
        lines.push('    // TODO: Call ' + entry + ' with input and capture output');
        lines.push('    // output' + i + ' := ' + (pkgAlias ? pkgAlias + '.' : '') + entry + '(' + (input === null ? '' : 'input' + i) + ')');
      }

      lines.push('    // Fingerprint computation');
      lines.push('    // fp := fingerprint(input0, output0)');
      lines.push('    // Write .regret file');
      lines.push('    t.Log(\"Capture not yet implemented for Go — see references/go.md\")');
      lines.push('    t.Skip(\"Go capture requires manual test implementation\")');
      lines.push('  });');
      lines.push('');
    }

    lines.push('}');

    function convertToGoLiteral(val, multiArgs) {
      if (val === null) return 'nil';
      if (typeof val === 'string') return JSON.stringify(val);
      if (typeof val === 'number') return String(val);
      if (typeof val === 'boolean') return String(val);
      if (Array.isArray(val)) {
        if (multiArgs) {
          return '[]interface{}{' + val.map(v => convertToGoLiteral(v, false)).join(', ') + '}';
        }
        return '[]interface{}{' + val.map(v => convertToGoLiteral(v, false)).join(', ') + '}';
      }
      if (typeof val === 'object') {
        const entries = Object.entries(val).map(([k, v]) => '\"' + k + '\": ' + convertToGoLiteral(v, false));
        return 'map[string]interface{}{' + entries.join(', ') + '}';
      }
      return 'nil';
    }

    console.log(lines.join('\n'));
  " >> "$test_file"

  echo "$test_file"
}

# ─── Helper: Generate validate test file ──────────────────────────────────────

generate_validate_test() {
  local clusters_json="$1"
  local test_file="${REGRET_DIR}/regret_validate_test.go"

  cat > "$test_file" << 'TESTHEADER'
// regret_validate_test.go — auto-generated by capture_go.sh
// DO NOT EDIT — this file is regenerated on each validate run.
package regrettest

import (
	"testing"
)

TESTHEADER

  echo "$FINGERPRINT_GO" >> "$test_file"

  echo "$clusters_json" | node -e "
    const clusters = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));
    const lines = [];
    lines.push('');
    lines.push('func TestRegretValidate(t *testing.T) {');

    for (const cluster of clusters) {
      lines.push('  t.Run(\"' + cluster.id + '\", func(t *testing.T) {');
      lines.push('    // Read .regret file, re-run entry function, compare fingerprint');
      lines.push('    t.Log(\"Validate not yet implemented for Go — see references/go.md\")');
      lines.push('    t.Skip(\"Go validate requires manual test implementation\")');
      lines.push('  });');
    }

    lines.push('}');

    console.log(lines.join('\n'));
  " >> "$test_file"

  echo "$test_file"
}

# ─── Main dispatch ────────────────────────────────────────────────────────────

case "$MODE" in
  capture)
    echo "📡 Capturing Go clusters..."

    # Check if go is available
    if ! command -v go &> /dev/null; then
      echo "⚠️  Go is not installed. Install Go to use the Go stack."
      echo "   Alternatively, use the manual capture approach described in references/go.md."
      echo ""
      echo "   For bfgo specifically, the following pure functions can be fingerprinted:"
      echo "   - readcode.ToValidBF(s string) string"
      echo "   - interpreter.MatchLoopIndices(index int, code string) (int, int, string)"
      echo "   - utils.RuneInSlice(a rune, list []rune) bool"
      echo "   - bffmt.format(code string) string"
      echo ""
      echo "   See references/go.md for the Go capture protocol."
      exit 0
    fi

    # Read clusters from manifest
    CLUSTERS_JSON=$(read_go_clusters)

    if [ "$CLUSTERS_JSON" = "[]" ]; then
      echo "No Go clusters found in manifest."
      exit 0
    fi

    echo "Found Go clusters:"
    echo "$CLUSTERS_JSON" | node -e "
      const clusters = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));
      clusters.forEach(c => console.log('  - ' + c.id + ' (' + c.entry + ')'));
    "

    # Generate test file
    TEST_FILE=$(generate_capture_test "$CLUSTERS_JSON")
    echo "📄 Generated: $TEST_FILE"

    # Build first to ensure modules are available
    echo "🔧 Building Go modules..."
    go build ./... 2>/dev/null || true

    # Run capture test
    echo "🧪 Running regret capture..."
    go test -v -run TestRegretCapture "$REGRET_DIR" 2>&1 || {
      echo "⚠️  Go test execution failed."
      echo "   The generated test file requires manual implementation."
      echo "   See references/go.md for step-by-step instructions."
    }
    ;;

  validate)
    echo "🔍 Validating Go clusters..."

    if ! command -v go &> /dev/null; then
      echo "⚠️  Go is not installed. Cannot validate Go clusters."
      exit 0
    fi

    CLUSTERS_JSON=$(read_go_clusters)

    if [ "$CLUSTERS_JSON" = "[]" ]; then
      echo "No Go clusters found in manifest."
      exit 0
    fi

    # Generate validate test file
    TEST_FILE=$(generate_validate_test "$CLUSTERS_JSON")
    echo "📄 Generated: $TEST_FILE"

    # Run validate test
    echo "🧪 Running regret validation..."
    go test -v -run TestRegretValidate "$REGRET_DIR" 2>&1 || {
      echo "⚠️  Go validate test execution failed."
      echo "   See references/go.md for manual validation instructions."
    }
    ;;

  health)
    node "$SKILL_DIR/scripts/health.js"
    ;;

  *)
    echo "Usage: bash scripts/capture_go.sh [capture|validate|health] [--cluster <id>]"
    exit 1
    ;;
esac
