// validate_dart.dart — regression validator for Dart clusters
//
// Reads .regret files for Dart clusters, re-invokes the entry function
// with the recorded INPUT, recomputes the fingerprint, compares to the
// stored HASH, and reports PASS/FAIL with a diff.
//
// Usage:
//   dart run scripts/validate_dart.dart
//   dart run scripts/validate_dart.dart --cluster my-cluster
//   dart run scripts/validate_dart.dart --fail-fast
//   dart run scripts/validate_dart.dart --update my-cluster --reason "..."
//
// .regret file format (parsed by this script):
//   cluster: <id>
//   version: 1
//   fingerprint: <7char>
//   captured: <ISO8601>
//   watches: [...]
//   entry: <name>
//   stack: dart
//   fingerprintLevel: entry
//   ... (optional: normalize, ignoreFields, multiArgs, file, libraryUri)
//   ---
//   INPUT  <json>
//   OUTPUT <json>
//   HASH   <7char>
//
// On PASS: prints "✅ PASS <cluster> hash=<hash>".
// On FAIL: prints "❌ FAIL <cluster>", expected vs actual hash, expected vs
//          actual OUTPUT, then exits 1 (or continues if --fail-fast not set).

import 'dart:convert';
import 'dart:io';
import 'dart:mirrors';

import 'fingerprint_dart.dart';

// ─── Manifest-aware entry-point invocation (shared with capture_dart.dart) ───
// dart:mirrors cannot resolve a library by file path that hasn't been
// imported. So we generate a small temporary harness file that imports
// the target file, looks up the entry symbol, invokes it with the recorded
// input (passed as JSON via env var REGRET_INPUT), and prints the output
// as JSON to stdout. Same approach as capture_dart.dart — kept in sync.

String _harnessCode(String entryName, String targetAbsPath) {
  final targetUri = Uri.file(targetAbsPath).toString();
  final parts = <String>[
    "// AUTO-GENERATED by validate_dart.dart — do not edit.",
    "import 'dart:convert';",
    "import 'dart:io';",
    "import 'dart:mirrors';",
    "import '$targetUri';",
    "",
    "void main(List<String> args) {",
    "  final inputJson = Platform.environment['REGRET_INPUT'];",
    "  final multiArgs = Platform.environment['REGRET_MULTIARGS'] == 'true';",
    "  Object? input;",
    "  if (inputJson != null && inputJson.isNotEmpty) {",
    "    input = jsonDecode(inputJson);",
    "  }",
    "",
    "  final entrySymbol = MirrorSystem.getSymbol('$entryName');",
    "  LibraryMirror? lib;",
    "  for (final l in currentMirrorSystem().libraries.values) {",
    "    final d = l.declarations[entrySymbol];",
    "    if (d is MethodMirror && d.isRegularMethod) {",
    "      lib = l;",
    "      break;",
    "    }",
    "  }",
    "  if (lib == null) {",
    "    stderr.writeln('REGRET_ERROR entry function $entryName not found in any loaded library');",
    "    stderr.writeln('REGRET_DONE');",
    "    exit(2);",
    "  }",
    "",
    "  try {",
    "    Object? output;",
    "    if (multiArgs && input is List) {",
    "      final args = input.cast<Object?>().toList();",
    "      output = lib.invoke(entrySymbol, args).reflectee;",
    "    } else {",
    "      output = lib.invoke(entrySymbol, [input]).reflectee;",
    "    }",
    "    stdout.writeln('REGRET_OUTPUT ' + jsonEncode(output));",
    "    stderr.writeln('REGRET_DONE');",
    "  } catch (e, st) {",
    "    stderr.writeln('REGRET_ERROR ' + e.toString());",
    "    stderr.writeln('REGRET_DONE');",
    "    exit(1);",
    "  }",
    "}",
  ];
  return parts.join('\n') + '\n';
}

Future<({Object? output, String? error})> _invokeViaHarness(
  RegretFile r,
  String targetAbsPath,
) async {
  final harnessDir = Directory.systemTemp.createTempSync('regret_dart_validate_');
  final harnessPath = '${harnessDir.path}/harness.dart';
  File(harnessPath).writeAsStringSync(_harnessCode(r.entry, targetAbsPath));

  try {
    final inputJson = jsonEncode(r.input);
    final result = await Process.run(
      'dart',
      ['run', '--enable-asserts', harnessPath],
      environment: {
        'REGRET_INPUT': inputJson,
        'REGRET_MULTIARGS': r.multiArgs ? 'true' : 'false',
      },
      workingDirectory: Directory.current.path,
    );

    final stdout = result.stdout as String;
    final stderr = result.stderr as String;

    String? outputLine;
    for (final line in stdout.split('\n')) {
      if (line.startsWith('REGRET_OUTPUT ')) {
        outputLine = line.substring('REGRET_OUTPUT '.length);
        break;
      }
    }

    if (outputLine != null) {
      try {
        final output = jsonDecode(outputLine);
        return (output: output, error: null);
      } catch (_) {
        return (output: outputLine, error: null);
      }
    }

    for (final line in stderr.split('\n')) {
      if (line.startsWith('REGRET_ERROR ')) {
        return (output: null, error: line.substring('REGRET_ERROR '.length));
      }
    }

    return (
      output: null,
      error: 'harness produced no output. stderr: ${stderr.trim()}',
    );
  } finally {
    harnessDir.deleteSync(recursive: true);
  }
}

// ─── CLI args ─────────────────────────────────────────────────────────────────

({String? clusterFilter, bool failFast, String manifestPath, String? updateTarget, String? updateReason})
_parseArgs(List<String> args) {
  String? clusterFilter;
  var failFast = false;
  String? manifestPath;
  String? updateTarget;
  String? updateReason;
  var i = 0;
  while (i < args.length) {
    if (args[i] == '--cluster' && i + 1 < args.length) {
      clusterFilter = args[++i];
    } else if (args[i] == '--fail-fast') {
      failFast = true;
    } else if (args[i] == '--manifest' && i + 1 < args.length) {
      manifestPath = args[++i];
    } else if (args[i] == '--update' && i + 1 < args.length) {
      updateTarget = args[++i];
    } else if (args[i] == '--reason' && i + 1 < args.length) {
      updateReason = args[++i];
    }
    i++;
  }
  manifestPath ??= '${Directory.current.path}/regrets/manifest.json';
  return (
    clusterFilter: clusterFilter,
    failFast: failFast,
    manifestPath: manifestPath,
    updateTarget: updateTarget,
    updateReason: updateReason,
  );
}

// ─── .regret file parser ─────────────────────────────────────────────────────

class RegretFile {
  final String cluster;
  final int version;
  final String goldenHash;
  final String entry;
  final List<String> watches;
  final String? file;
  final String? libraryUri;
  final List<String> normalizeRules;
  final List<String> ignoreFields;
  final bool multiArgs;
  final Object? input;
  final Object? output;

  RegretFile({
    required this.cluster,
    required this.version,
    required this.goldenHash,
    required this.entry,
    required this.watches,
    this.file,
    this.libraryUri,
    required this.normalizeRules,
    required this.ignoreFields,
    required this.multiArgs,
    this.input,
    this.output,
  });
}

List<String> _parseListField(String val) {
  final trimmed = val.trim();
  if (trimmed.isEmpty) return [];
  // Strip surrounding []
  final inner = trimmed.startsWith('[') && trimmed.endsWith(']')
      ? trimmed.substring(1, trimmed.length - 1)
      : trimmed;
  if (inner.trim().isEmpty) return [];
  return inner
      .split(',')
      .map((s) => s.trim())
      .where((s) => s.isNotEmpty)
      .toList();
}

RegretFile _parseRegret(String content) {
  final sections = content.split('---');
  final metaSection = sections[0];
  final dataSection = sections.length > 1 ? sections.sublist(1).join('---') : '';

  final meta = <String, String>{};
  for (final line in metaSection.split('\n')) {
    final idx = line.indexOf(': ');
    if (idx == -1) continue;
    final key = line.substring(0, idx);
    final val = line.substring(idx + 2);
    meta[key] = val;
  }

  // Parse data section: lines starting with INPUT / OUTPUT / HASH
  String? inputLine;
  String? outputLine;
  String? hashLine;
  for (final line in dataSection.split('\n')) {
    if (line.startsWith('INPUT ')) inputLine = line.substring('INPUT '.length);
    if (line.startsWith('OUTPUT ')) outputLine = line.substring('OUTPUT '.length);
    if (line.startsWith('HASH ')) hashLine = line.substring('HASH '.length);
  }

  Object? parseJsonOrUndef(String? s) {
    if (s == null) return null;
    if (s == 'undefined') return null;
    try {
      return json.decode(s);
    } catch (_) {
      return s;
    }
  }

  return RegretFile(
    cluster: meta['cluster'] ?? '',
    version: int.tryParse(meta['version'] ?? '1') ?? 1,
    goldenHash: (hashLine ?? '').trim(),
    entry: meta['entry'] ?? '',
    watches: _parseListField(meta['watches'] ?? ''),
    file: meta['file'],
    libraryUri: meta['libraryUri'],
    normalizeRules: _parseListField(meta['normalize'] ?? ''),
    ignoreFields: _parseListField(meta['ignoreFields'] ?? ''),
    multiArgs: (meta['multiArgs'] ?? 'false') == 'true',
    input: parseJsonOrUndef(inputLine),
    output: parseJsonOrUndef(outputLine),
  );
}

// ─── Re-invoke entry function (via temporary harness) ────────────────────────
// Cannot use dart:mirrors directly to load a file-by-path that hasn't been
// imported. We spawn a temporary harness Dart file that imports the target
// and invokes the entry. See _invokeViaHarness above.

Future<({Object? output, String? error})> _invokeEntry(RegretFile r) async {
  if (r.file == null && r.libraryUri == null) {
    throw StateError('RegretFile for ${r.cluster} has neither file nor libraryUri');
  }
  final targetAbsPath = r.file != null
      ? '${Directory.current.path}/${r.file}'
      : r.libraryUri!;
  if (r.file != null && !File(targetAbsPath).existsSync()) {
    throw StateError('Target file not found: $targetAbsPath');
  }
  return _invokeViaHarness(r, targetAbsPath);
}

// ─── Validate one cluster ────────────────────────────────────────────────────

enum ValidateResult { pass, fail, skip }

Future<({ValidateResult result, String? actualHash, Object? actualOutput, String? error})>
_validateOne(RegretFile r) async {
  try {
    final res = await _invokeEntry(r);
    if (res.error != null) {
      return (
        result: ValidateResult.fail,
        actualHash: null,
        actualOutput: null,
        error: 'invocation threw: ${res.error}',
      );
    }
    final actualOutput = res.output;
    if (isTrivialOutput(actualOutput)) {
      return (
        result: ValidateResult.skip,
        actualHash: null,
        actualOutput: actualOutput,
        error: 'trivial output (null/NaN/empty)',
      );
    }
    final actualHash = fingerprint(
      r.input,
      actualOutput,
      rules: r.normalizeRules,
      ignoreFields: r.ignoreFields,
    );
    final ok = actualHash == r.goldenHash;
    return (
      result: ok ? ValidateResult.pass : ValidateResult.fail,
      actualHash: actualHash,
      actualOutput: actualOutput,
      error: ok ? null : 'hash mismatch',
    );
  } catch (e) {
    return (
      result: ValidateResult.fail,
      actualHash: null,
      actualOutput: null,
      error: 'invocation threw: $e',
    );
  }
}

// ─── Main ────────────────────────────────────────────────────────────────────

Future<void> main(List<String> argv) async {
  final args = _parseArgs(argv);

  // --update requires --reason
  if (args.updateTarget != null && (args.updateReason == null ||
      args.updateReason!.split(' ').where((w) => w.isNotEmpty).length < 4)) {
    stderr.writeln('❌ --update requires --reason with at least 4 words.');
    stderr.writeln('   Example: --update my-cluster --reason "tax rate changed from 11% to 12%"');
    exit(1);
  }

  final regretDir = Directory('${Directory.current.path}/regrets');
  if (!regretDir.existsSync()) {
    stderr.writeln('❌ regrets/ directory not found.');
    exit(1);
  }

  final filterId = args.clusterFilter ?? args.updateTarget;
  final regretFiles = <File>[];
  for (final f in regretDir.listSync()) {
    if (f is! File) continue;
    if (!f.path.endsWith('.regret')) continue;
    if (filterId != null) {
      final id = f.path.split('/').last.replaceAll('.regret', '');
      // Also include callee files: <parent>.calls.<callee>.regret — skip for v1
      if (id != filterId) continue;
    }
    regretFiles.add(f);
  }

  // Also filter by stack: dart — read each .regret, check stack field
  final dartRegrets = <RegretFile>[];
  for (final f in regretFiles) {
    final content = f.readAsStringSync();
    final r = _parseRegret(content);
    // Check stack: dart in raw meta
    final stackMatch = RegExp(r'^stack:\s*(\S+)', multiLine: true)
        .firstMatch(content);
    final stack = stackMatch?.group(1) ?? '';
    if (stack != 'dart') continue;
    dartRegrets.add(r);
  }

  if (dartRegrets.isEmpty) {
    stdout.writeln('No Dart .regret files found.'
        '${filterId != null ? ' (filter: "$filterId")' : ''}');
    exit(0);
  }

  stdout.writeln('🔍 Validating ${dartRegrets.length} Dart regret file(s)...');

  var pass = 0;
  var fail = 0;
  var skip = 0;

  for (final r in dartRegrets) {
    final res = await _validateOne(r);
    switch (res.result) {
      case ValidateResult.pass:
        stdout.writeln('✅ PASS  ${r.cluster}  hash=${res.actualHash}');
        pass++;
      case ValidateResult.fail:
        stdout.writeln('❌ FAIL  ${r.cluster}');
        stdout.writeln('   expected hash: ${r.goldenHash}');
        stdout.writeln('   actual hash:   ${res.actualHash ?? "(none)"}');
        stdout.writeln('   reason:        ${res.error}');
        stdout.writeln('   expected OUTPUT: ${json.encode(r.output)}');
        stdout.writeln('   actual OUTPUT:   ${json.encode(res.actualOutput)}');
        fail++;
        if (args.failFast) {
          stdout.writeln('\n⚠️  --fail-fast: stopping on first failure.');
          exit(1);
        }
      case ValidateResult.skip:
        stdout.writeln('⏭️  SKIP  ${r.cluster}  (${res.error})');
        skip++;
    }
  }

  stdout.writeln('\n${"─" * 50}');
  stdout.writeln('Validation summary: $pass PASS, $fail FAIL, $skip SKIP');

  if (fail > 0) {
    stdout.writeln('\n❌ Regression detected. Fix the code, NOT the .regret file.');
    exit(1);
  }
  stdout.writeln('\n✅ All green. Clear to refactor.');
}
