#!/usr/bin/env bash
# validate_csharp.sh — re-run C# clusters and compare fingerprints
#
# For each csharp cluster in regrets/manifest.json:
#   1. Read the matching .regret file (regrets/<id>.regret)
#   2. Parse INPUT / HASH (and INPUTS for multi-input clusters, issue #315)
#   3. Re-invoke the entry method with each input
#   4. Compute the live fingerprint and compare to the stored HASH
#   5. Report PASS / FAIL with a clean diff
#
# Exit code: 0 if ALL clusters pass, 1 if ANY cluster fails.
#
# Usage:
#   bash scripts/validate_csharp.sh                  # validate all csharp clusters
#   bash scripts/validate_csharp.sh --cluster calc-add
#   bash scripts/validate_csharp.sh --verbose
#
# Requirements:
#   - dotnet SDK 8+ on PATH (or set DOTNET_CMD=/path/to/dotnet)
#   - regrets/manifest.json + regrets/<id>.regret files in the current directory
#   - User source files in src/ (or set REGRET_CSHARP_SRC=/path/to/src)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_DIR="$(pwd)"
MANIFEST="${PROJECT_DIR}/regrets/manifest.json"
REGRET_DIR="${PROJECT_DIR}/regrets"
HELPER_CS="${SCRIPT_DIR}/RegretFingerprint.cs"

DOTNET_CMD="${DOTNET_CMD:-dotnet}"
USER_SRC_DIR="${REGRET_CSHARP_SRC:-${PROJECT_DIR}/src}"

CLUSTER_FILTER=""
VERBOSE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --cluster)   CLUSTER_FILTER="$2"; shift 2 ;;
    --verbose|-v) VERBOSE=true; shift ;;
    --help|-h)
      sed -n '2,/^set -euo/p' "$0" | sed 's/^# \?//'
      exit 0 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

mkdir -p "$REGRET_DIR"

# ─── Pre-flight ───────────────────────────────────────────────────────────────
if [ ! -f "$MANIFEST" ]; then
  echo "❌ regrets/manifest.json not found at $MANIFEST" >&2
  exit 1
fi
if [ ! -f "$HELPER_CS" ]; then
  echo "❌ Helper not found: $HELPER_CS" >&2
  exit 1
fi
if ! command -v "$DOTNET_CMD" >/dev/null 2>&1; then
  echo "❌ dotnet SDK not found on PATH. Install .NET 8+ or set DOTNET_CMD=/path/to/dotnet" >&2
  exit 1
fi
if [ ! -d "$USER_SRC_DIR" ]; then
  echo "❌ Source directory not found: $USER_SRC_DIR" >&2
  exit 1
fi

# ─── Read & filter C# clusters ────────────────────────────────────────────────
CLUSTERS_JSON=$(node -e "
  const fs = require('fs');
  const m = JSON.parse(fs.readFileSync('$MANIFEST', 'utf8'));
  let clusters = (m.clusters || []).filter(c => c.stack === 'csharp');
  if ('$CLUSTER_FILTER') {
    clusters = clusters.filter(c => c.id === '$CLUSTER_FILTER');
  }
  process.stdout.write(JSON.stringify(clusters));
") || {
  echo "No csharp clusters found in manifest." >&2
  exit 0
}

echo "🔍 Validating C# clusters..."

# ─── Generate temporary .NET project ──────────────────────────────────────────
HARNESS_DIR="${REGRET_DIR}/_regret_validate"
rm -rf "$HARNESS_DIR"
mkdir -p "$HARNESS_DIR"

CLUSTERS_FILE="${HARNESS_DIR}/clusters.json"
echo "$CLUSTERS_JSON" > "$CLUSTERS_FILE"

cp "$HELPER_CS" "${HARNESS_DIR}/RegretFingerprint.cs"

USER_CS_FILES=()
shopt -s nullglob
for f in "$USER_SRC_DIR"/*.cs; do
  USER_CS_FILES+=( "$f" )
done
shopt -u nullglob

if [ ${#USER_CS_FILES[@]} -eq 0 ]; then
  echo "❌ No .cs files found in $USER_SRC_DIR" >&2
  exit 1
fi

CSPROJ="${HARNESS_DIR}/RegretValidate.csproj"
{
  echo "<Project Sdk=\"Microsoft.NET.Sdk\">"
  echo "  <PropertyGroup>"
  echo "    <OutputType>Exe</OutputType>"
  echo "    <TargetFramework>net8.0</TargetFramework>"
  echo "    <Nullable>enable</Nullable>"
  echo "    <ImplicitUsings>enable</ImplicitUsings>"
  echo "    <RootNamespace>RegretValidate</RootNamespace>"
  echo "    <AssemblyName>RegretValidate</AssemblyName>"
  echo "  </PropertyGroup>"
  echo "  <ItemGroup>"
  for f in "${USER_CS_FILES[@]}"; do
    echo "    <Compile Include=\"$f\" />"
  done
  echo "    <!-- RegretFingerprint.cs and RegretValidate.cs are auto-included by the SDK -->"
  echo "  </ItemGroup>"
  echo "</Project>"
} > "$CSPROJ"

# ─── Generate RegretValidate.cs ───────────────────────────────────────────────
cat > "${HARNESS_DIR}/RegretValidate.cs" <<'CSHARPEOF'
// RegretValidate.cs — auto-generated by validate_csharp.sh
// DO NOT EDIT — regenerated on every validate run.
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using System.Text.Json;
using RegretSupport;

namespace RegretValidate;

public static class RegretValidate
{
    public static int Main(string[] args)
    {
        if (args.Length < 3)
        {
            Console.Error.WriteLine("Usage: RegretValidate <clusters.json> <regret-dir> <manifest-path>");
            return 1;
        }
        var clustersPath = args[0];
        var regretDir = args[1];

        var clustersJson = File.ReadAllText(clustersPath);
        using var doc = JsonDocument.Parse(clustersJson);

        int totalPass = 0, totalFail = 0, totalSkip = 0;

        foreach (var cluster in doc.RootElement.EnumerateArray())
        {
            var id = cluster.GetProperty("id").GetString()!;
            var regretPath = Path.Combine(regretDir, $"{id}.regret");

            if (!File.Exists(regretPath))
            {
                Console.WriteLine($"   ⚠️  SKIP {id}: no .regret file at {regretPath}");
                totalSkip++;
                continue;
            }

            var (pass, fail, detail) = ValidateCluster(cluster, regretPath);
            if (pass > 0 && fail == 0)
            {
                Console.WriteLine($"   ✅ PASS {id}: {pass} input(s) verified");
                totalPass++;
            }
            else if (fail > 0)
            {
                Console.WriteLine($"   ❌ FAIL {id}: {fail}/{pass + fail} input(s) mismatch");
                foreach (var line in detail) Console.WriteLine($"       {line}");
                totalFail++;
            }
        }

        Console.WriteLine();
        Console.WriteLine($"   Validate summary: {totalPass} pass, {totalFail} fail, {totalSkip} skip");
        return totalFail == 0 ? 0 : 1;
    }

    private static (int pass, int fail, List<string> detail) ValidateCluster(JsonElement cluster, string regretPath)
    {
        var id = cluster.GetProperty("id").GetString()!;
        var entry = cluster.GetProperty("entry").GetString()!;
        var className = cluster.GetProperty("class").GetString()!;
        var regretRaw = File.ReadAllText(regretPath);

        // Parse .regret file: split into meta / data on '---' line
        var parts = regretRaw.Split("\n---\n", 2, StringSplitOptions.None);
        if (parts.Length < 2)
        {
            return (0, 1, new List<string> { $"malformed .regret file: no '---' separator in {regretPath}" });
        }
        var dataSection = parts[1];

        // Extract INPUT / OUTPUT / ERROR_CONTRACT / HASH / INPUTS lines
        string? inputJson = null, outputJson = null, errorContractJson = null, hashStr = null, inputsJson = null;
        foreach (var line in dataSection.Split('\n'))
        {
            if (line.StartsWith("INPUT  ")) inputJson = line.Substring("INPUT  ".Length).Trim();
            else if (line.StartsWith("OUTPUT ")) outputJson = line.Substring("OUTPUT ".Length).Trim();
            else if (line.StartsWith("ERROR_CONTRACT ")) errorContractJson = line.Substring("ERROR_CONTRACT ".Length).Trim();
            else if (line.StartsWith("HASH   ")) hashStr = line.Substring("HASH   ".Length).Trim();
            else if (line.StartsWith("INPUTS ")) inputsJson = line.Substring("INPUTS ".Length).Trim();
        }
        if (hashStr == null || inputJson == null)
        {
            return (0, 1, new List<string> { "missing INPUT or HASH line in .regret file" });
        }

        // Locate the type + method via reflection
        var type = RegretFingerprint.FindType(className)
            ?? throw new InvalidOperationException($"Type not found: {className}");
        var method = type.GetMethod(entry, BindingFlags.Public | BindingFlags.Static)
            ?? throw new InvalidOperationException($"Method not found: {className}.{entry}");

        int pass = 0, fail = 0;
        var detail = new List<string>();

        // Validate input[0] against top-level INPUT/HASH
        var (liveFp, liveOut, threw) = InvokeAndFingerprint(method, inputJson);
        if (liveFp == hashStr)
        {
            pass++;
        }
        else
        {
            fail++;
            detail.Add($"input[0] hash mismatch:");
            detail.Add($"  golden:  {hashStr}");
            detail.Add($"  live:    {liveFp}");
            detail.Add($"  input:   {inputJson}");
            // Show output diff if both have an OUTPUT line (no throw on either side)
            if (outputJson != null && !threw)
            {
                var goldenOut = outputJson;
                var liveOutStr = RegretFingerprint.StableStringify(liveOut);
                if (goldenOut != liveOutStr)
                {
                    detail.Add($"  golden output: {goldenOut}");
                    detail.Add($"  live output:   {liveOutStr}");
                }
            }
            else if (errorContractJson != null && threw)
            {
                detail.Add($"  golden threw:  {errorContractJson}");
                detail.Add($"  live threw:    {RegretFingerprint.StableStringify(liveOut)}");
            }
            else if (errorContractJson != null && !threw)
            {
                detail.Add($"  golden threw:  {errorContractJson}");
                detail.Add($"  live returned: {RegretFingerprint.StableStringify(liveOut)}");
            }
            else if (outputJson != null && threw)
            {
                detail.Add($"  golden returned: {outputJson}");
                detail.Add($"  live threw:      {RegretFingerprint.StableStringify(liveOut)}");
            }
        }

        // Validate inputs[1+] against INPUTS line (issue #315 pattern)
        if (inputsJson != null)
        {
            using var inputsDoc = JsonDocument.Parse(inputsJson);
            int idx = 1;
            foreach (var itemEl in inputsDoc.RootElement.EnumerateArray())
            {
                var goldenHash = itemEl.GetProperty("hash").GetString()!;
                var itemInputJson = RegretFingerprint.StableStringify(itemEl.GetProperty("input"));
                var (liveFp_i, liveOut_i, threw_i) = InvokeAndFingerprint(method, itemInputJson);
                if (liveFp_i == goldenHash)
                {
                    pass++;
                }
                else
                {
                    fail++;
                    detail.Add($"input[{idx}] hash mismatch:");
                    detail.Add($"  golden:  {goldenHash}");
                    detail.Add($"  live:    {liveFp_i}");
                    detail.Add($"  input:   {itemInputJson}");
                    var goldenOutStr = itemEl.GetProperty("output").GetRawText();
                    var liveOutStr = RegretFingerprint.StableStringify(liveOut_i);
                    if (goldenOutStr != liveOutStr)
                    {
                        detail.Add($"  golden output: {goldenOutStr}");
                        detail.Add($"  live output:   {liveOutStr}");
                    }
                }
                idx++;
            }
        }

        return (pass, fail, detail);
    }

    private static (string fp, object? output, bool threw) InvokeAndFingerprint(MethodInfo method, string inputJson)
    {
        using var inputDoc = JsonDocument.Parse(inputJson);
        var inputEl = inputDoc.RootElement.Clone();
        object? output = null;
        bool threw = false;
        try
        {
            output = method.Invoke(null, new object[] { inputEl });
        }
        catch (TargetInvocationException tie)
        {
            threw = true;
            var inner = tie.InnerException;
            output = new { threw = true, type = inner?.GetType().FullName ?? "Unknown", message = inner?.Message ?? "" };
        }
        var fp = RegretFingerprint.Fingerprint(inputEl, output);
        return (fp, output, threw);
    }
}
CSHARPEOF

# ─── Build + run ──────────────────────────────────────────────────────────────
echo "🔧 Building regret validate project..."
export DOTNET_CLI_HOME="${DOTNET_CLI_HOME:-/tmp/dotnet-home-validate}"
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_NOLOGO=1

BUILD_LOG="$("$DOTNET_CMD" build "$CSPROJ" -c Release --nologo -clp:NoSummary 2>&1)" || {
  echo "❌ Build failed:" >&2
  echo "$BUILD_LOG" >&2
  exit 1
}
if $VERBOSE; then
  echo "$BUILD_LOG" | sed 's/^/   build: /'
fi

echo "🧪 Running regret validate..."
"$DOTNET_CMD" run --project "$CSPROJ" -c Release --no-build --no-launch-profile -- \
  "$CLUSTERS_FILE" "$REGRET_DIR" "$MANIFEST"

RC=$?

# Clean up the harness dir on success unless --verbose
if ! $VERBOSE; then
  rm -rf "$HARNESS_DIR"
fi

if [ $RC -eq 0 ]; then
  echo "✅ Validate finished: ALL clusters PASS"
else
  echo "❌ Validate finished: some clusters FAIL (see output above)"
fi
exit $RC
