// regret_capture_test.go — auto-generated by capture_go.sh
// DO NOT EDIT — this file is regenerated on each capture run.
package regrettest

import (
        datetime "github.com/regrets/proof-go-independent/datetime"
        finance "github.com/regrets/proof-go-independent/finance"
        collections "github.com/regrets/proof-go-independent/collections"
        "reflect"
        "testing"
)

func TestRegretCapture(t *testing.T) {
  t.Run("parse-iso8601", func(t *testing.T) {
    var results []regretIO

    // Input 0
    var in0 interface{} = "2026-06-22T15:04:05Z"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 0 for parse-iso8601 threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.ParseISO8601), false, in0)
      if err != nil {
        t.Logf("⚠️  Input 0 for parse-iso8601 error: %v", err)
        return
      }
      hash := fingerprint(in0, out)
      results = append(results, regretIO{Input: in0, Output: out, Hash: hash})
    }()

    // Input 1
    var in1 interface{} = "2026-01-01T00:00:00Z"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 1 for parse-iso8601 threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.ParseISO8601), false, in1)
      if err != nil {
        t.Logf("⚠️  Input 1 for parse-iso8601 error: %v", err)
        return
      }
      hash := fingerprint(in1, out)
      results = append(results, regretIO{Input: in1, Output: out, Hash: hash})
    }()

    // Input 2
    var in2 interface{} = "2026-12-31T23:59:59Z"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 2 for parse-iso8601 threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.ParseISO8601), false, in2)
      if err != nil {
        t.Logf("⚠️  Input 2 for parse-iso8601 error: %v", err)
        return
      }
      hash := fingerprint(in2, out)
      results = append(results, regretIO{Input: in2, Output: out, Hash: hash})
    }()

    // Input 3
    var in3 interface{} = "not-a-date"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 3 for parse-iso8601 threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.ParseISO8601), false, in3)
      if err != nil {
        t.Logf("⚠️  Input 3 for parse-iso8601 error: %v", err)
        return
      }
      hash := fingerprint(in3, out)
      results = append(results, regretIO{Input: in3, Output: out, Hash: hash})
    }()

    if len(results) == 0 {
      t.Errorf("❌ parse-iso8601: all inputs threw/errored — no capture possible")
      return
    }
    if err := writeRegret("parse-iso8601", "ParseISO8601", results); err != nil {
      t.Fatalf("write .regret for parse-iso8601: %v", err)
    }
    t.Logf("✅ parse-iso8601 captured (hash: %s)", results[0].Hash)
  })

  t.Run("format-duration", func(t *testing.T) {
    var results []regretIO

    // Input 0
    var in0 interface{} = 3661
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 0 for format-duration threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.FormatDuration), false, in0)
      if err != nil {
        t.Logf("⚠️  Input 0 for format-duration error: %v", err)
        return
      }
      hash := fingerprint(in0, out)
      results = append(results, regretIO{Input: in0, Output: out, Hash: hash})
    }()

    // Input 1
    var in1 interface{} = 45
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 1 for format-duration threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.FormatDuration), false, in1)
      if err != nil {
        t.Logf("⚠️  Input 1 for format-duration error: %v", err)
        return
      }
      hash := fingerprint(in1, out)
      results = append(results, regretIO{Input: in1, Output: out, Hash: hash})
    }()

    // Input 2
    var in2 interface{} = 86400
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 2 for format-duration threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.FormatDuration), false, in2)
      if err != nil {
        t.Logf("⚠️  Input 2 for format-duration error: %v", err)
        return
      }
      hash := fingerprint(in2, out)
      results = append(results, regretIO{Input: in2, Output: out, Hash: hash})
    }()

    // Input 3
    var in3 interface{} = -5
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 3 for format-duration threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.FormatDuration), false, in3)
      if err != nil {
        t.Logf("⚠️  Input 3 for format-duration error: %v", err)
        return
      }
      hash := fingerprint(in3, out)
      results = append(results, regretIO{Input: in3, Output: out, Hash: hash})
    }()

    if len(results) == 0 {
      t.Errorf("❌ format-duration: all inputs threw/errored — no capture possible")
      return
    }
    if err := writeRegret("format-duration", "FormatDuration", results); err != nil {
      t.Fatalf("write .regret for format-duration: %v", err)
    }
    t.Logf("✅ format-duration captured (hash: %s)", results[0].Hash)
  })

  t.Run("weekday-name", func(t *testing.T) {
    var results []regretIO

    // Input 0
    var in0 interface{} = "2026-06-22"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 0 for weekday-name threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.WeekdayName), false, in0)
      if err != nil {
        t.Logf("⚠️  Input 0 for weekday-name error: %v", err)
        return
      }
      hash := fingerprint(in0, out)
      results = append(results, regretIO{Input: in0, Output: out, Hash: hash})
    }()

    // Input 1
    var in1 interface{} = "2026-06-21"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 1 for weekday-name threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.WeekdayName), false, in1)
      if err != nil {
        t.Logf("⚠️  Input 1 for weekday-name error: %v", err)
        return
      }
      hash := fingerprint(in1, out)
      results = append(results, regretIO{Input: in1, Output: out, Hash: hash})
    }()

    // Input 2
    var in2 interface{} = "2026-01-01"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 2 for weekday-name threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.WeekdayName), false, in2)
      if err != nil {
        t.Logf("⚠️  Input 2 for weekday-name error: %v", err)
        return
      }
      hash := fingerprint(in2, out)
      results = append(results, regretIO{Input: in2, Output: out, Hash: hash})
    }()

    // Input 3
    var in3 interface{} = "garbage"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 3 for weekday-name threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.WeekdayName), false, in3)
      if err != nil {
        t.Logf("⚠️  Input 3 for weekday-name error: %v", err)
        return
      }
      hash := fingerprint(in3, out)
      results = append(results, regretIO{Input: in3, Output: out, Hash: hash})
    }()

    if len(results) == 0 {
      t.Errorf("❌ weekday-name: all inputs threw/errored — no capture possible")
      return
    }
    if err := writeRegret("weekday-name", "WeekdayName", results); err != nil {
      t.Fatalf("write .regret for weekday-name: %v", err)
    }
    t.Logf("✅ weekday-name captured (hash: %s)", results[0].Hash)
  })

  t.Run("days-between", func(t *testing.T) {
    var results []regretIO

    // Input 0
    var in0 interface{} = []interface{}{"2026-01-01", "2026-01-10"}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 0 for days-between threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.DaysBetween), true, in0)
      if err != nil {
        t.Logf("⚠️  Input 0 for days-between error: %v", err)
        return
      }
      hash := fingerprint(in0, out)
      results = append(results, regretIO{Input: in0, Output: out, Hash: hash})
    }()

    // Input 1
    var in1 interface{} = []interface{}{"2026-01-10", "2026-01-01"}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 1 for days-between threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.DaysBetween), true, in1)
      if err != nil {
        t.Logf("⚠️  Input 1 for days-between error: %v", err)
        return
      }
      hash := fingerprint(in1, out)
      results = append(results, regretIO{Input: in1, Output: out, Hash: hash})
    }()

    // Input 2
    var in2 interface{} = []interface{}{"2026-06-22", "2026-06-22"}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 2 for days-between threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.DaysBetween), true, in2)
      if err != nil {
        t.Logf("⚠️  Input 2 for days-between error: %v", err)
        return
      }
      hash := fingerprint(in2, out)
      results = append(results, regretIO{Input: in2, Output: out, Hash: hash})
    }()

    // Input 3
    var in3 interface{} = []interface{}{"garbage", "2026-01-01"}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 3 for days-between threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.DaysBetween), true, in3)
      if err != nil {
        t.Logf("⚠️  Input 3 for days-between error: %v", err)
        return
      }
      hash := fingerprint(in3, out)
      results = append(results, regretIO{Input: in3, Output: out, Hash: hash})
    }()

    if len(results) == 0 {
      t.Errorf("❌ days-between: all inputs threw/errored — no capture possible")
      return
    }
    if err := writeRegret("days-between", "DaysBetween", results); err != nil {
      t.Fatalf("write .regret for days-between: %v", err)
    }
    t.Logf("✅ days-between captured (hash: %s)", results[0].Hash)
  })

  t.Run("add-business-days", func(t *testing.T) {
    var results []regretIO

    // Input 0
    var in0 interface{} = []interface{}{"2026-06-22", 5}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 0 for add-business-days threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.AddBusinessDays), true, in0)
      if err != nil {
        t.Logf("⚠️  Input 0 for add-business-days error: %v", err)
        return
      }
      hash := fingerprint(in0, out)
      results = append(results, regretIO{Input: in0, Output: out, Hash: hash})
    }()

    // Input 1
    var in1 interface{} = []interface{}{"2026-06-22", 0}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 1 for add-business-days threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.AddBusinessDays), true, in1)
      if err != nil {
        t.Logf("⚠️  Input 1 for add-business-days error: %v", err)
        return
      }
      hash := fingerprint(in1, out)
      results = append(results, regretIO{Input: in1, Output: out, Hash: hash})
    }()

    // Input 2
    var in2 interface{} = []interface{}{"2026-06-19", 1}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 2 for add-business-days threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.AddBusinessDays), true, in2)
      if err != nil {
        t.Logf("⚠️  Input 2 for add-business-days error: %v", err)
        return
      }
      hash := fingerprint(in2, out)
      results = append(results, regretIO{Input: in2, Output: out, Hash: hash})
    }()

    // Input 3
    var in3 interface{} = []interface{}{"garbage", 5}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 3 for add-business-days threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(datetime.AddBusinessDays), true, in3)
      if err != nil {
        t.Logf("⚠️  Input 3 for add-business-days error: %v", err)
        return
      }
      hash := fingerprint(in3, out)
      results = append(results, regretIO{Input: in3, Output: out, Hash: hash})
    }()

    if len(results) == 0 {
      t.Errorf("❌ add-business-days: all inputs threw/errored — no capture possible")
      return
    }
    if err := writeRegret("add-business-days", "AddBusinessDays", results); err != nil {
      t.Fatalf("write .regret for add-business-days: %v", err)
    }
    t.Logf("✅ add-business-days captured (hash: %s)", results[0].Hash)
  })

  t.Run("format-cents", func(t *testing.T) {
    var results []regretIO

    // Input 0
    var in0 interface{} = 1099
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 0 for format-cents threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(finance.FormatCents), false, in0)
      if err != nil {
        t.Logf("⚠️  Input 0 for format-cents error: %v", err)
        return
      }
      hash := fingerprint(in0, out)
      results = append(results, regretIO{Input: in0, Output: out, Hash: hash})
    }()

    // Input 1
    var in1 interface{} = 0
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 1 for format-cents threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(finance.FormatCents), false, in1)
      if err != nil {
        t.Logf("⚠️  Input 1 for format-cents error: %v", err)
        return
      }
      hash := fingerprint(in1, out)
      results = append(results, regretIO{Input: in1, Output: out, Hash: hash})
    }()

    // Input 2
    var in2 interface{} = -550
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 2 for format-cents threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(finance.FormatCents), false, in2)
      if err != nil {
        t.Logf("⚠️  Input 2 for format-cents error: %v", err)
        return
      }
      hash := fingerprint(in2, out)
      results = append(results, regretIO{Input: in2, Output: out, Hash: hash})
    }()

    // Input 3
    var in3 interface{} = 100000
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 3 for format-cents threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(finance.FormatCents), false, in3)
      if err != nil {
        t.Logf("⚠️  Input 3 for format-cents error: %v", err)
        return
      }
      hash := fingerprint(in3, out)
      results = append(results, regretIO{Input: in3, Output: out, Hash: hash})
    }()

    if len(results) == 0 {
      t.Errorf("❌ format-cents: all inputs threw/errored — no capture possible")
      return
    }
    if err := writeRegret("format-cents", "FormatCents", results); err != nil {
      t.Fatalf("write .regret for format-cents: %v", err)
    }
    t.Logf("✅ format-cents captured (hash: %s)", results[0].Hash)
  })

  t.Run("apply-discount", func(t *testing.T) {
    var results []regretIO

    // Input 0
    var in0 interface{} = []interface{}{1000, 10}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 0 for apply-discount threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(finance.ApplyDiscount), true, in0)
      if err != nil {
        t.Logf("⚠️  Input 0 for apply-discount error: %v", err)
        return
      }
      hash := fingerprint(in0, out)
      results = append(results, regretIO{Input: in0, Output: out, Hash: hash})
    }()

    // Input 1
    var in1 interface{} = []interface{}{999, 50}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 1 for apply-discount threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(finance.ApplyDiscount), true, in1)
      if err != nil {
        t.Logf("⚠️  Input 1 for apply-discount error: %v", err)
        return
      }
      hash := fingerprint(in1, out)
      results = append(results, regretIO{Input: in1, Output: out, Hash: hash})
    }()

    // Input 2
    var in2 interface{} = []interface{}{1000, 150}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 2 for apply-discount threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(finance.ApplyDiscount), true, in2)
      if err != nil {
        t.Logf("⚠️  Input 2 for apply-discount error: %v", err)
        return
      }
      hash := fingerprint(in2, out)
      results = append(results, regretIO{Input: in2, Output: out, Hash: hash})
    }()

    // Input 3
    var in3 interface{} = []interface{}{1000, -5}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 3 for apply-discount threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(finance.ApplyDiscount), true, in3)
      if err != nil {
        t.Logf("⚠️  Input 3 for apply-discount error: %v", err)
        return
      }
      hash := fingerprint(in3, out)
      results = append(results, regretIO{Input: in3, Output: out, Hash: hash})
    }()

    if len(results) == 0 {
      t.Errorf("❌ apply-discount: all inputs threw/errored — no capture possible")
      return
    }
    if err := writeRegret("apply-discount", "ApplyDiscount", results); err != nil {
      t.Fatalf("write .regret for apply-discount: %v", err)
    }
    t.Logf("✅ apply-discount captured (hash: %s)", results[0].Hash)
  })

  t.Run("sum-cents", func(t *testing.T) {
    var results []regretIO

    // Input 0
    var in0 interface{} = "100|200|300"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 0 for sum-cents threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(finance.SumCents), false, in0)
      if err != nil {
        t.Logf("⚠️  Input 0 for sum-cents error: %v", err)
        return
      }
      hash := fingerprint(in0, out)
      results = append(results, regretIO{Input: in0, Output: out, Hash: hash})
    }()

    // Input 1
    var in1 interface{} = "100|-50|200"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 1 for sum-cents threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(finance.SumCents), false, in1)
      if err != nil {
        t.Logf("⚠️  Input 1 for sum-cents error: %v", err)
        return
      }
      hash := fingerprint(in1, out)
      results = append(results, regretIO{Input: in1, Output: out, Hash: hash})
    }()

    // Input 2
    var in2 interface{} = ""
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 2 for sum-cents threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(finance.SumCents), false, in2)
      if err != nil {
        t.Logf("⚠️  Input 2 for sum-cents error: %v", err)
        return
      }
      hash := fingerprint(in2, out)
      results = append(results, regretIO{Input: in2, Output: out, Hash: hash})
    }()

    // Input 3
    var in3 interface{} = "-100|-200"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 3 for sum-cents threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(finance.SumCents), false, in3)
      if err != nil {
        t.Logf("⚠️  Input 3 for sum-cents error: %v", err)
        return
      }
      hash := fingerprint(in3, out)
      results = append(results, regretIO{Input: in3, Output: out, Hash: hash})
    }()

    if len(results) == 0 {
      t.Errorf("❌ sum-cents: all inputs threw/errored — no capture possible")
      return
    }
    if err := writeRegret("sum-cents", "SumCents", results); err != nil {
      t.Fatalf("write .regret for sum-cents: %v", err)
    }
    t.Logf("✅ sum-cents captured (hash: %s)", results[0].Hash)
  })

  t.Run("parse-money", func(t *testing.T) {
    var results []regretIO

    // Input 0
    var in0 interface{} = "$10.99"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 0 for parse-money threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(finance.ParseMoney), false, in0)
      if err != nil {
        t.Logf("⚠️  Input 0 for parse-money error: %v", err)
        return
      }
      hash := fingerprint(in0, out)
      results = append(results, regretIO{Input: in0, Output: out, Hash: hash})
    }()

    // Input 1
    var in1 interface{} = "-$5.50"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 1 for parse-money threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(finance.ParseMoney), false, in1)
      if err != nil {
        t.Logf("⚠️  Input 1 for parse-money error: %v", err)
        return
      }
      hash := fingerprint(in1, out)
      results = append(results, regretIO{Input: in1, Output: out, Hash: hash})
    }()

    // Input 2
    var in2 interface{} = "$0.00"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 2 for parse-money threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(finance.ParseMoney), false, in2)
      if err != nil {
        t.Logf("⚠️  Input 2 for parse-money error: %v", err)
        return
      }
      hash := fingerprint(in2, out)
      results = append(results, regretIO{Input: in2, Output: out, Hash: hash})
    }()

    // Input 3
    var in3 interface{} = "10.99"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 3 for parse-money threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(finance.ParseMoney), false, in3)
      if err != nil {
        t.Logf("⚠️  Input 3 for parse-money error: %v", err)
        return
      }
      hash := fingerprint(in3, out)
      results = append(results, regretIO{Input: in3, Output: out, Hash: hash})
    }()

    if len(results) == 0 {
      t.Errorf("❌ parse-money: all inputs threw/errored — no capture possible")
      return
    }
    if err := writeRegret("parse-money", "ParseMoney", results); err != nil {
      t.Fatalf("write .regret for parse-money: %v", err)
    }
    t.Logf("✅ parse-money captured (hash: %s)", results[0].Hash)
  })

  t.Run("dedupe-strings", func(t *testing.T) {
    var results []regretIO

    // Input 0
    var in0 interface{} = "a|b|a|c|b"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 0 for dedupe-strings threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(collections.DedupeStrings), false, in0)
      if err != nil {
        t.Logf("⚠️  Input 0 for dedupe-strings error: %v", err)
        return
      }
      hash := fingerprint(in0, out)
      results = append(results, regretIO{Input: in0, Output: out, Hash: hash})
    }()

    // Input 1
    var in1 interface{} = ""
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 1 for dedupe-strings threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(collections.DedupeStrings), false, in1)
      if err != nil {
        t.Logf("⚠️  Input 1 for dedupe-strings error: %v", err)
        return
      }
      hash := fingerprint(in1, out)
      results = append(results, regretIO{Input: in1, Output: out, Hash: hash})
    }()

    // Input 2
    var in2 interface{} = "solo"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 2 for dedupe-strings threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(collections.DedupeStrings), false, in2)
      if err != nil {
        t.Logf("⚠️  Input 2 for dedupe-strings error: %v", err)
        return
      }
      hash := fingerprint(in2, out)
      results = append(results, regretIO{Input: in2, Output: out, Hash: hash})
    }()

    if len(results) == 0 {
      t.Errorf("❌ dedupe-strings: all inputs threw/errored — no capture possible")
      return
    }
    if err := writeRegret("dedupe-strings", "DedupeStrings", results); err != nil {
      t.Fatalf("write .regret for dedupe-strings: %v", err)
    }
    t.Logf("✅ dedupe-strings captured (hash: %s)", results[0].Hash)
  })

  t.Run("sort-and-join", func(t *testing.T) {
    var results []regretIO

    // Input 0
    var in0 interface{} = []interface{}{"banana|apple|cherry", ","}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 0 for sort-and-join threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(collections.SortAndJoin), true, in0)
      if err != nil {
        t.Logf("⚠️  Input 0 for sort-and-join error: %v", err)
        return
      }
      hash := fingerprint(in0, out)
      results = append(results, regretIO{Input: in0, Output: out, Hash: hash})
    }()

    // Input 1
    var in1 interface{} = []interface{}{"solo", "-"}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 1 for sort-and-join threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(collections.SortAndJoin), true, in1)
      if err != nil {
        t.Logf("⚠️  Input 1 for sort-and-join error: %v", err)
        return
      }
      hash := fingerprint(in1, out)
      results = append(results, regretIO{Input: in1, Output: out, Hash: hash})
    }()

    // Input 2
    var in2 interface{} = []interface{}{"", ","}
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 2 for sort-and-join threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(collections.SortAndJoin), true, in2)
      if err != nil {
        t.Logf("⚠️  Input 2 for sort-and-join error: %v", err)
        return
      }
      hash := fingerprint(in2, out)
      results = append(results, regretIO{Input: in2, Output: out, Hash: hash})
    }()

    if len(results) == 0 {
      t.Errorf("❌ sort-and-join: all inputs threw/errored — no capture possible")
      return
    }
    if err := writeRegret("sort-and-join", "SortAndJoin", results); err != nil {
      t.Fatalf("write .regret for sort-and-join: %v", err)
    }
    t.Logf("✅ sort-and-join captured (hash: %s)", results[0].Hash)
  })

  t.Run("count-words", func(t *testing.T) {
    var results []regretIO

    // Input 0
    var in0 interface{} = "The Quick Brown Fox the"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 0 for count-words threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(collections.CountWords), false, in0)
      if err != nil {
        t.Logf("⚠️  Input 0 for count-words error: %v", err)
        return
      }
      hash := fingerprint(in0, out)
      results = append(results, regretIO{Input: in0, Output: out, Hash: hash})
    }()

    // Input 1
    var in1 interface{} = ""
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 1 for count-words threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(collections.CountWords), false, in1)
      if err != nil {
        t.Logf("⚠️  Input 1 for count-words error: %v", err)
        return
      }
      hash := fingerprint(in1, out)
      results = append(results, regretIO{Input: in1, Output: out, Hash: hash})
    }()

    // Input 2
    var in2 interface{} = "the The THE"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 2 for count-words threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(collections.CountWords), false, in2)
      if err != nil {
        t.Logf("⚠️  Input 2 for count-words error: %v", err)
        return
      }
      hash := fingerprint(in2, out)
      results = append(results, regretIO{Input: in2, Output: out, Hash: hash})
    }()

    if len(results) == 0 {
      t.Errorf("❌ count-words: all inputs threw/errored — no capture possible")
      return
    }
    if err := writeRegret("count-words", "CountWords", results); err != nil {
      t.Fatalf("write .regret for count-words: %v", err)
    }
    t.Logf("✅ count-words captured (hash: %s)", results[0].Hash)
  })

  t.Run("intersect", func(t *testing.T) {
    var results []regretIO

    // Input 0
    var in0 interface{} = "a|b|c||b|c|d"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 0 for intersect threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(collections.Intersect), false, in0)
      if err != nil {
        t.Logf("⚠️  Input 0 for intersect error: %v", err)
        return
      }
      hash := fingerprint(in0, out)
      results = append(results, regretIO{Input: in0, Output: out, Hash: hash})
    }()

    // Input 1
    var in1 interface{} = "a|b||c|d"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 1 for intersect threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(collections.Intersect), false, in1)
      if err != nil {
        t.Logf("⚠️  Input 1 for intersect error: %v", err)
        return
      }
      hash := fingerprint(in1, out)
      results = append(results, regretIO{Input: in1, Output: out, Hash: hash})
    }()

    // Input 2
    var in2 interface{} = "x|y|z||a|b|c|x"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 2 for intersect threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(collections.Intersect), false, in2)
      if err != nil {
        t.Logf("⚠️  Input 2 for intersect error: %v", err)
        return
      }
      hash := fingerprint(in2, out)
      results = append(results, regretIO{Input: in2, Output: out, Hash: hash})
    }()

    if len(results) == 0 {
      t.Errorf("❌ intersect: all inputs threw/errored — no capture possible")
      return
    }
    if err := writeRegret("intersect", "Intersect", results); err != nil {
      t.Fatalf("write .regret for intersect: %v", err)
    }
    t.Logf("✅ intersect captured (hash: %s)", results[0].Hash)
  })

  t.Run("chunk", func(t *testing.T) {
    var results []regretIO

    // Input 0
    var in0 interface{} = "1|2|3|4|5|2"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 0 for chunk threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(collections.Chunk), false, in0)
      if err != nil {
        t.Logf("⚠️  Input 0 for chunk error: %v", err)
        return
      }
      hash := fingerprint(in0, out)
      results = append(results, regretIO{Input: in0, Output: out, Hash: hash})
    }()

    // Input 1
    var in1 interface{} = "1|2|3|5"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 1 for chunk threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(collections.Chunk), false, in1)
      if err != nil {
        t.Logf("⚠️  Input 1 for chunk error: %v", err)
        return
      }
      hash := fingerprint(in1, out)
      results = append(results, regretIO{Input: in1, Output: out, Hash: hash})
    }()

    // Input 2
    var in2 interface{} = "1|2|3|0"
    func() {
      defer func() {
        if r := recover(); r != nil {
          t.Logf("⚠️  Input 2 for chunk threw: %v", r)
        }
      }()
      out, err := invokeEntry(reflect.ValueOf(collections.Chunk), false, in2)
      if err != nil {
        t.Logf("⚠️  Input 2 for chunk error: %v", err)
        return
      }
      hash := fingerprint(in2, out)
      results = append(results, regretIO{Input: in2, Output: out, Hash: hash})
    }()

    if len(results) == 0 {
      t.Errorf("❌ chunk: all inputs threw/errored — no capture possible")
      return
    }
    if err := writeRegret("chunk", "Chunk", results); err != nil {
      t.Fatalf("write .regret for chunk: %v", err)
    }
    t.Logf("✅ chunk captured (hash: %s)", results[0].Hash)
  })

}
