// regret_validate_test.go — auto-generated by capture_go.sh
// DO NOT EDIT — this file is regenerated on each validate run.
package regrettest

import (
        datetime "github.com/regrets/proof-go-independent/datetime"
        finance "github.com/regrets/proof-go-independent/finance"
        collections "github.com/regrets/proof-go-independent/collections"
        "os"
        "reflect"
        "testing"
)

func TestRegretValidate(t *testing.T) {
  t.Run("parse-iso8601", func(t *testing.T) {
    regretPath := "parse-iso8601.regret"
    data, err := os.ReadFile(regretPath)
    if err != nil {
      t.Fatalf("read .regret for parse-iso8601: %v", err)
    }
    gInput, _, gHash, gInputsList, err := parseRegret(string(data))
    if err != nil {
      t.Fatalf("parse .regret for parse-iso8601: %v", err)
    }

    // Validate the primary input
    out, err := invokeEntry(reflect.ValueOf(datetime.ParseISO8601), false, gInput)
    if err != nil {
      t.Fatalf("invoke ParseISO8601: %v", err)
    }
    newHash := fingerprint(gInput, out)
    if newHash != gHash {
      t.Errorf("❌ parse-iso8601 FAIL — expected %s got %s", gHash, newHash)
    } else {
      t.Logf("✅ parse-iso8601 %s PASS", newHash)
    }

    // Validate INPUTS[1+] if present
    for i, item := range gInputsList {
      inVal := item["input"]
      expectedHash := item["hash"].(string)
      outN, err := invokeEntry(reflect.ValueOf(datetime.ParseISO8601), false, inVal)
      if err != nil {
        t.Errorf("❌ parse-iso8601 INPUTS[%d] invoke error: %v", i, err)
        continue
      }
      gotHash := fingerprint(inVal, outN)
      if gotHash != expectedHash {
        t.Errorf("❌ parse-iso8601 INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)
      } else {
        t.Logf("✅ parse-iso8601 INPUTS[%d] %s PASS", i, gotHash)
      }
    }
  })

  t.Run("format-duration", func(t *testing.T) {
    regretPath := "format-duration.regret"
    data, err := os.ReadFile(regretPath)
    if err != nil {
      t.Fatalf("read .regret for format-duration: %v", err)
    }
    gInput, _, gHash, gInputsList, err := parseRegret(string(data))
    if err != nil {
      t.Fatalf("parse .regret for format-duration: %v", err)
    }

    // Validate the primary input
    out, err := invokeEntry(reflect.ValueOf(datetime.FormatDuration), false, gInput)
    if err != nil {
      t.Fatalf("invoke FormatDuration: %v", err)
    }
    newHash := fingerprint(gInput, out)
    if newHash != gHash {
      t.Errorf("❌ format-duration FAIL — expected %s got %s", gHash, newHash)
    } else {
      t.Logf("✅ format-duration %s PASS", newHash)
    }

    // Validate INPUTS[1+] if present
    for i, item := range gInputsList {
      inVal := item["input"]
      expectedHash := item["hash"].(string)
      outN, err := invokeEntry(reflect.ValueOf(datetime.FormatDuration), false, inVal)
      if err != nil {
        t.Errorf("❌ format-duration INPUTS[%d] invoke error: %v", i, err)
        continue
      }
      gotHash := fingerprint(inVal, outN)
      if gotHash != expectedHash {
        t.Errorf("❌ format-duration INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)
      } else {
        t.Logf("✅ format-duration INPUTS[%d] %s PASS", i, gotHash)
      }
    }
  })

  t.Run("weekday-name", func(t *testing.T) {
    regretPath := "weekday-name.regret"
    data, err := os.ReadFile(regretPath)
    if err != nil {
      t.Fatalf("read .regret for weekday-name: %v", err)
    }
    gInput, _, gHash, gInputsList, err := parseRegret(string(data))
    if err != nil {
      t.Fatalf("parse .regret for weekday-name: %v", err)
    }

    // Validate the primary input
    out, err := invokeEntry(reflect.ValueOf(datetime.WeekdayName), false, gInput)
    if err != nil {
      t.Fatalf("invoke WeekdayName: %v", err)
    }
    newHash := fingerprint(gInput, out)
    if newHash != gHash {
      t.Errorf("❌ weekday-name FAIL — expected %s got %s", gHash, newHash)
    } else {
      t.Logf("✅ weekday-name %s PASS", newHash)
    }

    // Validate INPUTS[1+] if present
    for i, item := range gInputsList {
      inVal := item["input"]
      expectedHash := item["hash"].(string)
      outN, err := invokeEntry(reflect.ValueOf(datetime.WeekdayName), false, inVal)
      if err != nil {
        t.Errorf("❌ weekday-name INPUTS[%d] invoke error: %v", i, err)
        continue
      }
      gotHash := fingerprint(inVal, outN)
      if gotHash != expectedHash {
        t.Errorf("❌ weekday-name INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)
      } else {
        t.Logf("✅ weekday-name INPUTS[%d] %s PASS", i, gotHash)
      }
    }
  })

  t.Run("days-between", func(t *testing.T) {
    regretPath := "days-between.regret"
    data, err := os.ReadFile(regretPath)
    if err != nil {
      t.Fatalf("read .regret for days-between: %v", err)
    }
    gInput, _, gHash, gInputsList, err := parseRegret(string(data))
    if err != nil {
      t.Fatalf("parse .regret for days-between: %v", err)
    }

    // Validate the primary input
    out, err := invokeEntry(reflect.ValueOf(datetime.DaysBetween), true, gInput)
    if err != nil {
      t.Fatalf("invoke DaysBetween: %v", err)
    }
    newHash := fingerprint(gInput, out)
    if newHash != gHash {
      t.Errorf("❌ days-between FAIL — expected %s got %s", gHash, newHash)
    } else {
      t.Logf("✅ days-between %s PASS", newHash)
    }

    // Validate INPUTS[1+] if present
    for i, item := range gInputsList {
      inVal := item["input"]
      expectedHash := item["hash"].(string)
      outN, err := invokeEntry(reflect.ValueOf(datetime.DaysBetween), true, inVal)
      if err != nil {
        t.Errorf("❌ days-between INPUTS[%d] invoke error: %v", i, err)
        continue
      }
      gotHash := fingerprint(inVal, outN)
      if gotHash != expectedHash {
        t.Errorf("❌ days-between INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)
      } else {
        t.Logf("✅ days-between INPUTS[%d] %s PASS", i, gotHash)
      }
    }
  })

  t.Run("add-business-days", func(t *testing.T) {
    regretPath := "add-business-days.regret"
    data, err := os.ReadFile(regretPath)
    if err != nil {
      t.Fatalf("read .regret for add-business-days: %v", err)
    }
    gInput, _, gHash, gInputsList, err := parseRegret(string(data))
    if err != nil {
      t.Fatalf("parse .regret for add-business-days: %v", err)
    }

    // Validate the primary input
    out, err := invokeEntry(reflect.ValueOf(datetime.AddBusinessDays), true, gInput)
    if err != nil {
      t.Fatalf("invoke AddBusinessDays: %v", err)
    }
    newHash := fingerprint(gInput, out)
    if newHash != gHash {
      t.Errorf("❌ add-business-days FAIL — expected %s got %s", gHash, newHash)
    } else {
      t.Logf("✅ add-business-days %s PASS", newHash)
    }

    // Validate INPUTS[1+] if present
    for i, item := range gInputsList {
      inVal := item["input"]
      expectedHash := item["hash"].(string)
      outN, err := invokeEntry(reflect.ValueOf(datetime.AddBusinessDays), true, inVal)
      if err != nil {
        t.Errorf("❌ add-business-days INPUTS[%d] invoke error: %v", i, err)
        continue
      }
      gotHash := fingerprint(inVal, outN)
      if gotHash != expectedHash {
        t.Errorf("❌ add-business-days INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)
      } else {
        t.Logf("✅ add-business-days INPUTS[%d] %s PASS", i, gotHash)
      }
    }
  })

  t.Run("format-cents", func(t *testing.T) {
    regretPath := "format-cents.regret"
    data, err := os.ReadFile(regretPath)
    if err != nil {
      t.Fatalf("read .regret for format-cents: %v", err)
    }
    gInput, _, gHash, gInputsList, err := parseRegret(string(data))
    if err != nil {
      t.Fatalf("parse .regret for format-cents: %v", err)
    }

    // Validate the primary input
    out, err := invokeEntry(reflect.ValueOf(finance.FormatCents), false, gInput)
    if err != nil {
      t.Fatalf("invoke FormatCents: %v", err)
    }
    newHash := fingerprint(gInput, out)
    if newHash != gHash {
      t.Errorf("❌ format-cents FAIL — expected %s got %s", gHash, newHash)
    } else {
      t.Logf("✅ format-cents %s PASS", newHash)
    }

    // Validate INPUTS[1+] if present
    for i, item := range gInputsList {
      inVal := item["input"]
      expectedHash := item["hash"].(string)
      outN, err := invokeEntry(reflect.ValueOf(finance.FormatCents), false, inVal)
      if err != nil {
        t.Errorf("❌ format-cents INPUTS[%d] invoke error: %v", i, err)
        continue
      }
      gotHash := fingerprint(inVal, outN)
      if gotHash != expectedHash {
        t.Errorf("❌ format-cents INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)
      } else {
        t.Logf("✅ format-cents INPUTS[%d] %s PASS", i, gotHash)
      }
    }
  })

  t.Run("apply-discount", func(t *testing.T) {
    regretPath := "apply-discount.regret"
    data, err := os.ReadFile(regretPath)
    if err != nil {
      t.Fatalf("read .regret for apply-discount: %v", err)
    }
    gInput, _, gHash, gInputsList, err := parseRegret(string(data))
    if err != nil {
      t.Fatalf("parse .regret for apply-discount: %v", err)
    }

    // Validate the primary input
    out, err := invokeEntry(reflect.ValueOf(finance.ApplyDiscount), true, gInput)
    if err != nil {
      t.Fatalf("invoke ApplyDiscount: %v", err)
    }
    newHash := fingerprint(gInput, out)
    if newHash != gHash {
      t.Errorf("❌ apply-discount FAIL — expected %s got %s", gHash, newHash)
    } else {
      t.Logf("✅ apply-discount %s PASS", newHash)
    }

    // Validate INPUTS[1+] if present
    for i, item := range gInputsList {
      inVal := item["input"]
      expectedHash := item["hash"].(string)
      outN, err := invokeEntry(reflect.ValueOf(finance.ApplyDiscount), true, inVal)
      if err != nil {
        t.Errorf("❌ apply-discount INPUTS[%d] invoke error: %v", i, err)
        continue
      }
      gotHash := fingerprint(inVal, outN)
      if gotHash != expectedHash {
        t.Errorf("❌ apply-discount INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)
      } else {
        t.Logf("✅ apply-discount INPUTS[%d] %s PASS", i, gotHash)
      }
    }
  })

  t.Run("sum-cents", func(t *testing.T) {
    regretPath := "sum-cents.regret"
    data, err := os.ReadFile(regretPath)
    if err != nil {
      t.Fatalf("read .regret for sum-cents: %v", err)
    }
    gInput, _, gHash, gInputsList, err := parseRegret(string(data))
    if err != nil {
      t.Fatalf("parse .regret for sum-cents: %v", err)
    }

    // Validate the primary input
    out, err := invokeEntry(reflect.ValueOf(finance.SumCents), false, gInput)
    if err != nil {
      t.Fatalf("invoke SumCents: %v", err)
    }
    newHash := fingerprint(gInput, out)
    if newHash != gHash {
      t.Errorf("❌ sum-cents FAIL — expected %s got %s", gHash, newHash)
    } else {
      t.Logf("✅ sum-cents %s PASS", newHash)
    }

    // Validate INPUTS[1+] if present
    for i, item := range gInputsList {
      inVal := item["input"]
      expectedHash := item["hash"].(string)
      outN, err := invokeEntry(reflect.ValueOf(finance.SumCents), false, inVal)
      if err != nil {
        t.Errorf("❌ sum-cents INPUTS[%d] invoke error: %v", i, err)
        continue
      }
      gotHash := fingerprint(inVal, outN)
      if gotHash != expectedHash {
        t.Errorf("❌ sum-cents INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)
      } else {
        t.Logf("✅ sum-cents INPUTS[%d] %s PASS", i, gotHash)
      }
    }
  })

  t.Run("parse-money", func(t *testing.T) {
    regretPath := "parse-money.regret"
    data, err := os.ReadFile(regretPath)
    if err != nil {
      t.Fatalf("read .regret for parse-money: %v", err)
    }
    gInput, _, gHash, gInputsList, err := parseRegret(string(data))
    if err != nil {
      t.Fatalf("parse .regret for parse-money: %v", err)
    }

    // Validate the primary input
    out, err := invokeEntry(reflect.ValueOf(finance.ParseMoney), false, gInput)
    if err != nil {
      t.Fatalf("invoke ParseMoney: %v", err)
    }
    newHash := fingerprint(gInput, out)
    if newHash != gHash {
      t.Errorf("❌ parse-money FAIL — expected %s got %s", gHash, newHash)
    } else {
      t.Logf("✅ parse-money %s PASS", newHash)
    }

    // Validate INPUTS[1+] if present
    for i, item := range gInputsList {
      inVal := item["input"]
      expectedHash := item["hash"].(string)
      outN, err := invokeEntry(reflect.ValueOf(finance.ParseMoney), false, inVal)
      if err != nil {
        t.Errorf("❌ parse-money INPUTS[%d] invoke error: %v", i, err)
        continue
      }
      gotHash := fingerprint(inVal, outN)
      if gotHash != expectedHash {
        t.Errorf("❌ parse-money INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)
      } else {
        t.Logf("✅ parse-money INPUTS[%d] %s PASS", i, gotHash)
      }
    }
  })

  t.Run("dedupe-strings", func(t *testing.T) {
    regretPath := "dedupe-strings.regret"
    data, err := os.ReadFile(regretPath)
    if err != nil {
      t.Fatalf("read .regret for dedupe-strings: %v", err)
    }
    gInput, _, gHash, gInputsList, err := parseRegret(string(data))
    if err != nil {
      t.Fatalf("parse .regret for dedupe-strings: %v", err)
    }

    // Validate the primary input
    out, err := invokeEntry(reflect.ValueOf(collections.DedupeStrings), false, gInput)
    if err != nil {
      t.Fatalf("invoke DedupeStrings: %v", err)
    }
    newHash := fingerprint(gInput, out)
    if newHash != gHash {
      t.Errorf("❌ dedupe-strings FAIL — expected %s got %s", gHash, newHash)
    } else {
      t.Logf("✅ dedupe-strings %s PASS", newHash)
    }

    // Validate INPUTS[1+] if present
    for i, item := range gInputsList {
      inVal := item["input"]
      expectedHash := item["hash"].(string)
      outN, err := invokeEntry(reflect.ValueOf(collections.DedupeStrings), false, inVal)
      if err != nil {
        t.Errorf("❌ dedupe-strings INPUTS[%d] invoke error: %v", i, err)
        continue
      }
      gotHash := fingerprint(inVal, outN)
      if gotHash != expectedHash {
        t.Errorf("❌ dedupe-strings INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)
      } else {
        t.Logf("✅ dedupe-strings INPUTS[%d] %s PASS", i, gotHash)
      }
    }
  })

  t.Run("sort-and-join", func(t *testing.T) {
    regretPath := "sort-and-join.regret"
    data, err := os.ReadFile(regretPath)
    if err != nil {
      t.Fatalf("read .regret for sort-and-join: %v", err)
    }
    gInput, _, gHash, gInputsList, err := parseRegret(string(data))
    if err != nil {
      t.Fatalf("parse .regret for sort-and-join: %v", err)
    }

    // Validate the primary input
    out, err := invokeEntry(reflect.ValueOf(collections.SortAndJoin), true, gInput)
    if err != nil {
      t.Fatalf("invoke SortAndJoin: %v", err)
    }
    newHash := fingerprint(gInput, out)
    if newHash != gHash {
      t.Errorf("❌ sort-and-join FAIL — expected %s got %s", gHash, newHash)
    } else {
      t.Logf("✅ sort-and-join %s PASS", newHash)
    }

    // Validate INPUTS[1+] if present
    for i, item := range gInputsList {
      inVal := item["input"]
      expectedHash := item["hash"].(string)
      outN, err := invokeEntry(reflect.ValueOf(collections.SortAndJoin), true, inVal)
      if err != nil {
        t.Errorf("❌ sort-and-join INPUTS[%d] invoke error: %v", i, err)
        continue
      }
      gotHash := fingerprint(inVal, outN)
      if gotHash != expectedHash {
        t.Errorf("❌ sort-and-join INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)
      } else {
        t.Logf("✅ sort-and-join INPUTS[%d] %s PASS", i, gotHash)
      }
    }
  })

  t.Run("count-words", func(t *testing.T) {
    regretPath := "count-words.regret"
    data, err := os.ReadFile(regretPath)
    if err != nil {
      t.Fatalf("read .regret for count-words: %v", err)
    }
    gInput, _, gHash, gInputsList, err := parseRegret(string(data))
    if err != nil {
      t.Fatalf("parse .regret for count-words: %v", err)
    }

    // Validate the primary input
    out, err := invokeEntry(reflect.ValueOf(collections.CountWords), false, gInput)
    if err != nil {
      t.Fatalf("invoke CountWords: %v", err)
    }
    newHash := fingerprint(gInput, out)
    if newHash != gHash {
      t.Errorf("❌ count-words FAIL — expected %s got %s", gHash, newHash)
    } else {
      t.Logf("✅ count-words %s PASS", newHash)
    }

    // Validate INPUTS[1+] if present
    for i, item := range gInputsList {
      inVal := item["input"]
      expectedHash := item["hash"].(string)
      outN, err := invokeEntry(reflect.ValueOf(collections.CountWords), false, inVal)
      if err != nil {
        t.Errorf("❌ count-words INPUTS[%d] invoke error: %v", i, err)
        continue
      }
      gotHash := fingerprint(inVal, outN)
      if gotHash != expectedHash {
        t.Errorf("❌ count-words INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)
      } else {
        t.Logf("✅ count-words INPUTS[%d] %s PASS", i, gotHash)
      }
    }
  })

  t.Run("intersect", func(t *testing.T) {
    regretPath := "intersect.regret"
    data, err := os.ReadFile(regretPath)
    if err != nil {
      t.Fatalf("read .regret for intersect: %v", err)
    }
    gInput, _, gHash, gInputsList, err := parseRegret(string(data))
    if err != nil {
      t.Fatalf("parse .regret for intersect: %v", err)
    }

    // Validate the primary input
    out, err := invokeEntry(reflect.ValueOf(collections.Intersect), false, gInput)
    if err != nil {
      t.Fatalf("invoke Intersect: %v", err)
    }
    newHash := fingerprint(gInput, out)
    if newHash != gHash {
      t.Errorf("❌ intersect FAIL — expected %s got %s", gHash, newHash)
    } else {
      t.Logf("✅ intersect %s PASS", newHash)
    }

    // Validate INPUTS[1+] if present
    for i, item := range gInputsList {
      inVal := item["input"]
      expectedHash := item["hash"].(string)
      outN, err := invokeEntry(reflect.ValueOf(collections.Intersect), false, inVal)
      if err != nil {
        t.Errorf("❌ intersect INPUTS[%d] invoke error: %v", i, err)
        continue
      }
      gotHash := fingerprint(inVal, outN)
      if gotHash != expectedHash {
        t.Errorf("❌ intersect INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)
      } else {
        t.Logf("✅ intersect INPUTS[%d] %s PASS", i, gotHash)
      }
    }
  })

  t.Run("chunk", func(t *testing.T) {
    regretPath := "chunk.regret"
    data, err := os.ReadFile(regretPath)
    if err != nil {
      t.Fatalf("read .regret for chunk: %v", err)
    }
    gInput, _, gHash, gInputsList, err := parseRegret(string(data))
    if err != nil {
      t.Fatalf("parse .regret for chunk: %v", err)
    }

    // Validate the primary input
    out, err := invokeEntry(reflect.ValueOf(collections.Chunk), false, gInput)
    if err != nil {
      t.Fatalf("invoke Chunk: %v", err)
    }
    newHash := fingerprint(gInput, out)
    if newHash != gHash {
      t.Errorf("❌ chunk FAIL — expected %s got %s", gHash, newHash)
    } else {
      t.Logf("✅ chunk %s PASS", newHash)
    }

    // Validate INPUTS[1+] if present
    for i, item := range gInputsList {
      inVal := item["input"]
      expectedHash := item["hash"].(string)
      outN, err := invokeEntry(reflect.ValueOf(collections.Chunk), false, inVal)
      if err != nil {
        t.Errorf("❌ chunk INPUTS[%d] invoke error: %v", i, err)
        continue
      }
      gotHash := fingerprint(inVal, outN)
      if gotHash != expectedHash {
        t.Errorf("❌ chunk INPUTS[%d] FAIL — expected %s got %s", i, expectedHash, gotHash)
      } else {
        t.Logf("✅ chunk INPUTS[%d] %s PASS", i, gotHash)
      }
    }
  })

}
