// example.zig — minimal Zig source for the Regrets Zig stack proof-of-concept.
//
// Three pure top-level functions:
//   - add(a: i64, b: i64) i64
//   - greet(name: []const u8, excited: bool) []const u8
//   - titleCaseWords(input: []const u8) []const u8
//
// These are the "functions under fingerprint". They are intentionally trivial
// so the focus stays on demonstrating the capture→refactor→validate flow,
// not on the business logic.
//
// After `regret capture`, a refactor that preserves the input→output contract
// (e.g. rewriting `a + b` to `b + a`) should PASS validate. A breaking
// refactor (e.g. returning `a - b` instead of `a + b`) should FAIL validate.
//
// All functions are `pub` so the RegretRunner.zig (generated by
// capture_zig.sh) can `@import` this file and call them via `@field`.

const std = @import("std");

/// Integer addition. Two i64 args → i64 result.
pub fn add(a: i64, b: i64) i64 {
    return a + b;
}

/// Greeting with optional excitement. String × Boolean → String.
/// Returns a heap-allocated string; the caller (runner) owns the memory
/// and must free it via allocator.free.
pub fn greet(allocator: std.mem.Allocator, name: []const u8, excited: bool) ![]u8 {
    const base = try std.fmt.allocPrint(allocator, "Hello, {s}", .{name});
    if (excited) {
        defer allocator.free(base);
        return std.fmt.allocPrint(allocator, "{s}!", .{base});
    }
    return base;
}

/// Title-case the first letter of each word. String → String.
/// Returns a heap-allocated string; the caller (runner) owns the memory.
pub fn titleCaseWords(allocator: std.mem.Allocator, input: []const u8) ![]u8 {
    const out = try allocator.alloc(u8, input.len);
    @memcpy(out, input);
    var make_upper = true;
    for (out) |*c| {
        if (make_upper and std.ascii.isAlphabetic(c.*)) {
            c.* = std.ascii.toUpper(c.*);
            make_upper = false;
        } else if (!std.ascii.isAlphabetic(c.*)) {
            // whitespace, punctuation → next alphabetic char becomes upper
            make_upper = true;
        } else {
            c.* = std.ascii.toLower(c.*);
        }
    }
    return out;
}
